kalite/control_panel/templates/control_panel/base.html
This request is to correct the issue written below
UI Issue - Improper overriding of search bar #2821
=> overrided the  search icon size properly

kalite/coachreports/templates/coachreports/tabular_view.html, kalite/coachreports/views.py, kalite/distributed/tests/browser_tests/coachreports.py, kalite/playlist/models.py
Is this on the right track to resolve #2808?
=> Tabular coach reports can now be generated for playlists as well as topics

kalite/distributed/static/js/distributed/content/models.js, kalite/distributed/static/js/distributed/content/views.js, kalite/main/migrations/0035_auto__chg_field_contentlog_progress.py, kalite/main/models.py
@aronasorman.
Branch:  develop
Issue: https://github.com/learningequality/ka-lite/issues/2767
Related PR: https://github.com/learningequality/ka-lite/pull/2790
I changed `IntegerField` to `FloatField` for percentage use. 
Attached screen shoot:
=> Refactor ContentLog class. Use FloatField instead of IntegerField for progress field.

python-packages/securesync/devices/models.py, python-packages/securesync/engine/models.py
Jamie updated the uuid generating mechanism with nalanda's uuid and fixed issue in #2837
=> Uuid update fixed "UNIQUE constraint failed: main_contentlog.id"

kalite/distributed/static/css/distributed/sidebar.css
Moved sidebar tab chevron up by a few pixels and changed padding for
sidebar descriptions to make them look slightly cleaner. They were annoying me a bit.
My first pull request!
=> Fixed some alignments in sidebar

kalite/main/migrations/0034_auto__del_index_contentlog_content_source__del_index_contentlog_conten.py, kalite/main/models.py
fixed issue in #2836
deleted db_index for ContentLog in content_source and content_kind
generated index_together for user and content_id
=> imporved data syncing

kalite/updates/views.py
#2855 
For 0.13 added warning.
=> Warning for Videos Download

kalite/coachreports/hbtemplates/coach_nav/reports-nav.handlebars, kalite/coachreports/urls.py, kalite/control_panel/templates/control_panel/partials/_device_table.html, kalite/student_testing/models.py, kalite/updates/urls.py
=> Test.all will reutrn empty if not Nalanda

kalite/facility/templates/facility/login.html, kalite/facility/views.py
A fairly simple change :) And maybe more a small example or madman OCD. But putting a link somewhere is template logic, not view logic :)
=> use the url template tag instead of a context variable

kalite/distributed/static/js/distributed/exercises/views.js
=> Properly render exercises when not logged in.

kalite/distributed/settings.py, kalite/i18n/__init__.py, kalite/settings.py, kalite/topic_tools/__init__.py
Fixes issue #2902 and possibly various other problems.
=> Updated khan-exercises directory paths

kalite/distributed/static/js/distributed/exercises/views.js
Add an event listener to elements with the class "perseus-input"
so that it triggers the click event on the check answer button.
Resolves #2833.
=> Pressing enter in perseus exercise submits answer

kalite/testing/mixins/browser_mixins.py
Which will throw a TimeoutException instead of quietly
failing. Also generously increased the wait time.
=> Replace time.wait with more robust WebDriverWait

kalite/distributed/static/js/distributed/exercises/views.js, kalite/distributed/static/js/distributed/software-keyboard.js
This fixes #2907, but only for Khan-Exercises.
Now also fixed for Perseus.
=> Software keyboard fix

bin/kalite, kalite/distributed/management/commands/setup.py, kalitectl.py, manage.py, scripts/cronstart.sh, scripts/graph_models.sh, scripts/optimizerpi.sh, scripts/run_command.sh, scripts/runatboot.sh, scripts/serverstart.sh, scripts/serverstop.sh
Do not merge yet... aggregating stuff for closing tasks in #2919
=> Remaining issues on kalite command fixing #2919

kalite/distributed/custom_context_processors.py, kalite/distributed/templates/distributed/partials/khan_dummy_channel_translation.html
Allows translation of the channel data that populates the footer and home page.
@aronasorman
=> Allow translation of Khan channel data

kalitectl.py, manage.py
=> Fixes for #2919 Chapter 2

kalite/playlist/playlists.json, kalite/playlist/static/js/playlist/assign_playlists.js, kalite/playlist/templates/playlist/assign_playlists.html
=> Added Exam Prep Playlists

kalite/control_panel/templates/control_panel/partials/_device_table.html
Hi @aronasorman this fixed #2972 
I attached screenshot.
=> add html div tag at register devise button to align it on center.

kalitectl.py
=> Fixes for #2919 Chapter 3

kalite/control_panel/templates/control_panel/facility_management.html, kalite/control_panel/templates/control_panel/zone_form.html, kalite/control_panel/templates/control_panel/zone_management.html, kalite/distributed/templates/distributed/404.html, kalite/distributed/templates/distributed/500.html, kalite/facility/templates/facility/login.html
Hi @MCGallaspy - this fixes #3057.
=> Fix text for page title.

kalite/distributed/templates/distributed/base_manage.html
Hi @MCGallaspy this fixed #3049.
i attached screenshot.
=> Coach manage page: user tab is not aligned properly

kalite/control_panel/templates/control_panel/facility_management.html
=> Only one tab should be active per template

kalite/coachreports/hbtemplates/student_progress/playlist-progress-container.handlebars, kalite/coachreports/hbtemplates/student_progress/playlist-progress-details.handlebars, kalite/coachreports/hbtemplates/student_progress/student-progress-container.handlebars, kalite/coachreports/models.py, kalite/control_panel/static/css/control_panel/student-report.css
=> Student progress report fix up

kalite/control_panel/templates/control_panel/partials/_facility_table.html
HI @MCGallaspy this fixed #3085
=> facilities table extra empty row.

kalite/distributed/templates/distributed/base_manage.html
Hi @MCGallaspy this fixed #3089
=> Manage navigation showing on guest user

kalite/distributed/static/css/distributed/bootstrap-overrides.css, kalite/distributed/templates/distributed/base.html
Hi @aronasorman, This fixed #3097 . This will fix the nav bar when resizing until `640 viewport size`.
Attached here are my screenshots.
Viewport size 640: 
Viewport size 768: 
/review: @arceduardvincent
=> Fixed navbar elements are misaligned when viewing with a viewport width of <768.

CONTRIBUTING.md
A first pass. Something is better than nothing, no?
=> Add CONTRIBUTING.md file that will appear when opening issues/PRs

kalite/updates/static/css/updates/update_languages.css, kalite/updates/static/js/updates/update_languages.js
Hi @aronasorman - this fixed #3084 - UX issue on update_languages page and  the footer issue as reported on #3003.
Screenshot is attached below:
=> Fix alignment issue on update_languages page.

kalite/distributed/static/js/distributed/search_autocomplete.js, kalite/facility/tests/form_tests.py
Hi @MCGallaspy this fixed #3095 
/review: @djallado
=> Disabled search button if value is null.

kalite/ab_testing/dynamic_assets.py, kalite/coachreports/hbtemplates/coach_nav/reports-nav.handlebars, kalite/coachreports/static/js/coachreports/base.js, kalite/coachreports/templates/coachreports/base.html, kalite/coachreports/templates/coachreports/landing_page.html, kalite/coachreports/templates/coachreports/spending_report_detail_view.html, kalite/coachreports/templates/coachreports/spending_report_view.html, kalite/coachreports/tests/coachreport_tests.py, kalite/coachreports/urls.py, kalite/coachreports/views.py, kalite/distributed/custom_context_processors.py, kalite/distributed/static/css/distributed/bootstrap-overrides.css, kalite/distributed/templates/distributed/base_teach.html, kalite/distributed/tests/browser_tests/nalanda.py, kalite/distributed/tests/browser_tests/quiz.py, kalite/playlist/tests.py, kalite/playlist/urls.py, kalite/settings.py, kalite/store/tests.py, kalite/student_testing/models.py, kalite/student_testing/tests.py, kalite/student_testing/urls.py, kalite/updates/urls.py
Even though 0.13 won't be used for Nalanda for quite some time, they will be using the updated Hub server, so we need these fixes to avoid breaking functionality for them on there.
=> Fix Nalanda package checks, and reintegrate Nalanda-specific coach reports

kalite/distributed/hbtemplates/exercise/exercise.handlebars
Hi @aronasorman. This fixed #3101- Submitting with hidden input button breaks the exercise
/review: @amodia
=> Fix the issue: Submitting with hidden input button breaks the exercise #3101

kalite/distributed/templates/distributed/base.html
Hi @MCGallaspy this fixed #3110
=> Change the ka-lite link to homepage.

kalite/distributed/static/js/distributed/exercises/views.js
Resolves #3096. I'm not writing a test for this one, because I'm taking a test hiatus while we discuss testing best practices. If that's a lame excuse, call me out and I'll write a test.
=> Remove redundant call to khan_loaded function

kalite/distributed/static/css/distributed/sidebar.css
=> Fixes the sidebar lag bug

kalite/updates/static/js/updates/update_videos.js, kalite/updates/templates/updates/update_videos.html
Hi @MCGallaspy this fixed #3122
=> Add clear message functon at the top of the video error message.

kalite/updates/templates/updates/update_languages.html, kalite/updates/templates/updates/update_software.html, kalite/updates/templates/updates/update_videos.html
Hi @MCGallaspy - this fixes #3128.
Here are some screenshots of the identified affected templates:
Update Videos
Update Languages
Update Software
/review: @djallado
=> Fix the page title issue of some templates.

kalite/distributed/templates/distributed/base_manage.html
Hi @MCGallaspy this fixes #3143
=> Change the facility tittle to manage facilities.

kalite/distributed/templates/distributed/loadtesting/load_test.html
=> Fixes video playback during loadtest

kalite/distributed/templates/distributed/loadtesting/load_test.html
=> Fixes exercise answering for nalanda-rct3

kalite/distributed/templates/distributed/loadtesting/load_test.html, kalite/distributed/urls.py, kalite/testing/loadtesting/views.py
We previously had a load testing suite using an iframe to automatically interact with the website to enable simulated user interactions on a large number of devices.
This reinstates that capability for 0.13.
=> Load testing suite

kalite/distributed/static/css/distributed/bootstrap-overrides.css
Hi @aronasorman, This fixed #3145. 
Steps to reproduce:
1. Login as teacher user.
2. Go to the manage tab.
3. It's now aligned
/review: @arceduardvincent
=> Fixed alignment of the sub nav at 480px size viewport.

kalite/distributed/static/css/distributed/khan-lite.css, kalite/distributed/static/js/distributed/distributed-server.js, kalite/distributed/static/js/distributed/exercises/views.js
The modal was added for not good design reasons.
It is poorly implemented, and gives a terrible user experience, especially on low end tablets.
(Note: I implemented it).
Hence I am just removing it, and pushing all the messages through our messaging system.
I recommend merging this instead of #3151 @jtamiace and @MCGallaspy - sorry I didn't spot you working on this earlier.
=> Kill the modal

kalite/distributed/templates/distributed/loadtesting/load_test.html, kalite/testing/loadtesting/views.py
This is just a cherry-pick of the main part of #3165.
=> Fixes and simplification to loadtesting app, for develop branch

kalite/distributed/hbtemplates/exercise/software-keyboard.handlebars, kalite/distributed/static/css/distributed/khan-lite.css, kalite/distributed/static/js/distributed/software-keyboard.js
Fixes #3153.
* Refactor software keyboard to use handlebars template
* Restyle software keyboard to properly leverage Bootstrap styling
=> Returns keypad to its former stylistic glory

kalite/distributed/static/js/distributed/exercises/views.js, kalite/distributed/static/js/distributed/software-keyboard.js
Hi @MCGallaspy  this fixes #2944
=> Software keypad only able to select one input

sphinx-docs/faq.rst, sphinx-docs/index.rst
Does what it says. FAQ from [here](https://learningequality.org/ka-lite/faq/).
=> Add FAQ to the docs.

.gitignore, kalite/distributed/templates/distributed/loadtesting/load_test.html, kalite/distributed/tests/browser_tests/quiz.py, kalite/settings.py, kalite/testing/loadtesting/views.py
Add load testing specific fixes to Nalanda Phase3
=> Nalanda rct3 to Nalanda Phase3

sphinx-docs/installguide/install_linux.rst, sphinx-docs/installguide/install_rasp_pi.rst
the file modifications actually cause trouble on Raspberry Pi
=> corrected the path and deleted unnecessary file modification in kalite Docs

kalite/coachreports/views.py, kalite/distributed/tests/browser_tests/coachreports.py
=> Fixes 3230

kalite/updates/management/commands/videodownload.py, python-packages/fle_utils/videos.py
=> Partial Fix for 2855

sphinx-docs/installguide/install_main.rst
=> Note that IE8 is not supported

kalite/control_panel/templates/control_panel/base.html
Hi @MCGallaspy this fixes #3231
=> Pagination numbers are hard to see.

kalite/distributed/templates/distributed/search_page.html
=> Set title block for search page

data/khan/topic_hierarchy.json
=> Fixed Spelling of Inequalities

sphinx-docs/installguide/install_main.rst, sphinx-docs/installguide/release_notes.rst
=> Add release notes

python-packages/securesync/devices/views.py, python-packages/securesync/tests/regression_tests.py
#3197 
Haven't tried yet. Can anyone try and confirm.
=> Fixes 3197 when central server is not reachable

sphinx-docs/installguide/release_notes.rst
two changes:
- organize release notes into platform subsections
- add subsection for RPi
=> split release notes into different subsections

kalite/distributed/static/js/distributed/exercises/views.js
Fixes #3284
Also properly process the 'multiple' answerType for Khan Exercises, then reads the solutions presented and activates the keypad if it is any kind of number.
=> Add proper support for Khan Exercise multiple input types

kalite/distributed/static/js/distributed/software-keyboard.js, kalite/version.py, python-packages/securesync/devices/models.py
Fixes #3171.
@MCGallaspy I think this is the minimal fix - but needs some testing to make sure that the keypad is still functional in IE8.
=> Hotfix for #3171 - fixes breaking error in software-keypad for IE8

kalite/coachreports/static/js/coachreports/exercise_mastery_view.js, kalite/contentload/management/commands/generate_assessment_zips.py, kalite/contentload/tests/generate_assessment_zips.py, python-packages/securesync/devices/models.py
=> Cherry pick changes from develop

kalite/i18n/__init__.py, kalite/topic_tools/__init__.py
Fixes #3311. Does what it says in the title. We now also log what languages we choose from when selecting the best language.
=> Look for khan-exercises only when the exercise isn't a perseus exercise

kalite/coachreports/api_resources.py, kalite/distributed/api_views.py, kalite/main/api_resources.py, kalite/store/models.py, kalite/student_testing/middleware.py
I removed @aronasorman's todo because he told me to. The rest I just downgraded. There's still one more, not sure how to handle it yet, so do not merge. Ultimately will address #3258.
=> Downgrade TODO-BLOCKERS to TODOS

kalite/topic_tools/__init__.py
=> Prevents ugettext returning u'None' for an empty string

kalite/facility/templates/facility/facility.html
=> UI fix for facility editing form

kalitectl.py, setup_unix.sh
Reverting parts of 5f56d2024c7784a903fdbc8e0b38c481d59dd238
=> Reopening and refixing #3272 - use different method for detecting rpi

kalite/playlist/api_resources.py, kalite/playlist/static/js/playlist/assign_playlists.js, kalite/playlist/templates/playlist/assign_playlists.html
Allows all teachers to view every grade playlist.
Now a teacher can click on Grade and collapse/expand that particular grade playlist. (Also sub types)
The code is very basic HTML and JS.
I need to improve the CSS, so need suggestions.
=> Assign Playlists are now grouped by grade and are collapsable interface

kalite/distributed/hbtemplates/user/login.handlebars
Added placeholder for password in login.handlebars
before : 
after :
=> fixes bug 3430

kalite/topic_tools/__init__.py
Fixes #3413.
* Add a check that item_data is a dict before looping over iter_items.
@jamalex
=> Checks that item_data is a dict before attempting to inspect it as one

kalite/distributed/static/css/distributed/bootstrap-overrides.css, kalite/distributed/static/css/distributed/sidebar.css, kalite/distributed/templates/distributed/homepage.html
My first PR of the quarter!
I made some minor changes to the new homepage button on smaller screens:
I also made the Bootstrap navbar toggle button (on smaller screens) feel more clicky by changing its active state color to the same color as our regular green button's active state color.
If anyone wants any minor fixes needed in the UI, let me know and I'll tack it onto this PR. I'll look through the issues meanwhile.
Loving the new Learn button image!
=> Some quality control for new homepage etc

kalite/distributed/static/js/distributed/distributed-server.js
Quick fix for login error display.
@MCGallaspy take a peek, should fix the UI issue you saw.
=> Properly partially fill functions with callback.

kalite/i18n/__init__.py
Fixes #3433 
Squashed commit of the following:
commit e9033b7bb4efa415681fa6f539f1be4ef876c9aa
Author: Benjamin Bach <benjaoming@gmail.com>
Date:   Mon Mar 30 15:23:56 2015 +0200
Wrong key lookup
commit c2c477499f5dd92df21ddc18f2f207342dea78b8
Author: Benjamin Bach <benjaoming@gmail.com>
Date:   Mon Mar 30 15:07:27 2015 +0200
Fix #3433 and only use caching of language choices when applicaple
commit 22c07cb359ac6321ea83badd427a9b2f23e77ed8
Author: Benjamin Bach <benjaoming@gmail.com>
Date:   Sun Mar 29 14:42:38 2015 +0200
learningequality/ka-lite#3433 -- now try again w/o ref'ing dead var
commit ad6eb54d0cb43bb2101915be8b720e59abfe42fb
Author: Benjamin Bach <benjaoming@gmail.com>
Date:   Sun Mar 29 14:36:17 2015 +0200
Fix learningequality/kalite#3433 by storing language selections
=> Add caching to select_best_available_language and remove over-logging

Vagrantfile, kalite/distributed/static/css/distributed/search_autocomplete.css, provision.sh
Supersedes #3304. Fixes #3303. Resolved the merge conflict, but wanted to run the tests before merging into develop.
=> Search indent fix

kalite/distributed/static/css/distributed/khan-lite.css, kalite/distributed/static/css/distributed/search_autocomplete.css, kalite/distributed/static/js/distributed/search_autocomplete.js
Changes the space between icon and the menu text.
Some Screenshots:
Fixes #3303
=> Fixes issue #3303: Fixes the indentation of text in search drop-down

kalite/main/migrations/0036_auto__del_field_attemptlog_response_count__add_field_attemptlog_assess.py, kalite/main/models.py
Merging this now, so we can launch the updated central server.
=> Restore response_count to its former glory on central-develop

kalite/main/migrations/0036_auto__del_field_attemptlog_response_count__add_field_attemptlog_assess.py, kalite/main/models.py
Undo accidental field deletion made here: https://github.com/rtibbles/ka-lite/commit/2037636f5d43c094680eff9ef6bf0aad5eefeec0#commitcomment-10592812
=> Restore response_count to its former glory.

kalite/control_panel/features/environment.py, kalite/distributed/features/environment.py, kalite/distributed/features/inline-help.feature, kalite/distributed/features/steps/exercises.py, kalite/distributed/features/steps/inline-help.py, kalite/testing/base_environment.py, kalite/testing/behave_helpers.py, kalite/testing/testrunner.py
Not yet done, but opening a PR to keep track of the changes. Reviewers, please take note of the feature spec in particular: `kalite/distributed/features/inline-help.feature`.
**What's inside so far:**
1. Behave test specs for the inline help feature
2. Adding some test helper methods
3. Re-factoring the behave environment a bit (for more general use)
3. Also fixes an issue I noticed: running the test command without any test labels wasn't running *any* behave tests, when in fact we'd like to run them *all* in that case. Fixes that in `kalite/testing/testrunner.py`
**What's next:**
1. Implement test steps.
=> Inline help features

kalite/ab_testing/data/facility_unit_mappings.json, kalite/playlist/playlists.json, kalite/student_testing/data/g4_u405_t1.json, kalite/student_testing/data/g5_u505_t1.json, kalite/student_testing/data/g6_u605_t1.json
We need student end of year test for grade 4,5,6 with output condition.
Added Unit 105 for Output Condition
Added a dummy playlist entry in playlist.json so that unit 105 can be displayed for switching.
Added student test files.
=> Added EOY Exam -- Student Testing

sphinx-docs/installguide/release_notes.rst
=> Tweak release notes

kalite/testing/mixins/browser_mixins.py
Fixes #3307. See also #3503 for a PR targeted to the `develop` branch.
=> Handle case where num_messages is 0 on 0.13.x

sphinx-docs/installguide/install_windows.rst
=> Add some styling to an image

kalite/updates/static/js/updates/update_languages.js, kalite/updates/static/js/updates/update_software.js, kalite/updates/static/js/updates/update_videos.js
=> Use more accurate error message

kalite/main/api_resources.py, kalite/main/api_urls.py
=> Added ContentRecommenderResource and urls

kalite/distributed/static/css/distributed/homepage.css, kalite/distributed/static/css/distributed/khan-lite.css, kalite/distributed/templates/distributed/homepage.html
1. Removed KA-Lite default blocks
2. More width to assigned playlist blocks, now 3 in one row, so playlist texts don't go out of blocks for long playlist names.
3. Increase the size of name of user because now login is without password and student needs to be sure they logined with correct user. Increasing size of name could help.
After Changes:
=> UI changes on Homepage 

kalite/facility/templates/facility/facility.html
Hi @aronasorman this fixes #3484
=> Facility name field validation display on top of textbox.

kalite/control_panel/features/steps/control_panel.py, kalite/distributed/features/login.feature, kalite/distributed/features/steps/login.py, kalite/distributed/static/js/distributed/user/views.js, kalite/facility/middleware.py, kalite/testing/behave_helpers.py, sphinx-docs/developer_docs/front_end_code.rst
* Test that facilities are properly hidden or shown depending whether > 1 or not
* Test error highlighting is done properly for incorrect username and password input
* Test that logging in actually results in (currently) a page reload.
=> Adds BDD tests for Modal Login

kalite/legacy/updates_settings.py
=> Fix UPDATES_DATA_PATH #3548

kalite/facility/templates/facility/facility_user.html
Hi @aronasorman this fixes #3494 and #3008
=> Facility user form validations are displayed at the top of the form fields

kalite/distributed/static/js/distributed/exercises/models.js, kalite/distributed/static/js/distributed/exercises/views.js, kalite/student_testing/api_resources.py, kalite/student_testing/api_urls.py, kalite/student_testing/templates/student_testing/test.html, kalite/student_testing/templates/student_testing/test_list.html
Fixes #2228
* Makes all views in exercise views.js use BaseView as the BaseClass.
* Abstracts redundant code from Practice, Test, and Quiz views into a Base class for all.
* Cleans up some old Nalanda code
I have manually tested this on exercises and tests. Both seem to function as intended.
=> Exercises refactor

sphinx-docs/installguide/install_windows.rst
=> Update windows installer link in docs

kalite/facility/views.py
Hi @MCGallaspy this fixes #2970
=> Successfully adding a coach takes you to the "Add a new coach" form

kalite/control_panel/templates/control_panel/partials/_students_table.html
=> No need to show student admin table header when no students exist

sphinx-docs/_static/default.css_t, sphinx-docs/_static/sidebar.js_t, sphinx-docs/conf.py, sphinx-docs/kalite-theme/layout.html, sphinx-docs/kalite-theme/theme.conf
Extends a builtin theme to include a link to the github source for the files. Had to include a some static files from the sphinx project. The branch targeted by the link is set by an option in `theme.conf` -- an ansible playbook script should probably override this option.
=> Add edit links

kalite/distributed/static/js/distributed/user/views.js
Fixes #3553
* Removes undefined _timeout_length variable from doRequest
=> Simplified Login Fix

sphinx-docs/usermanual/userman_admin.rst
Now it won't choke building latex.
=> Grab fixed userman_admin.rst from develop

kalite/i18n/management/commands/setup_in_context_translations.py
This does a few things:
1. Downloads our pseudo-language
2. Adds it to our locale dir
3. Compiles the po files into mo files.
Will only run when IN_CONTEXT_LOCALIZED = True.
=> Create a management command for setting up in-context translations mode.

kalite/distributed/static/js/distributed/exercises/views.js
Fix for https://github.com/learningequality/ka-lite/issues/3584#issuecomment-102458034
Exact same fix as the one i PR'ed for the develop branch. Streak bar is not visible to a super user
=> Fixes #3584 (again), this time correctly targeting the 0.13.x branch instead of the develop branch

kalite/distributed/hbtemplates/video/video-player.handlebars
=> Video fix , Now videos can be played directly via playlists

kalite/distributed/static/js/distributed/software-keyboard.js
#3655
Removed the setRangeText which is the part of chrome webkit.
=> Fixes 3655 , Software Keypad Issue in Android Chrome

sphinx-docs/usermanual/userman_admin.rst
@rtibbles @jamalex here are the requested pages. I tried to update the information.
=> Add docs pages

kalite/distributed/management/commands/setup.py, sphinx-docs/installguide/install_mac.rst
Fixes #3593. Adds a warning about the included version of python and a link to download 2.7.9.
=> Add python version warning

kalite/distributed/management/commands/initdconfig.py
=> Add restart and status to initd config #3654

kalite/distributed/management/commands/initdconfig.py
@aronasorman I found a problem with this, please do cherry-pick to 0.13 as well.
=> Fix erred output by manage initdconfig

kalite/facility/views.py
Hi @MCGallaspy this fixes #3682
=> Coach can access the sign up page

kalite/facility/templates/facility/facility_group.html
Hi @aronasorman this fixes #3658
=> Name field validation is align on top.

kalite/updates/api_views.py
Self-explanatory. No corresponding issue, @EdDixon identified it in hipchat.
=> Add missing import

sphinx-docs/faq.rst, sphinx-docs/usermanual/userman_admin.rst
Updated BTSync Link in FAQ and Admin User Manual
=> Updated BTSync Link

unit2.py
I don't see comments or find anything that's using it...
=> What is this file doing?

kalite/main/settings.py
not comfortable that kalite.main.settings imports kalite
=> remove unused imports

kalite/version.py, requirements.txt, setup.py
=> Setuptools distribution changes

kalite/distributed/management/commands/setup.py
=> Clarify setup question

kalite/version.py
=> Revert yml filename rename

kalite/main/tests/api_tests.py
Fixes #2152
* Reinstates ExerciseLog API test and updates for TastyPie endpoint
@aronasorman
=> Reinstates ExerciseLog API test

kalite/distributed/management/commands/kaserve.py
Just a slight rewording of the message in the `kaserve` command. Fixes #3732.
=> Clarify kaserve message

kalite/distributed/custom_context_processors.py, kalite/distributed/templates/distributed/base.html
Fixes #3744. Simpler than #3758.
=> Use settings.DEBUG ctxt variable

kalite/version.py
=> bump to 0.14.dev10

kalite/facility/tests/crypto_tests.py, kalite/testing/testrunner.py, python-packages/securesync/tests/trust_tests.py
I don't really have any words for this.
=> Don't run all our tests with DEBUG=True

sphinx-docs/faq.rst, sphinx-docs/usermanual/userman_admin.rst
Seems to be a frequent question that deserves its own entry into our frequently asked questions section.
=> add steps on how to point to your local content folder

.travis.yml, kalite/distributed/management/commands/setup.py
Maybe fixes #3764? Can't seem to replicate those test failures. Let's see how travis does.
=> Js reverse fail fix

kalite/distributed/management/commands/initdconfig.py, kalite/version.py
I've got another 0.13.x bugfix incoming. But after this, perhaps 0.13.x bugfixes should target 0.14.
=> 0.13.x into develop

kalite/control_panel/static/js/control_panel/zone_management.js, kalite/control_panel/templates/control_panel/base.html, kalite/distributed/static/js/distributed/distributed-server.js
=> Device link fix

kalite/updates/static/js/updates/update_languages.js
Fixes #3788. There are more urls in this file that need to be similary fixed; incoming fix.
=> Use js reverse urls

kalite/coachreports/hbtemplates/coach_nav/landing.handlebars, kalite/coachreports/static/css/coachreports/landing_view.css
-Cleaned up landing page CSS, 
-removed background color of the landing view, 
-made 4 circle charts more consistent, 
-improved readability of circle chart text, 
-fixed minor sizing issue of overall landing page view, 
-added -moz- support for circles (instead of squares).
=> coach landing adjustments/cleanup

kalite/distributed/static/js/distributed/topics/views.js
=> Disables back button for the sidebar when it is not visible on the screen

sphinx-docs/usermanual/userman_coach.rst
Docs failed to build for me, this was the issue.
=> sphinx is very sensitive... to tabs vs. spaces

kalite/distributed/static/css/distributed/bootstrap-overrides.css, kalite/distributed/static/css/distributed/khan-lite.css
https://github.com/learningequality/ka-lite/issues/3851
=> Fixes #3851: fixes alignment for search bar and button

kalite/updates/static/js/updates/update_languages.js
Fixes #3855. Also, there was some very saddening js in there :(
=> Create empty td for better display

kalite/topic_tools/__init__.py
=> Handle path names in cross-platform way

kalite/distributed/static/js/distributed/topics/views.js
=> Prevent too many views being removed by back button.

.travis.yml, kalitectl.py
Adds a commit on top of #3894. In addition to that PR, we update the test calls to conform to the new parser.
Fixes #3892.
=> Parse positional arguments correctly

kalite/distributed/static/js/distributed/topics/views.js
=> Trigger for title change when a content item is added.

kalite/distributed/management/commands/setup.py
Fixes #3895
Example:
```
➜  ka-lite git:(clean_pyc) ✗ bin/kalite manage setup   
_   __  ___    _     _ _        
| | / / / _ \  | |   (_) |       
| |/ / / /_\ \ | |    _| |_ ___  
|    \ |  _  | | |   | | __/ _ \ 
| |\  \| | | | | |___| | ||  __/ 
\_| \_/\_| |_/ \_____/_|\__\___| 
http://kalite.learningequality.org
version 0.14.dev11
WARNING:root:It's recommended that you install Python version 2.7.9. Your version is: sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
--------------------------------------------------------------------------------
This script will configure the database and prepare it for use.
--------------------------------------------------------------------------------
Press [enter] to continue... …
```
=> Reintroduce removal of stale *.pyc files #3895

kalite/i18n/__init__.py
=> Fixes #3919: Fix to have get_localized_exercise_dirpath return correct path

sphinx-docs/faq.rst, sphinx-docs/usermanual/userman_admin.rst
Didn't build locally, but looks OK by Github.
Btw, I checked out the 0.13.x branch to add the same info to [FAQ](https://github.com/learningequality/ka-lite/blob/0.13.x/sphinx-docs/faq.rst), but the sphinx-docs seems empty... Where do I grab the faq.rst?
=> Instructions to donwload & add assessment items post-install  - fixes #3950

kalite/version.py
For reference: https://www.python.org/dev/peps/pep-0440/
=> Use PEP440 compliant pre-release version str

sphinx-docs/screenshot.py
My pretty commands were broken. :(
=> Fix mgmt command option format after changes

kalite/distributed/hbtemplates/user/superusercreatemodal.handlebars, kalite/distributed/static/js/distributed/user/views.js, kalite/distributed/views.py
=> Superuser to admin

kalite/distributed/views.py
change initial login message to address the issue in #3874
=> change initial login message to address the issue in #3874

kalite/distributed/static/js/distributed/user/views.js, kalite/distributed/views.py
address the issues stated in these #3995   #3973
=> fix superuser modal 403, which is caused by CSRF related problem

kalite/distributed/static/js/distributed/user/views.js, kalite/distributed/views.py
also changed the first time login message
and switched superuser to admin
=> superuser modal 403 fix

python-packages/securesync/engine/utils.py
=> Remove odd parenthesis

sphinx-docs/usermanual/userman_admin.rst
Fixes #4034, problem originally described in  #4027.
=> Adding the server restart requirement after language packs download/update to Admin docs

kalitectl.py
DJANGO_SETTINGS_MODULE with it.
This will allow 'kalite start' to work with a custom settings module
specified with --settings=<module>.
@benjaoming @jamalex please take a look.
=> explicitly recognize the --settings option, and set the

python-packages/fle_utils/testing/models.py
See here: https://github.com/learningequality/ka-lite/commit/5e311dbf45934463e1885fd55527a859bd388438#commitcomment-12140755
=> Add required models.py file

kalite/distributed/hbtemplates/contentrec/content-explore.handlebars, kalite/distributed/hbtemplates/contentrec/content-nextsteps-lesson.handlebars, kalite/distributed/hbtemplates/contentrec/content-nextsteps.handlebars
Found these non-wrapped strings while fixing cards for screen readers.
=> Fixed i18 wrapping in content rec cards.

kalite/coachreports/static/js/coachreports/student_progress.js
Hi @MCGallaspy this fixes #4088
=> "Click on the LEARN button above to get started" shown to coaches when viewing student report with no data

kalite/caching/__init__.py, kalite/updates/views.py
=> Read DO_NOT_RELOAD_CONTENT_CACHE_AT_STARTUP from new location

kalite/coachreports/static/js/coachreports/tabular_reports/views.js
It seems the intent is that the constructor is passed an options object.
=> Fixup in tabular report view

kalite/coachreports/api_resources.py, kalite/coachreports/static/js/coachreports/coach_reports/views.js, kalite/control_panel/templates/control_panel/partials/_groups_table.html, kalite/facility/views.py
@jamalex I commend this to the house.
* Remove deleted method from api resource
* Properly redirect after creating a user.
* Fix javascript error on coach reports when no selected.
=> Quick bug fix coach reports

kalite/topic_tools/content_recommendation.py, kalite/topic_tools/tests/explore_tests.py, kalite/topic_tools/tests/helper_tests.py, kalite/topic_tools/tests/next_tests.py, kalite/topic_tools/tests/resume_tests.py
WIP also.
Changes so far:
* Fix up all import related errors/messiness in content_recommendation
=> More test fixing for develop

kalite/distributed/static/css/distributed/video-js-override.css, kalite/distributed/static/js/distributed/content/views.js, kalite/distributed/static/js/distributed/video/hbtemplates/video-player.handlebars, kalite/distributed/static/js/distributed/video/views.js, kalite/distributed/templates/distributed/learn.html
still need to implement Modernizer for best use/cooperation of Javascript and CSS
=> makes view for video content responsive for tablets

kalite/i18n/__init__.py
@aronasorman 's  Fix #4186: Extract the translated khan exercises into the right directory in the user's static files.
=> Merge 0.14.x to develop (fixed i18n issues)

kalite/topic_tools/__init__.py
=> Fix #4232 - generate content cache on first-run

kalite/topic_tools/__init__.py
=> cherry-pick fix for #4232

.gitignore, kalite/coachreports/features/steps/coachreports.py, kalite/distributed/features/steps/content_recommendation.py, kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-explore-topic.handlebars, kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-nextsteps-lesson.handlebars, kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-resume.handlebars
Does what it says. Also add something to .gitignore that I've been meaning to do for a while.
=> Add more explicit wait in test

docs/installguide/install_all.rst
Branch: `0.14.x`
@aronasorman. I updated the steps on mac installation in install_all.rst file.
cc/ @cpauya
=> Update docs for mac installation.

docs/installguide/install_all.rst
Fixes https://github.com/learningequality/ka-lite/issues/4268.
=> Use double backticks for code sample; single backtick inappropriate

kalite/facility/views.py
Hi! @aronasorman. This fixes the issue #4172.
I just removed the `getattr` attribute of `get_zone()` of `facility/views.py`
=> Fix the issue 4172 - Successfully add coach but it returns an error.

docs/installguide/install_all.rst
Since it doesn't work currently, let's not recommend using it.
=> Remove mention of Software Center

kalite/distributed/management/commands/setup.py, kalite/distributed/settings.py, kalite/project/settings/dev.py
* Set default to offline compression with Django Compressor.
* Run compression during setup.
* Turn offline compression off for dev.
=> Prevents django compressor happening dynamically per request

kalite/project/settings/dev.py
See here: http://django-tastypie.readthedocs.org/en/latest/settings.html#tastypie-full-debug
=> Let tastypie produce helpful debug output

kalite/main/content_rating_models.py, kalite/main/migrations/0039_auto__del_assessmentitem__add_contentrating__add_unique_contentrating_.py, kalite/main/migrations/0040_auto__del_unique_contentrating_content_kind_content_id_user__add_uniqu.py
See here: https://github.com/learningequality/ka-lite/pull/4149/files#r37342427
=> Content rating model fixup

kalite/coachreports/features/steps/coachreports.py, kalite/distributed/features/steps/superuser_create.py
Fixes #4314. No obvious goofy race condition stuff going on there, just good ol' fashioned totally sequential waiting, but not long enough.
=> Increase timeout for test

kalite/coachreports/features/steps/coachreports.py, kalite/distributed/features/steps/superuser_create.py
Reverts learningequality/ka-lite#4316
=> Revert "Increase timeout for test"

kalite/updates/static/css/updates/update_videos.less, kalite/updates/static/js/updates/bundle_modules/update_videos.js
=> Properly override fancytree LESS.

kalite/distributed/static/js/distributed/topics/views.js
=> Make sure content nodes are still highlighted as active in the sidebar

kalite/distributed/static/js/distributed/topics/views.js
=> Fix back button behaviour for sidebar.

package.json
This solves the JS file change does not get rebuild issue. 
Salute .. @rtibbles
=> make the browserify and watchify compatible again

kalite/distributed/static/css/distributed/video-js-override.css, kalite/distributed/static/js/distributed/video/views.js
Fixes https://github.com/learningequality/ka-lite/issues/4336
=> Fix video player auto-resizing, and set default height, to avoid jump

requirements_sphinx.txt
Previous PR #4322 made our docs almost RTD compatible... we just need this additional requirements file and we're good to go!
(self-merging this, it's 100% harmless)
@MCGallaspy just letting you know about this!
=> Requirements file for RTD (cannot be set per-branch)

kalite/coachreports/static/js/coachreports/coach_reports/views.js
@rtibbles I'm not sure if these strings are displayed, but I wrapped them anyway. Can you confirm if they are?
=> Wrap some JS strings in coachreports views.js.

kalite/distributed/templates/distributed/base.html
Or else the catalog files will reset to empty.
=> Don't double import en.js.

setup.py
=> fix #4382 -- we are MIT licensed

kalite/distributed/static/js/distributed/exercises/perseus-helpers.js, kalite/distributed/static/js/distributed/exercises/views.js
=> Selectively hide hint indicator if not hints available.

circle.yml, kalite/testing/base_environment.py, requirements_test.txt
Hopefully this configuration is right! Useless without adding secrets to the environment in Circle CI (which I did).
See: https://circleci.com/docs/browser-testing-with-sauce-labs
and: https://github.com/circleci/sauce-connect
=> Use saucelabs remote webdriver

kalite/updates/static/js/updates/updates/base.js
=> Imports sprintf in update app

kalite/distributed/static/css/distributed/content_recommendation.less, kalite/distributed/static/css/distributed/sidebar.css, kalite/distributed/static/css/distributed/video-js-override.less, kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-resume.handlebars, kalite/distributed/static/js/distributed/contentrec/views.js, kalite/distributed/static/js/distributed/topics/hbtemplates/sidebar.handlebars, kalite/distributed/static/js/distributed/video/hbtemplates/video-player.handlebars, kalite/distributed/static/js/distributed/video/views.js, kalite/topic_tools/content_recommendation.py
Fixes #4357, closes #4362, resolves #4369.
=> Content bug fixes

kalite/settings/base.py
Fixes #4399. Expire cookies every 30 minutes instead of "browser close".
=> expire sessions every 30 minutes.

circle.yml, kalite/testing/base_environment.py
Logs output and tries to gracefully degrade the tests if we can't connect to saucelabs. Supercedes #4428.
=> Graceful sauce failure

kalite/caching/__init__.py, kalite/contentload/management/commands/channels/import_channel.py, kalite/distributed/custom_context_processors.py, kalite/distributed/management/commands/setup.py, kalite/distributed/views.py, kalite/main/api_resources.py, kalite/main/content_rating_models.py, kalite/main/models.py, kalite/settings/base.py, kalite/student_testing/tests.py, kalite/topic_tools/__init__.py, kalite/topic_tools/settings.py, kalite/updates/api_views.py, kalite/updates/videos.py
Makes custom channels activatable in new settings paradigm.
Sets root node of custom channel import to "root".
=> Custom channel fixes

kalitectl.py
See https://github.com/learningequality/installers/issues/152
=> Disallow python 3

kalite/main/models.py, kalite/main/tests/progress_timestamp_test.py
Fixes #4273
@MCGallaspy this is simply a copypasta of your content_rating model get_uuid code.
=> Adds get_uuid to ContentLog.

kalite/updates/static/js/updates/bundle_modules/update_videos.js
fix No indicator in the topic tree for a specific video after a successful download. #4429
=> fix for #4429

kalite/distributed/static/css/distributed/khan-lite.less, kalite/distributed/static/js/distributed/exercises/hbtemplates/exercise.handlebars
https://github.com/learningequality/ka-lite/pull/4457 + my comment with title addressed.
=> Exercise overflow

kalite/distributed/static/js/distributed/exercises/hbtemplates/exercise.handlebars
Fixes #4418 as far as I think is feasible for 0.15.x
Masks the issue by wrapping exercises in the same content box as other content.
=> Fixes exercise wrapping to prevent overflow after watching a video.

kalite/coachreports/static/css/coachreports/landing_view.css, kalite/coachreports/static/js/coachreports/coach_reports/hbtemplates/landing.handlebars, kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-container.handlebars, kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-details.handlebars
=> Much responsive coach report

kalite/updates/static/js/updates/bundle_modules/update_languages.js, kalite/updates/static/js/updates/updates/base.js
=> Adds warning to restart the server on language pack download completion.

kalite/updates/static/js/updates/bundle_modules/update_videos.js
Fixes #4474.
When no videos are available for a language, show a warning to the user, rather than trigger a Javascript error.
=> Show warning when no videos available.

kalite/i18n/__init__.py, kalite/updates/static/js/updates/bundle_modules/update_languages.js
=> Don't accidentally translate "Invalidate caches" during language pack download.

kalite/main/api_resources.py
=> Fixed import error.

kalite/settings/_utils.py, kalite/settings/base.py
Fixes #4213.
Conflicts:
kalite/settings/base.py
=> Generate a secret key file, and load SECRET_KEY from said file.

docs/installguide/install_all.rst
Addresses https://github.com/learningequality/ka-lite/issues/4481 for Windows. If someone can tell me what the comparable situation is for OSX, I'll add it in!
=> Add upgrade note

docs/faq.rst
=> Add FAQ entry on installing language packs offline.

kalite/updates/management/commands/languagepackdownload.py
Fixes #4543. The distributed server doesn't know the full list of languages beforehand. That way we can add new languages on the fly from the central server without changing anything on the distributed server. We can also specify that a language be imported locally, i.e. downloaded first and then the path specified here. 
So for remote language packs, we check that we're not 404ing. If we do, error out with a better message.
=> Check the existence of the language pack before attempting to download it.

kalite/distributed/features/steps/content_rating.py, kalite/distributed/static/js/distributed/rating/views.js
Quick fix to #4545. Hope it looks safe. Can re-target to develop if desired.
@benjaoming I also take a stab at #4527. See commit message.
=> Rating delete hide

kalite/distributed/static/js/distributed/user/hbtemplates/login.handlebars, kalite/updates/management/commands/languagepackdownload.py
They weren't getting translated before.
@jinchuika.
=> i18n the placeholders in the login modal.

kalite/facility/api_resources.py
might as well get the fix in 0.15 :)
=> deprecated function name change

kalite/distributed/static/js/distributed/user/views.js
=> IE9 Compatibility fix for Nav Bar

docs/installguide/install_all.rst
@cpauya, These are the final steps of KA-Lite Monitor installation in OSX.
=> Final docs of KA-Lite Monitor installation in OSX.

kalite/updates/static/js/updates/bundle_modules/update_languages.js, kalite/updates/static/js/updates/updates/base.js
=> Use correct name for progress_log.

docs/installguide/install_all.rst, docs/usermanual/userman_admin.rst
Just typos and a minor rephrase, maybe it can be merged before the release?
=> Minor documentation corrections

kalite/distributed/static/css/distributed/bootstrap-overrides.less, kalite/distributed/templates/distributed/partials/_footer.html
=> Let everyone see the language selection #4471

kalite/updates/static/js/updates/bundle_modules/update_languages.js
Cherry picks #4587 to 0.15.x and beyond.
=> Change version comparison logic

docs/installguide/install_all.rst, docs/installguide/release_notes.rst, docs/installguide/system_requirements.rst
@cpauya, I added a note on system_requirements.rst and release_notes.rst.
=> Add a note in system_requirements.rst and release_notes.rst.

requirements.txt
=> Avoid unnecessary dependencies for old dbbackup version

kalite/control_panel/static/js/control_panel/utils/force_sync.js, kalite/distributed/static/js/distributed/base/jQuery.js, kalite/distributed/static/js/distributed/exercises/models.js, kalite/distributed/static/js/distributed/exercises/perseus-helpers.js, kalite/distributed/static/js/distributed/perseus/ke/local-only/i18n.js
Fixes #4601, resolves #4602 parts 1 and 2.
=> Fix js errors

kalite/distributed/static/css/distributed/bootstrap-overrides.less, kalite/distributed/static/css/distributed/kalite-base.less, kalite/distributed/templates/distributed/base_manage.html
=> fix facilities tab not display correctly

requirements.txt
=> Upgrade to latest dbbackup #4634

kalite/playlist/playlists.json, kalite/student_testing/data/g4_ut2.json, kalite/student_testing/data/g5_ut2.json, kalite/student_testing/data/g6_ut2.json, kalite/student_testing/data/g7_ut2.json
Added Basic skills playlist
Added Unit 2 Student Tests
=> Nalanda phase3

docs/faq.rst
=> Document KALITE_HOME

requirements_dev.txt
Adding the django_extensions module to requirements_dev.txt
=> Adding the django_extensions module to requirements_dev.txt

kalite/playlist/playlists.json
=> update playlist grade 5 playlist 13

kalite/distributed/features/steps/learn_content.py, kalite/testing/behave_helpers.py, kalite/topic_tools/content_models.py, kalite/topic_tools/models.py, kalite/topic_tools/tests/__init__.py, kalite/topic_tools/tests/annotate_tests.py, kalite/topic_tools/tests/content_models_tests.py
Starts to work on #4716. See commit message for rationale. But still, the troubled test passes even though there's clearly an alert bubble there. So something else is up.
=> Refactor behave_helper functions; add & amend test cases; fix update_item function

requirements_dev.txt
Fixes #4658. @rtibbles want to confirm the fix is ok?
=> Pin django-debug-toolbar version

kalite/distributed/features/steps/content_rating.py, kalite/distributed/features/steps/search.py, kalite/distributed/static/django_js_reverse/js/reverse.js
I don't know if this entirely fixes the problem, but at least if the document isn't fully loaded and the forementioned IndexError occurs, we will retry for 10 seconds because of `WebDriverWait`.
#4736
=> Fix for sometimes-failing test

data/version.yml, kalite/version.py
Keeping track of the changes here, though we may wish to cherry-pick specific PRs instead of merging.
=> 0.15.x into develop

kalite/distributed/management/commands/setup.py, kalite/settings/base.py
=> Prepopulated db support for all dists

kalite/distributed/features/steps/content_rating.py
Don't write the same code to rate an element twice. Just re-use.
Fixes #4716 again.
=> Make test DRYer

kalite/distributed/management/commands/retrievecontentpack.py, kalite/topic_tools/content_models.py
First pass, although there's one interesting bug on the content db side:
=> First pass on the content pack retriever command.

setup.py
=> Fix for #4752 until current tastypie master is released

python-packages/fle_utils/videos.py
=> fix broken way of detecting video download success 

setup.py
@aronasorman I merged @benjaoming [PR](https://github.com/learningequality/ka-lite/pull/4761/files) to 0.16.x branch.
=> tastypie fix merge to 0.16.x.

docs/installguide/advanced.rst
=> change PPA instructions to work for non-ubuntu debian-based dists

docs/installguide/install_all.rst
Fixes #4748. Think I should also add an FAQ question?
=> Add explicit upgrade instructions

kalite/settings/base.py
Re-opened as new PR because #4793 didn't target 0.16.x
=> Add date and time to log messages

scripts/add_systemstart_task.bat, scripts/remove_systemstart_task.bat
Reverts learningequality/ka-lite#4771
=> Revert "Finally remove batch scripts; moved to installers repo"

scripts/add_systemstart_task.bat, scripts/remove_systemstart_task.bat
Reverts learningequality/ka-lite#4799
=> Finally remove batch scripts; moved to installers repo

kalitectl.py
Candidate for backporting to 0.16.x
=> clean up kalite usage instructions

docs/installguide/install_all.rst, kalite/basetests/tests.py, kalite/distributed/management/commands/retrievecontentpack.py, kalite/distributed/static/css/distributed/content-rating.less, kalite/distributed/static/js/distributed/rating/hbtemplates/rating.handlebars, kalite/distributed/static/js/distributed/rating/hbtemplates/star.handlebars, kalite/settings/base.py, kalite/testing/base_environment.py, python-packages/fle_utils/videos.py, scripts/add_systemstart_task.bat, scripts/remove_systemstart_task.bat, setup.py
Resolves conflicts, #4808 didn't
=> 0.16.x into develop

kalite/topic_tools/content_models.py
=> Adds node sort order

kalite/control_panel/views.py
Fixes #4787. A mercifully simple fix! However, it suggests we may wish to visit pages after having generated some appropriate exercise logs and assert that no errors are found -- thoughts @rtibbles?
=> Add streak_progress to values, since we access it

Makefile, kalite/distributed/features/content_rating.feature, kalite/distributed/features/learn_content.feature, kalite/distributed/features/steps/learn_content.py, kalite/distributed/static/js/distributed/topics/models.js, kalite/distributed/static/js/distributed/topics/views.js, kalite/main/api_views.py, kalite/testing/base_environment.py, kalite/testing/testrunner.py, kalite/topic_tools/content_models.py, kalite/topic_tools/tests/__init__.py, kalite/topic_tools/tests/content_models_tests.py
Fixes #3997 -- is this the right fix @rtibbles? Any suggestions for writing a test for this? I'm thinking to write a browser test. Perhaps we can take this as an opportunity to experiment with a "stateful" sidebar for writing robust browser tests in KA Lite, kind of like what I suggested for Kolibri?
Screenshots incoming.
=> Do not show unavailable content in sidebar

kalite/coachreports/models.py, kalite/main/api_resources.py, kalite/main/models.py, kalite/shared/api_auth/auth.py, kalite/shared/decorators/auth.py, kalite/testing/asserts.py
If we forgo #4838, this at least fixes the errors I discovered while linting. Shall we merge this, or should I finish #4838? @rtibbles tagging you since you weighed in on the original as well.
=> Fix errors discovered during linting

kalite/distributed/features/steps/generic.py, kalite/distributed/features/ui_regression.feature, kalite/distributed/static/js/distributed/user/views.js
=> Don't display loginModalView when SuperUserCreateModalView is displayed

kalite/coachreports/models.py, kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-details.handlebars, kalite/coachreports/tests/coachreport_tests.py, kalite/distributed/features/steps/learn_content.py, kalite/testing/behave_helpers.py
resolves issues from https://github.com/learningequality/ka-lite/pull/4861
@benjaoming  this is still giving me a time out, i have resolved all other issues.
=> Fixes sprintf javascript error and adds new tests

kalite/distributed/management/commands/setup.py
Rewrote the way we detect Python versions and made nicer messages.
#4883
=> Fix Python version warnings

kalite/distributed/features/login.feature, kalite/facility/api_resources.py
=> remove confusing message during login

kalite/topic_tools/content_models.py
=> reinstate total_files=0

kalite/distributed/static/js/distributed/exercises/models.js, kalite/distributed/templates/distributed/base.html, kalite/main/api_urls.py, kalite/main/api_views.py, kalite/main/tests/api_tests.py
A few random issues that I noticed while addressing other issues:
* A "style" issue, with a function that name shadowed itself with three different objects sharing the same name!
* A javascript error
I thought about the best way to create a regression test for the js error -- we need a js testing framework. It's sort of unrelated, but I decided to add some tests for the otherwise untested api endpoint as a "consolation prize".
=> Miscellaneous fixes

kalite/topic_tools/annotate.py
Reinstates BACKUP_VIDEO source that was removed in #4943, also updates to fit with current logic.
=> Reinstate backup video source

kalitectl.py
Parse args with '-' in them
Fixes #4954.
=> Parse args with '-' in them

kalite/coachreports/models.py, kalite/coachreports/tests/coachreport_tests.py
pass in the language keyward argument when retrieve content nodes on progress report so that language pack setting will take effect
#4980
=> Translation on Progress Report

kalite/distributed/static/js/distributed/bundle_modules/base.js
There was a typo. This fixes it. We probably didn't notice it, as it only affects older browsers.
Check my spelling please.
Fixes #5026
=> Fixes typo.

kalite/i18n/base.py
Says what it says. Fixes my previous PR, now we extract it in the right directory for cherrypy to read.
=> Write the html exercises in a static root subdirectory.

kalite/coachreports/api_views.py, kalite/coachreports/static/js/coachreports/coach_reports/models.js, kalite/coachreports/static/js/coachreports/tabular_reports/hbtemplates/tabular-view.handlebars
Ensures the end date is set properly for the tabular report. Fix a bug where already translated titles were being translated again on the client side, causing an error.
Aimed to fix #5022 - but that is a result of generaterealdata, so don't expect it to fix it.
=> Coach report bug fixes - date ranging and translation

kalite/coachreports/api_views.py
=> Revert "Return no data if no data."

data/version.yml, docs/installguide/release_notes.rst
Added some release notes for our 0.16 release. Note: depends on #5060. Will rebase to that once merged.
=> [WIP] 0.16 Release notes

docs/faq.rst, docs/installguide/advanced.rst, docs/installguide/install_all.rst, docs/installguide/system_requirements.rst
Hope I got all of them this time!
(Dev docs need a more experienced eye...)
=> Last minute docs updates for 0.16 release

bin/kalite
Since https://github.com/learningequality/installers/issues/368 is getting fixed, we can make this slight simplification.
=> Default kalite user should now have a shell

kalite/distributed/templates/distributed/partials/_footer.html
=> Use current year instead of hard coded 2015

kalite/control_panel/api_resources.py, kalite/control_panel/static/js/control_panel/data_export/models.js, kalite/control_panel/static/js/control_panel/data_export/views.js, kalite/control_panel/templates/control_panel/data_export.html, kalite/control_panel/views.py
"Fixes" #4668 -- however I'd like to take a closer look and see if this whole page can be polished up a bit. Consider this PR a statement of intent.
=> Export defaults to all users

README.rst
=> Add IRC channel info

docs/faq.rst, docs/installguide/install_all.rst
@benjaoming  I updated the KA Lite windows application as we discussed  on this [issue](https://github.com/learningequality/ka-lite/issues/5129#issuecomment-223600114)
=> Add warning message on KA Lite windows application docs.

kalite/distributed/templates/distributed/search_page.html
Search paginator not working properly #4934
=> Remove links to search pages that don't exist

kalite/updates/views.py
I think it's about time we let go of this odd warning message as we've intended to. Only took 5 seconds to find and remove :)
#4982
=> Remove useless warning message that no longer serves a purpose #4982

docs/conf.py
=> Emergency fix for documentation, to get installer links working again

docs/installguide/release_notes.rst
Let's make it clear to everyone that we are aware of some things and working on them so they know what to expect!
**Ship early, ship often!** :)
=> [WIP] Known issues for 0.16.6

README.rst
Lots of subscribers, let's get more! :)
=> Mention mailing list in docs

README.rst, docs/installguide/release_notes.rst, kalite/version.py
A couple of docs fixes going into master so it gets built on RTD.
=> 0.16.x into master

README.rst
=> Fix wrong twitter link

docs/installguide/install_all.rst
Same text an image repeated, ran diff and everything is identical.
=> Remove duplication artifact from manual 'cherry-picking'

kalite/settings/base.py
Merged by mistake, let's get it into `0.16.x` instead.
=> Revert "allow for CONTENT_ROOT to be set with an environment variable,"

kalite/settings/base.py
*Short description*
*If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)*
*They're nice. :)*
We use this at endlessm.com to allow sharing content whilst keeping the databases separate (we merge them on launch).
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>
=> allow for CONTENT_ROOT to be set with an environment variable,

docs/index.rst
Replaced wording about FAQs and Forum with correct links to the community.learningequality.org forum.
=> Replace 'Forums' link with community link in documentation

data/version.yml, docs/installguide/release_notes.rst
=> Release notes 0167

.github/ISSUE_TEMPLATE.md
Gently point out to our users that they should go to our forums first before posting here!
=> Add community.leq blurb on issue template

kalite/distributed/static/css/distributed/bootstrap-overrides.less
Cherry-picked #5205 for 0.16.x
=> limit size of logo to fit in nav bar (to fix aflatoun's issue)

docs/installguide/advanced.rst, kalite/project/wsgi.py
Our docs had some errors regarding deployment with uwsgi or mod_wsgi which are fixed in this PR.
This does not pertain normal usage of KA Lite, it only changes a file that was broken anyways.
None
#5195
=> Update installation instructions for apache+mod_wsgi and wsgi.py file

docs/developer_docs/behave_testing.rst, kalite/testing/base_environment.py, kalite/testing/behave_helpers.py, kalite/topic_tools/content_models.py
Our project is in serious danger because we accept broken tests. Fixing some of them here.. hopefully all of them!
None
#5169
=> Fix BDD tests

docs/installguide/advanced.rst
=> Add a clause that allows execution of wsgi application in mod_wsgi

kalite/topic_tools/management/commands/annotate_content_items.py, kalite/updates/static/js/updates/bundle_modules/update_videos.js
Add user feedback to ensure user is aware of the time it can take to scan video contents.
~~Is the javascript alert problematic in any way? I'm not willing to correct it unless it's worse off than not having it :)~~
#5200
=> Assessment scan duration

docs/installguide/advanced.rst
Just remembered that the instructions regarding non-Ubuntu platforms should be updated so our users on especially RPi don't all have to google the same solutions.
#5228
=> Instructions for adding our Launchpad repo also works for Debian/Raspberry Pi

.coveralls.yml, circle.yml, requirements_test.txt
We've tried and failed numerous times.. but now that the tests work, let's try again.
=> Coverage support

.coveralls.yml, circle.yml, docs/installguide/advanced.rst, kalite/distributed/management/commands/setup.py, kalite/settings/base.py, kalite/topic_tools/content_models.py, kalite/version.py, requirements.txt, requirements_test.txt
=> 0.16.x into develop (merge conflicts)

data/version.yml, docs/installguide/release_notes.rst, kalite/distributed/management/commands/compileymltojson.py
Consolidating release notes here. Will also consolidate version.yml.
=> 0.16.7 release notes and known issues

docs/installguide/release_notes.rst
Small docs amendment, will not end up in 0.16.7 release.
=> Add a couple of known 0.16.7 issues

requirements.txt
Very well-tested already by @arceduardvincent 
Any further manual testing or consent is of course appreciated, otherwise we'll move forward with 0.16.8 very soon
#5211
=> Downgrade requests because of pyrun issue

kalite/settings/base.py
Users were confused because of the previous message.
No, just gonna merge this.
#5236
=> Make secret key message look less like an error since it isnt

kalite/distributed/features/steps/learn_content.py, kalite/distributed/features/steps/superuser_create.py
Getting very tired of unrelated test failures. Subtitle test and "red button" tests are unstable, tempting to remove them, but just trying to go with the fix for now.
None.. if it works on Circle, I will merge.
#5215
=> Add wait conditions to unstable bdd test

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
Ironically, I feel a bit like not following the PR template because it's not a normal PR :D
Please feel free to add comments and suggestions as always :)
-
=> Clean up issue guidelines

docs/installguide/system_requirements.rst
Missing info about hardware requirements had spawned some emails from people wondering which platforms they can deploy KA Lite on.
Please make suggestions as comments. Otherwise, because this is just documentation and can be changed outside of our release cycle, I'm going to merge this soon.
#5178
=> Write a more precise system requirements doc

docs/installguide/release_notes.rst
Sorted "known issues" to make sure people see the more severe ones.
None really here, it's just docs, feel welcome to make suggestions, also after I merged it.
-
=> Release notes for 0.16.8

.github/ISSUE_TEMPLATE.md
It would be nice to have better feedback from users, hopefully this can stimulate it.
=> Update issue template so people will fill in their operating system

.github/ISSUE_TEMPLATE.md
Had a github server error so my previous PR was missing a force-pushed amendment.
=> Issuetemplate

data/version.yml
Forgot this small thing for the release, but it is not known to have any serious consequences.
-
=> Bump version.yml a bit too late for the party

kalite/distributed/static/js/distributed/user/views.js
Fixes the remaining issues in #5256
#5255
#5256
=> Mrpau hotfix/5255 activating simplified login results in blank login modal

data/version.yml, docs/installguide/release_notes.rst, kalite/version.py
=> Release notes for 0.16.9

docs/installguide/release_notes.rst
Your input is in safe hands @jamalex :)
=> Clarify windows known issue [ci skip]

requirements.txt
Bump requests to latests version.
This requires installers for OSX to stop using PyRun. #5211 @mrpau-eduard @cpauya 
N/A
#5277 #5264
=> Bump requests to latest version

docs/installguide/advanced.rst, docs/installguide/system_requirements.rst
=> Cherry-pick:  Wrongly resolved merge conflict in PPA instructions correction

docs/installguide/advanced.rst, docs/installguide/system_requirements.rst
Previous instructions were duplicated and didn't work. Now tested on RPi3.
=> Wrongly resolved merge conflict in PPA instructions correction

docs/installguide/advanced.rst, docs/installguide/install_all.rst, docs/installguide/install_main.rst, docs/installguide/rpi_install.rst, docs/installguide/system_requirements.rst
Updates to @rajnikumbh 's work - will add some more links, especially to various steps for downloading videos.
We also need to write something about creating a hotspot (I've removed the out-dated old guide because of all the issues it was generating).
#5006 #4725 #5281
=> RPI tutorial updates

docs/installguide/release_notes.rst, kalite/distributed/middleware.py
Retargets #5297 for develop
Fixes #5255
=> Enable all user API patterns in LOCKDOWN mode for SIMPLIFIED_LOGIN

docs/installguide/release_notes.rst, kalite/distributed/custom_context_processors.py, kalite/settings/base.py
Can't do string replacement in settings because it doesn't know about current language.
Simple changes, if tests run, it's cool
#5055
=> Use current year in channel footer text

kalite/updates/static/js/updates/bundle_modules/update_languages.js
=> Rename 'Delete Subtitles' to simply 'Delete'

kalite/updates/static/js/updates/updates/base.js
Hi @benjaoming and @aronasorman 
This fixes the issue of the unexpected placeholder which causes the progress bar will not show.
Reference for fmt: 
- https://golang.org/pkg/fmt/ 
- http://www.diveintojavascript.com/projects/javascript-sprintf
- #5321
=> Syntax Error sprintf unexpected placeholder

docs/installguide/release_notes.rst
User advice, only targets automated deployments really.
Please make specific text change suggestions
learningequality/installers#425
=> Add section regarding changes in debian installer

docs/installguide/release_notes.rst
=> Add release notes for #5323

docs/installguide/release_notes.rst, kalite/distributed/management/commands/clearuserdata.py
Fixes #5341 
This new command is essential for writing a good new RPI deployment guide.
=> Prepare a device for cloning: Management command for clearing user data

docs/installguide/release_notes.rst, kalite/i18n/api_views.py
Adding release notes + a little note to ensure that no one think code is stale. #5342
=> Comments and release notes about #5342

circle.yml, kalite/testing/base_environment.py
Noticed that there is an enormous increase in test times after updating to Ubuntu 14.04 and newer Selenium. Not sure, could also be a temporary worse performance at SauceLabs.
Trying to see how tests perform without Sauce...
=> Experiment with Sauce disabled.

circle.yml, docs/installguide/release_notes.rst, kalite/cli.py
=> Windows logging

docs/usermanual/userman_admin.rst
=> Document RESTRICTED_TEACHER_PERMISSIONS 

docs/faq.rst
=> Remove FAQ entry #4636

docs/usermanual/cli.rst
Suggestions following a review of the documentation added in #4326.
* you might cherry-pick any changes you want, then close this pull request.
* None, apart from readability and accuracy.
* None.
=> Issue #4326 documentation review suggestions

README.rst
We should make our strategy visible to community.
I'm not sure if this is the best way, but at least it'll be better than nothing (I don't think we've really mentioned our thoughts for the future development of KA Lite anywhere in public?)
We should also encourage more community members to join the development since KA Lite really depends on community - for those who want to continue their deployments of KA Lite and cannot move to Kolibri.
=> Update docs regarding current roadmap

requirements.txt
Retargeting #5396 to 0.17.x @mrpau-richard
=> Upgrade six==1.10.0

docs/installguide/release_notes.rst
Making a note for @mrpau-eduard and @mrpau-richard ;)
#5400 #5285
=> Document well-known location for language packs 

circle.yml, kalite/distributed/features/steps/superuser_create.py, kalite/packages/bundled/fle_utils/internet/functions.py, kalite/packages/bundled/securesync/devices/views.py, kalite/updates/tests/regression_tests.py
Sorry about that @mrpau-eduard @mrpau-richard 
I was rushing along in some kind of fantasy world where we had test cases for pages like the registration page.
=> Remove debug exception expression, + test case

.github/PULL_REQUEST_TEMPLATE.md, docs/installguide/release_notes.rst, requirements.txt
Wondering if the 0.16 series is also broken. Tests so far indicate that it should be, or perhaps it's related to Python 2.7.12. We don't really know yet...
I'll test this on Ubuntu 16.04, I think that changes in `rsa` look fairly conservative and safe.
#5401 
*They're nice. :)*
=> Update rsa - fixes #5401

.github/PULL_REQUEST_TEMPLATE.md, Makefile, circle.yml, docs/installguide/release_notes.rst, kalite/distributed/features/steps/superuser_create.py, kalite/distributed/features/superuser_create.feature, kalite/distributed/middleware.py, kalite/distributed/static/js/distributed/utils/api.js, kalite/distributed/templates/distributed/500.html, kalite/distributed/templates/distributed/base.html, kalite/distributed/views.py, kalite/packages/bundled/fle_utils/django_utils/middleware.py, kalite/packages/bundled/fle_utils/internet/classes.py, kalite/packages/bundled/fle_utils/internet/functions.py, kalite/packages/bundled/securesync/devices/api_views.py, kalite/packages/bundled/securesync/devices/decorators.py, kalite/packages/bundled/securesync/devices/views.py, kalite/project/settings/dev.py, kalite/settings/base.py, kalite/updates/static/js/updates/bundle_modules/update_languages.js, kalite/updates/tests/regression_tests.py, kalite/version.py, requirements.txt
Hereby targeting `develop` for 0.18, `0.17.x` created for the upcoming release.
=> Rebase on 0.17.x and bump develop branch version to next major release 0.18 series

docs/installguide/release_notes.rst, kalite/version.py
Adds known issue regarding #5407
=> Bump version + add release notes for upcoming 0.17.1

docs/installguide/advanced.rst, docs/installguide/release_notes.rst, docs/installguide/tutorial_rpi.rst
Updates a couple of language issues, adds missing release note and IE9 known issue.
#5409
=> Documentation updates

docs/usermanual/userman_admin.rst
We have been documenting a non-existing setting, while forgetting another one.
Comments always welcomed - but will probably merge in a few hours because the changes are just about documentation.
#2462
=> User log docs

docs/installguide/uninstall.rst
=> Mrpau eduard osx uninstall

docs/installguide/release_notes.rst
Adding release notes describing most significant changes to installers.
=> Update release notes for 0.17.1 installers

docs/installguide/release_notes.rst, docs/usermanual/userman_admin.rst, kalite/cli.py, kalite/settings/base.py
* Fixes #4280 at long last
* Also fixes sphinx build error and 2 warnings
=> Document environment variables

docs/installguide/release_notes.rst, kalite/version.py, requirements.txt
Updated python-ifcfg to 0.10 and released on PyPi through https://github.com/learningequality/python-ifcfg/issues/3
Haven't tested this yet on affected systems (Ubuntu 17.04+)
Fixes #5455
=> Bump version of ifcfg

docs/installguide/release_notes.rst, kalite/distributed/static/js/distributed/base/handlebars.js, kalite/distributed/static/js/distributed/video/hbtemplates/video-player.handlebars
Captions should be enabled by default. 
#5359 
#5464
=> Captions on by default.

docs/faq.rst
Response to https://community.learningequality.org/t/python-exe-has-stopped-working/253/19
=> Add FAQ entry for Discourse

docs/installguide/release_notes.rst, kalite/cli.py, kalite/distributed/static/js/distributed/about/hbtemplates/about.handlebars, kalite/distributed/static/js/distributed/about/views.js, kalite/distributed/static/js/distributed/base/handlebars.js, kalite/distributed/static/js/distributed/bundle_modules/about.js, kalite/distributed/static/js/distributed/user/hbtemplates/navigation.handlebars, kalite/distributed/templates/distributed/about.html, kalite/distributed/tests/__init__.py, kalite/distributed/tests/about_tests.py, kalite/distributed/urls.py, kalite/distributed/views.py
A page which displays the output from `kalite diagnose`
#5452
=> About/Diagnose Page

docs/installguide/release_notes.rst
=> Consolidate release notes with changes in installers

docs/faq.rst, docs/installguide/release_notes.rst, kalite/cli.py, kalite/distributed/static/js/distributed/about/hbtemplates/about.handlebars, kalite/distributed/static/js/distributed/about/views.js, kalite/distributed/static/js/distributed/base/handlebars.js, kalite/distributed/static/js/distributed/bundle_modules/about.js, kalite/distributed/static/js/distributed/user/hbtemplates/navigation.handlebars, kalite/distributed/static/js/distributed/video/hbtemplates/video-player.handlebars, kalite/distributed/templates/distributed/about.html, kalite/distributed/tests/__init__.py, kalite/distributed/tests/about_tests.py, kalite/distributed/urls.py, kalite/distributed/views.py, requirements.txt
=> 0.17.x into develop

kalite/control_panel/tests/control_panel.py
Trying to re-introduce some test that for some reason got removed and kept in another branch.
=> Reintroduce control_panel tests

README.rst, docs/installguide/release_notes.rst
Updating changelog for 0.17.2rc2
http://keepachangelog.com/
=> Changelog 0.17.x

kalite/locale/en/LC_MESSAGES/django.po, kalite/locale/en/LC_MESSAGES/djangojs.po
Should have added this back in #5496 
Uploaded to CrowdIn now, @radinamatic
=> Newly built 0.17 translation sources

docs/installguide/release_notes.rst
=> Update release notes regarding content pack downloads

SUPPORT.rst
This file will automatically show up when trying to create a new Issue. Should prompt users to *not* create issues with support questions.
FYI @mrpau-eduard @mrpau-eugene @mrpau-richard @radinamatic
=> Add support guidelines

Makefile, docs/installguide/release_notes.rst, kalite/version.py
=> Assume npm>=5 and bump to 0.17.4dev0

kalite/testing/behave_helpers.py
Just check the HTTP response if it is 200
=> Check HTTP Response for BDD tests

docs/installguide/release_notes.rst, kalite/control_panel/templates/control_panel/base.html, kalite/control_panel/templates/control_panel/partials/_welcome_message.html, kalite/distributed/custom_context_processors.py, kalite/facility/api_resources.py, kalite/project/settings/base.py
More details on this PR #5522 
#5529
=> Display custom welcome message for admins

docs/installguide/release_notes.rst, docs/usermanual/userman_admin.rst
A little bit extra for the docs :)
=> Document KALITE_WELCOME_MESSAGE

docs/installguide/release_notes.rst, kalite/version.py
This PR will be merged and the release branch will be updated with new version numbers and tags. This means that we can track what has been released and use `git describe`. It will be used for automated Buildkite scripts in future PRs. @mrpau-eugene FYI :)
New release, manually brewing the distributions:
See release notes: http://ka-lite.readthedocs.io/en/develop/installguide/release_notes.html
Current `0.17.x` branch
- Debian/Ubuntu:
- ka-lite-bundle https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-bundle_0.17.4~b2-0ubuntu1_all.deb
- ka-lite-raspberry-pi  https://launchpad.net/~learningequality/+archive/ubuntu/ka-lite-proposed/+files/ka-lite-raspberry-pi_0.17.4~b2-0ubuntu1_all.deb
- ka-lite …
=> Bump to 0.17.4b2

.buildkite/build_whl.sh, .buildkite/build_windows_installer.sh, .buildkite/pipeline.yml, .buildkite/setup_and_upload_artifacts.sh, .buildkite/upload_artifacts.py, Dockerfile, Makefile, docs/installguide/release_notes.rst, requirements_pipeline.txt, windows_installer_docker_build/Dockerfile
routine stuff, but lets see if the bot is alive @mrpau-eugene
=> 0.17.x into develop (buildkite configuration incoming)

docs/installguide/release_notes.rst, kalite/distributed/management/commands/retrievecontentpack.py, kalite/version.py
Fix an error in subtitle unpacking, thanks @fsrechia
n/a
#5476
=> Fix error in subtitle retrievecontentpack / unpacking

docs/installguide/release_notes.rst, kalite/cli.py, kalite/distributed/views.py, kalite/packages/bundled/fle_utils/internet/functions.py, requirements.txt
Improves detection of local IP.
n/a
#5498
=> Bump ipcfg to 0.13 and use for Windows also

Makefile
Uses `kalite --version` for the filename
n/a
https://github.com/learningequality/ka-lite/issues/5558
=> Use software version and a commit hash in pex filename

docs/index.rst, docs/usermanual/userman_admin.rst
Everything in the docs was translated to French by Orange Foundation, adding it here.
n/a
n/a
=> Add translation section w/ link to French docs

docs/usermanual/userman_admin.rst
Had a [support request](https://community.learningequality.org/t/ka-lite-single-user-or-no-account-required/668), and it would be appropriate to add this setting somewhere because it's relevant.
n/a
None
=> Document SIMPLIFIED_LOGIN

docs/installguide/advanced.rst
Tested on a blank RPi 3+ w/Raspian.
=> Some precisioning to the PPA install process

docs/installguide/release_notes.rst
=> Release note about #5476

docs/installguide/release_notes.rst, kalite/version.py
=> 0.17.x into master
