python-packages/fle_utils/handlebars/loader.py

Hi @aronasorman - this fix is for #2843.
I have re-used the `fle_utils.platforms.is_windows()` function and did some minor PEP-8 fixes.

Fix to use backslash character when platform is windows.

---

kalite/distributed/hbtemplates/exercise/exercise.handlebars
kalite/distributed/static/css/distributed/khan-site.css

This targets part of issue #2312. The "show scratchpad" button is hard to find. Since the exercises widget is not loading correctly in the develop branch, I was not able to find a better spot to put the button inside the exercises widget. So I put it at the top, and it looks fine to me.
This is what my version looks like:
Here's the before:

Made 'show scratchpad' more prominent in exercises

---

kalite/updates/management/commands/videoscan.py

Fixes #2873 
Videoscan does not actually touch any files, so will not change the status of the cache anyway. It only modifies VideoObjects in the repo.
What this does mean, however, is that our availability stamping might show partially downloaded videos(?)

Prevents videoscan.py from invalidating cache

---

python-packages/securesync/__init__.py
python-packages/securesync/devices/api_views.py

Minimum to reproduce seems to be:
An entry in `securesync_device` but not `securesync_devicezone` corresponding to the client_device (on the central server)
No `securesync_zone` or `securesync_devicezone` in the client database
But so what? If the registration object exists, then we'll just get the zone there and create a new DeviceZone.
There's another redirect loop possible, see comment in api_view.py, however I've been assured
it shouldn't be reachable without some serious database deletions. Disregarding for now to avoid further time sink.

Fix redirect loop issue in one case

---

kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/static/js/distributed/exercises/models.js
kalite/distributed/static/js/distributed/exercises/views.js
kalite/distributed/static/js/distributed/software-keyboard.js

This should fix issue #2888. The 'show keypad' button now sits where it should and matches the hint and scratchpad buttons. Software keyboard has been tweaked slightly. The buttons are now `simple-button`s instead of the weird `green_button` class (which had no CSS styling anywhere LOL).
Things are now pixel-perfect!
I have also improved the coloring on the main green buttons that I edited with the recent overhaul. They match the orange buttons better.
> I had some trouble with my local clone and had to fiddle around a bit. Ignore the "changes" to `models.js` and `views.js`. Unless I'm missing something, the changes it shows for both those files match the current versions of those files in the develop branch. Nothing should change. Sorry if it causes any trouble.

Fixed issue #2888: 'Show keypad' button floating around

---

kalite/control_panel/templates/control_panel/partials/_students_table.html
kalite/facility/tests/form_tests.py

HI @aronasorman this fixed #2928 
I change the `ungrouped` context variable to `ungrouped_id`.
I attached a screenshot bellow:

change the context variable of the ungrouped to ungrouped_id.

---

kalite/coachreports/static/js/coachreports/base_d3_visualization.js
kalite/coachreports/templates/coachreports/landing_page.html
kalite/coachreports/templates/coachreports/spending_report_view.html
kalite/coachreports/templates/coachreports/tabular_view.html
kalite/coachreports/templates/coachreports/test_detail_view.html
kalite/coachreports/templates/coachreports/test_view.html
kalite/control_panel/static/js/control_panel/facility_management.js
kalite/control_panel/static/js/control_panel/zone_management.js
kalite/control_panel/templates/control_panel/facility_management.html
kalite/control_panel/templates/control_panel/partials/_coaches_table.html
kalite/control_panel/templates/control_panel/partials/_facility_table.html
kalite/control_panel/templates/control_panel/partials/_group_summary.html
kalite/control_panel/templates/control_panel/partials/_groups_table.html
kalite/control_panel/templates/control_panel/partials/_students_table.html
kalite/control_panel/templates/control_panel/zone_form.html
kalite/distributed/demo_middleware.py
kalite/distributed/templates/distributed/base_teach.html
kalite/distributed/tests/browser_tests/coachreports.py
kalite/distributed/tests/browser_tests/control_panel.py
kalite/facility/models.py
kalite/facility/templates/facility/facility_selection.html
kalite/facility/views.py
kalite/playlist/templates/playlist/assign_playlists.html
kalite/topic_tools/__init__.py

Only changed user-facing strings in wrapped in gettext calls and django templte trans blocks. So, for example, logs and tests still use the teacher/student terminology.

Replace user-facing uses of teacher/student with coach/learner

---

kalite/distributed/static/js/distributed/exercises.js
kalite/playlist/static/js/playlist/view_playlist.js
kalite/playlist/views.py

Disabling the sesssion timeout is not helping.
Students still gets logged out in between doing exercise and their progress are not saved.
A temporary fix which make sure that students will be redirected to login page if they gets logged out while doing an exercise.

Student should be redirected to login page if he/she gets looged out while doing playlist exercies

---

kalite/control_panel/templates/control_panel/partials/_groups_table.html
kalite/control_panel/templates/control_panel/partials/_students_table.html
kalite/control_panel/tests/control_panel.py

Fixes #2929 
* Adds 'autocomplete="off"' to checkbox type inputs to prevent students from being checked (but not highlighted) on page refresh.
* Regression test for bug.

Checkbox Autocomplete Off

---

kalite/coachreports/static/css/coachreports/test_view.css

Increased the height of exercise name column in exam reports

---

kalite/ka-lite.wsgi

Quick fix!
Old path layout gave import errors for middleware not prefixed with kalite. Opening up a secondary issue to propose that all middleware is correctly prefixed with `kalite.`.

Path fix for mod_wsgi

---

kalite/distributed/hbtemplates/content/content-wrapper.handlebars

Hi @aronasorman  this fixed #2962 
I add if statement on `organization context variable` to determine the variable is not empty.
I attached a screenshot.

"by:" shown on content when no author or organization designated.

---

kalite/control_panel/api_resources.py

Added Unit Variable to ExerciseLog Export

---

python-packages/fle_utils/internet/functions.py

Fixes #3023. We error out whenever we try to retrieve the external IP address of the computer, since we hardcode the OS values we're looking for. This just sets a default so we don't error out.
A proper fix for the given issue would be to make `ifcfg` work for *BSD.

Don't error out in case we don't recognize the OS

---

kalite/distributed/templates/distributed/base_teach.html

@aronasorman.
This will fix the issue: https://github.com/learningequality/ka-lite/issues/2995 - Learn tab not active when it should be.
Maybe the `KA-Lite Logo` would link to `homepage`, for now this is link to `learn`.

Hotfix for issue #2995 change learn tab url to learn instead of home.

---

kalite/distributed/static/css/distributed/sidebar.css

Hi @aronasorman this fixed #2974 
I adjust the `sidebar topic description font size to 0.9em` and  add `margin top 15px`.
i attached a screenshot.

Titles and descriptions are identically styled in sidebar

---

kalite/control_panel/templates/control_panel/partials/_device_table.html
kalite/control_panel/tests/control_panel.py

Hi @aronasorman this fix this issue #3002
Fix: If the device is registered hide the register button else show the button for unregistered device.
Reference: you can identify if the device is registered or not by device.is_registered() method. 
you can see the image below the button is not showing if the device is already registered.

Hide button when the device is registered.

---

kalite/distributed/api_views.py
kalite/distributed/tests/browser_tests/distributed.py

After `fetch`ing `window.statusModel` returns among other
things a value of `null` for `points` when logged in as a
coach. In some sort of tangled javascript fashion, this prevented
the `success` callback of the `StausModel.fetch` method from being
executed.
Solves #3000.

Set statusModel points attributes default for coaches

---

kalite/distributed/static/css/distributed/sidebar.css
kalite/topic_tools/__init__.py
kalite/updates/management/commands/videodownload.py

Fixes #2965 and fixes #2976.
* Move cache invalidation during video download to *after* all files have been attempted/handled.
* Add extra 'available' False flag addition during content_cache availability checking.
* Restyle sidebar slightly to make missing content more contrasting.

Video availability

---

setup_unix.sh

Address #2975. Just changes the command used by the setup script, the instructions in INSTALL.md are fine, and will be removed once we merge in the new docs and/or get added to package repositories.

Use kalite binary for setup_unix script instead of deprecated manage.py

---

kalite/distributed/static/js/distributed/exercises/perseus-helpers.js

Turned out to need a big of PerseusBridge magic sauce from KA.

Fixes #2977: Properly proxy hints through to get rendered, for Perseus

---

kalite/distributed/static/js/distributed/exercises/perseus-helpers.js

Solves #3006. Everything was in order, just a matter of firing off a Backbone event instead of a jQuery event.

Add proxy listener to hintUsed event

---

kalite/distributed/settings.py
kalite/distributed/urls.py
kalite/student_testing/urls.py
kalite/updates/api_urls.py

When running ./manage.py from the root of the KA Lite directory, any relative imports fail. This fixes (hopefully) all relative imports to be absolute by prepending kalite.
@MCGallaspy

Fixes (all?) relative imports to be absolute.

---

kalite/control_panel/static/css/control_panel/student-report.css

Allow word-breaking on student progress reports.

---

kalite/distributed/static/css/distributed/khan-lite.css

Hi @aronasorman and @MCGallaspy 
This fix solve this issue #3098 
when the  viewport size of >768 the points will not appear anymore see the image below that demonstrate 2 viewports 
`(Window size: 400 x 575 Viewport size: 400 x 480)` and `(Window size: 480 x 877 Viewport size: 480 x 782)`

Fix the navbar the that display points unexpected behavior

---

kalite/facility/templates/facility/facility_user.html

Hi @MCGallaspy- this fixed #3105  - Clicking edit teacher button on "users" changes the second level nav tab to "facilities," should stay on "users".
Screenshot is attached below:

Fix for 3105 Clicking edit teacher button on "users" changes the second level nav tab to "facilities," should stay on "users"

---

kalite/coachreports/hbtemplates/coach_nav/reports-nav.handlebars
kalite/coachreports/static/css/coachreports/base.css
kalite/coachreports/templates/coachreports/base.html

Hi @aronasorman and @MCGallaspy - fixed #3099 
Branch : Develop
See the attach image below demonstrating the fix. The view port of the 640 x 960 DVGA - iphone via `window resizer`  
this fix work on 480 x 800 and 320 x 480

Fix Report page misaligned when viewport width <768

---

kalite/distributed/tests/browser_tests/quiz.py
static-libraries/js/khan-lite.js

Fix 3040, Redirect to login page in case of Unauthorized

---

kalite/distributed/templates/distributed/base.html

Seems like they present information that's only applicable to
students, so I just added the student-only class to set their
display to none.
Resolves #2912.

Add student-only css class to certain dropdown menu elements

---

kalite/control_panel/views.py

Hi @MCGallaspy / @aronasorman - this fixes #3133.
I just copied the way the `base_template` context variable is added to the `context` dictionary to be used by the `control_panel/base.html` template `if not settings.CENTRAL_SERVER`.
Here's a screenshot of the facility management page for the coach user now:

Inherit from the `distributed/base_manage.html` template to fix the navigation links.

---

kalite/coachreports/static/css/coachreports/scatter_view.css

Hi @jamalex and @aronasorman. This fixed #3124 - User popup on scatterplot coach.
Here's the screenshot:

Fix for #3124 - User popup on scatterplot coach

---

kalite/distributed/static/css/distributed/khan-lite.css

Fixes #3094 without messing with any other styles.
* Prevent text selection in the work area (note, that this still allows for clicking of radio buttons when scratchpad is open, it just prevents inadvertent text selection).
@Antrikshy @MCGallaspy

Prevents user text selection on work area where exercises are rendered

---

kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/templates/distributed/base.html

Now the footer is positioned statically after the #wrapper element
If content overflows the #wrapper now instead of extending past
the footer, #wrapper will become scrollable.
Fixes #3067.

Move footer tag and set overflow for #wrapper

---

kalite/coachreports/models.py

Because of import_all_child_modules nonsense, this file is loaded and
these functions are called long before they are ever used. Why don't we just
wait until they're first called to be used? If it's just too intolerably slow
and should be called when the server starts anyway, let's do it explicitly
somewhere else so that innocently importing this file won't take forever.

runserver is blazingly fast after removing prefetched variables

---

kalite/distributed/templates/distributed/loadtesting/load_test.html
kalite/distributed/urls.py
kalite/testing/loadtesting/views.py

Cherry picked and tweaked version of #3148 for Nalanda branch.

Load testing nalanda

---

kalite/updates/management/commands/videoscan.py

Currently cache invalidation gets called repeatedly during videoscan. This prevents that, and makes it only run if the 'auto_cache' option is passed to it.
This has the result of only showing the language dub mappings once on startup, and improving start up times (following on from @MCGallaspy's lead in #3150).

No cache invalidation on videoscan

---

kalite/control_panel/templates/control_panel/account_management.html
kalite/control_panel/templates/control_panel/device_management.html
kalite/distributed/templates/admin/base.html
kalite/distributed/templates/admin/login.html
kalite/distributed/templates/distributed/base_manage.html
kalite/distributed/templates/distributed/base_teach.html
kalite/distributed/templates/distributed/exercise.html
kalite/distributed/templates/distributed/help_admin.html
kalite/distributed/templates/distributed/help_student.html
kalite/facility/templates/facility/facility.html
kalite/facility/templates/facility/facility_user.html
kalite/facility/templates/facility/login.html
kalite/updates/templates/updates/update_languages.html
kalite/updates/templates/updates/update_software.html
kalite/updates/templates/updates/update_videos.html

Hi @aronasorman and @MCGallaspy -this fixes #3075
> I remove the css classes mistakenly translated and revert it to the intended purpose. 
> I wrapped the css classes in a maker `block` that can mark this this blocks ` {% block i18n_do_not_translate %}` as not to be translated.
> As long as this `css classes` are mark within this block it will not be translated.
See the implementation and the fix here https://github.com/fle-internal/i18nize_templates/pull/3
/review: @jesumer

Remove the css classes mistakenly translated.

---

kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/templates/distributed/learn.html

Hi. @MCGallaspy. This fixed #2980 - Answer box highlighting is missing left border.
Milestone: 0.14.x
No test for now because this is a simple box-shawdow in css.
Screenshot below:

fix for #2980 - Answer box highlighting is missing left border.

---

kalite/distributed/management/commands/screenshots.py
sphinx-docs/screenshot.py
sphinx-docs/usermanual/userman_admin.rst

Because previously it couldn't. Does this by creating an associated Zone and DeviceZone for the Device, so that `Device.is_registered()` returns `True`.
Also touched up `sphinx-docs/screenshot.py` a little bit while I was in there, and added the appropriate option to a couple of screenshots.

docs - screenshot directive (and management command) can take screenshot as though the device was registered

---

kalite/coachreports/static/css/coachreports/base.css
kalite/coachreports/static/css/coachreports/tabular_view.css
kalite/coachreports/templates/coachreports/base_d3_visualization.html

Hi @MCGallaspy - this fixes #3189.
I've moved the `subtitle` css style into the `coachreports/base.css` so that all the other reports uses the same style.  See screenshot gif below.

Move `subtitle` css styles to be used by all coach reports templates instead of just the tabular report.

---

sphinx-docs/developer_docs/contributing.rst
sphinx-docs/developer_docs/documentation.rst
sphinx-docs/index.rst

Just adds a section to the docs.

Add workflow for contributing to docs

---

kalite/coachreports/templates/coachreports/base.html
kalite/coachreports/templates/coachreports/base_d3_visualization.html
kalite/coachreports/templates/coachreports/tabular_view.html
kalite/coachreports/templates/coachreports/test_detail_view.html
kalite/coachreports/templates/coachreports/timeline_view.html
kalite/control_panel/templates/control_panel/base.html
kalite/control_panel/templates/control_panel/data_export.html
kalite/control_panel/templates/control_panel/device_management.html
kalite/control_panel/templates/control_panel/facility_management.html
kalite/control_panel/templates/control_panel/zone_management.html
kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/templates/distributed/base.html
kalite/distributed/templates/distributed/base_manage.html
kalite/distributed/templates/distributed/base_teach.html
kalite/distributed/templates/distributed/coachreport.html
kalite/distributed/templates/distributed/homepage.html
kalite/distributed/templates/distributed/learn.html
kalite/distributed/templates/distributed/perseus.html
kalite/facility/templates/facility/facility.html
kalite/facility/templates/facility/facility_selection.html
kalite/facility/templates/facility/facility_user.html
kalite/playlist/templates/playlist/assign_playlists.html
kalite/student_testing/templates/student_testing/test_list.html
kalite/updates/templates/updates/update_languages.html
kalite/updates/templates/updates/update_software.html
kalite/updates/templates/updates/update_videos.html

Pushing these changes now so that it's easier to work with making the second level navigation under teach and manage responsive. 
Reference this issue:
https://github.com/learningequality/ka-lite/issues/3168#issuecomment-76888913

Fixes top level navigation bug that showed "Teach" twice, also style fixes and css cleanup

---

kalite/distributed/static/js/distributed/content/views.js
kalite/distributed/static/js/distributed/distributed-server.js
kalite/distributed/static/js/distributed/exercises/views.js
kalite/store/static/js/store/views.js

Fixes #3186 
* Track how many points have been piled onto statusModel points
* Directly increase 'points' on statusModel
This seems to be a robust way of doing it (I thought it might be problematic when switching to and from different exercises, but this way of tracking it accounts for that).

Properly update statusModel points

---

kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/templates/distributed/base.html

There was a slight css bug in the top nav that this fixes

slight changes to css styling in top nav

---

sphinx-docs/conf.py

So that if we build the docs and distribute them separately, there's a clear version.

Add timestamp to html docs output format

---

kalite/distributed/custom_context_processors.py

Hi @aronasorman / @MCGallaspy - this fixes #3238.
I just moved the for loop to translate the channel data items inside the function so that translation happens for every function call.
Here's a .gif screenshot of it:

Move the translation codes inside the `custom` function.

---

kalite/control_panel/templates/control_panel/device_management.html
kalite/control_panel/templates/control_panel/partials/_coaches_table.html
kalite/control_panel/templates/control_panel/partials/_device_table.html
kalite/control_panel/templates/control_panel/partials/_facility_table.html
kalite/control_panel/templates/control_panel/partials/_groups_table.html
kalite/control_panel/templates/control_panel/partials/_students_table.html
kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/templates/distributed/base.html
kalite/distributed/templates/distributed/partials/_footer.html

#2961 can finally be closed. This PR contains some minor changes to the CSS. The light green table headers in the Manage tab now match the light blue header and footer. Took me a while to understand that the green color came from Bootstrap's CSS.
Now, changing the light blue in one CSS file will change the light blues across the entire site. Be sure to use the `.header-footer-bg` class wherever you want a background that matches the site header and footer. That's all it adds.

Hotfix/2961 - Refactored some template classes, fixed pesky .faded-green-bg

---

kalite/contentload/management/commands/generate_assessment_zips.py
kalite/contentload/tests/generate_assessment_zips.py

Needed to resolve [an issue in the central server](https://github.com/fle-internal/ka-lite-central/issues/238).

Refactor so convert_urls function can be used elsewhere

---

kalite/distributed/templates/distributed/base.html
kalite/distributed/tests/browser_tests/distributed.py

Hi @aronasorman - this fixes #3239 to Enable the language selector for students and teachers.
See .gif how it works:

Enable the language selector for students and teachers.

---

kalite/distributed/static/js/distributed/content/views.js

#3227 
When we exit from the video page, a video log is saved and we don't save that for admin.
So, added a check using window status model, if is_admin is true then don't save.

Fixes 3227 get_uuid error on video exit

---

scripts/add_systemstart_task.bat

If the SCRIPT_DIR variable has spaces in it, then it needs to be escaped. Tested in Windows 7, scheduled task runs fine. This issue exists in 0.12 too.

Escape spaces in variable, use supported start command

---

kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/static/js/distributed/software-keyboard.js

Fixes #3283 
Adds input highlighting for Perseus exercises so that keypad users will know which input they are entering.

Input highlighting for exercises

---

kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/static/js/distributed/exercises/views.js

I have improved the readability of the progress-bar by changing the color of the score and the attempt icons.
Just some simple CSS changes.
Here is a screenshot.

Progress-bar readability improvement

---

python-packages/securesync/devices/views.py

#3197 
#3302 
We are getting a error while trying to open a url:
because we are using settings.CENTRAL_SERVER , which is a bool not a url
instead we have to use settings.CENTRAL_SERVER_HOST which points to the correct url.

Partially Fixes 3197/3302 -- After the fix Server can be registered but will fail is DEBUG is True

---

data/khan/topic_hierarchy.json

Modifies the description to NULL from space (" "->"") for Test prep in the side-bar

Fixes issue #3320: Removes the empty title being displayed with 'Test prep' in side-bar

---

scripts/add_systemstart_task.bat
scripts/remove_systemstart_task.bat

Now the script requires no input to complete and the task is owned by the appropriate user. This should be merged before a fix to the installer, so that the included submodule can be updated.

Bat script no input fix

---

kalite/distributed/static/js/distributed/exercises/views.js

Fixes #3286
Destroys any existing tooltips when an exercise_view is closed, and hence prevents phantom tooltips from floating around the screen.

Destroys any existing tooltips when exercise view is closed.

---

kalitectl.py

Because valid paths can have whitespace in them.
Don't you like paths with whitespace in them? :(
Fixes #3330. Before we merge this, can we get @EdDixon to verify that this works on Windows 7 & XP? (And Vista now too @jamalex?) Ed, just make sure your home directory has white space in it (or if it doesn't ping me and we can just add some whitespace to one of the directories in `kalitectl.py`), pull my branch and try to run the `bin/windows/kalite.bat start` command. You should no longer get a `CommandError`, but instead the server should start normally.

Don't split args on whitespace

---

kalite/contentload/management/commands/unpack_assessment_zip.py

r+w as a file mode works ok on linux but fails
on windows, but isn't a valid mode at any rate.
Probably meant to use r+.
Fixes #3347. Important so that a windows installer built with included submodule pointing to `develop` will work properly.

Use valid mode

---

kalite/distributed/tests/browser_tests/distributed.py
kalite/distributed/tests/browser_tests/quiz.py
python-packages/django_snippets/session_timeout_middleware.py
static-libraries/js/khan-lite.js

Fixes #3256
* Redirects to login page when API returns a 401/403.
* Fixes session timeout middleware to return 401 on Ajax calls.
Note: Any other reason for a session ending will not get a message.

Auth redirect

---

kalite/distributed/hbtemplates/topics/sidebar.handlebars
kalite/distributed/static/css/distributed/sidebar.css
kalite/distributed/static/js/distributed/topics/views.js

Just @Antrikshy's changes from #3343, but with one amendment since I'd like to get this PR merged today. Fixes #3245 and fixes #3223. The back button is now a bootstrap button:

Ui cleanup

---

kalite/topic_tools/__init__.py
kalite/topic_tools/tests/utils_tests.py
python-packages/accenting.py
python-packages/fle_utils/general.py

Fixes #2729. 
Before, the actual questions aren't getting translated.
This was due to an encoding issue. PO files are read as ascii, but we are passing unicode strings to `gettext`, and hence they are not getting matched. With this fix (+ a couple of others) we now have this:
To test:
1. Run `bin/kalite manage create_dummy_language_pack --traceback`
2. Run the server, and change your language to `Esperanto`.
3. Go to a perseus exercise, preferably some of the early math ones (as the later ones don't even have entries in the PO file).
Remaining issues:
- Need to get `backbone.js` strings translated.

Translate the text inside the question area

---

kalite/distributed/management/commands/setup.py
kalite/settings.py
sphinx-docs/installguide/release_notes.rst

Fixes #3275. Is the language in the docs sufficiently clear? Should we take the opportunity in the release notes to explain what exactly the assessment items are and the various options users have to download them or unpack them later with the `contentload` management commands?

Assessment zip file handling

---

kalite/distributed/demo_middleware.py
kalite/settings.py

Properly namespaces import for demo middleware.
Blacklists all non-page requests to show messages appropriately.

Fixes demo server for 0.13

---

kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/templates/distributed/base_teach.html

To address this issue:
Tested in German as well, and it works out.

Creates minimum width for the dropdown username tab

---

kalite/distributed/templates/distributed/learn.html
kalite/playlist/templates/playlist/view_playlist.html

Fixes issue #3365 .
Puts content-area above sidebar-container in html flow for better accessibility using screen readers.
The navigation links are put below the main content.
Screenshot using fangs Screen Reader:

Puts content-area above sidebar-container in html flow for accessibility improvements

---

kalite/control_panel/templates/control_panel/partials/_coaches_table.html
kalite/control_panel/templates/control_panel/partials/_groups_table.html
kalite/control_panel/templates/control_panel/partials/_students_table.html

fixes #2993 
Fixed the bug with the facilities management tab not displaying a unit of time under "login time" for each user type (coach/group/student).
Went from login time : 0 
to login time : 0 hour(s)

fixing bug 2993 'no login time units'

---

kalite/settings.py

Compress all server response data in Gzip format, which all of our targeting browsers support.
This will significantly reduce the data size to be transferred between the server and client, but since this is dynamic compression, will use some CPU cycle on the server side, and unpack Gzip will have some impact on the client side. For low power devices, we need more benchmarking to find out the balance, perhaps only apply GZip to individual views using the gzip_page() decorator.
if we have lots of binary files to serve, might need to watch out for Gzip backfire

enable Gzip system-wide

---

kalite/distributed/static/js/distributed/exercises/views.js
kalite/distributed/static/js/distributed/topics/router.js
kalite/distributed/static/js/distributed/topics/views.js

Fixes #3410 and fixes #3391, plus two issues I found while fixing #3410.
* Intercept click on 'nav_learn' button while on the learn tab and use the Backbone Router to resolve it.
* Do not pass the empty string that we get from splitting our URLs by "/" due to the trailing slash we have.
* The above then prevents too many inner views on the sidebar being closed when go to a higher level in the hierarchy.
* Clearing any existing callbacks from load of assessment item data, or loading Perseus files - this prevents Perseus trying to render into non-existent DOM elements if someone navigates away before it has finished loading.
* Change the title of the page as we navigate through the topic tree, now instead of always being "Learn | KA Lite", we will instead get the title …

Learn navigation clean up

---

kalite/coachreports/templates/coachreports/partials/_tabular_exercises_report.html
kalite/coachreports/templates/coachreports/partials/_tabular_videos_report.html

Fixes #3384 
* Add learn url before exercise or video path on table header link.

Properly forms URL for individual exercises in tabular coach report header

---

kalite/contentload/api_views.py
kalite/distributed/api_views.py
kalite/facility/api_views.py
kalite/updates/api_views.py
python-packages/fle_utils/internet/decorators.py
python-packages/securesync/devices/api_views.py
python-packages/securesync/engine/api_views.py

Adds appropriate HTTP status codes to JSON response errors.
Fixes #3177 Non-semantic HTTP Response codes
Branch: develop
Expected behavior: Provide meaningful error status codes
Steps to reproduce: User registration or login are an example. When a client device tries to register and fails to validate the chain of trust, HTTP 401 unauthorized should be returned, which is not the case.
At the moment JSON response codes are mostly 500 errors or do not contain any status message.
The changes distinguish between client and server side errors and can lead the user / developer in the right direction during the verification of returned JSON error responses.
-added missing status kwarg to JsonResponseMessageError
-added missing import of JsonResponseMessageError …

Add appropriate HTTP status codes to JSON response errors.

---

kalite/coachreports/static/js/coachreports/student_progress.js

fixes this bug -https://github.com/learningequality/ka-lite/issues/3204
When a new student clicks on the progress report section without completing any quizes or videos, currently a blank screen is shown
I have checked to see if number of collections are zero are not after successful fetching..If number is zero, then i render a message to make it look better.
if it is not zero then nothing is changed

fixes bug 3204

---

kalite/updates/views.py

Fix import statement for i18n, causing error on video management page.
Fixes #3436 Video management page does not work and returns an error 
Branch: develop
Expected behavior: Display video management page
Steps to reproduce: In the main navigation click on the manage button. After that in the sub navigation, click on the Videos button.
Actual behavior: Video management page does not work and an error message is displayed
Error
Sorry, but there was an error while trying to load the page.
(NameError: global name '_' is not defined)
A previous commit for i18n, caused a missing import statement, resulting in _ not being found.
-Changed to import ugettext_lazy as _
-Changed to use _ instead of ugettext_lazy within the @require_registration decorators
Thanks, Georgy

Use correct import statement for i18n to fix error in the video management page.

---

python-packages/securesync/templates/securesync/register_public_key_client.html

Remove this. We should not let them run this command, as we don't support it.

Don't show `manage.py update` message.

---

kalite/topic_tools/__init__.py
kalite/topic_tools/tests/utils_tests.py

Fixes https://github.com/learningequality/ka-lite/issues/3413.
Upon reading [KA's code](https://gist.github.com/aronasorman/e8f77ad7444d55c5a5e1#file-models-py-L127) we apparently don't translate a list of strings inside an assessment item properly. The symptom of this is the 500 error code which @EdDixon caught. So now, when we see a string (perhaps passed as an argument in `item_data[field] = map(smart_translate_item_data, field_data)`, we now just translate that string directly.
Now also features tests! (tm)

smart_translate_item_data: translate strings automatically

---

.travis.yml

It's already run by `kalite start` earlier in the travis file.

Fix #3438 - remove syncdb and migrate from travis.yml because it's redundant

---

data/khan/channel_data.json
kalite/distributed/static/js/distributed/exercises/views.js
kalite/distributed/static/perseus/ke/local-only/i18n.js
kalite/distributed/templates/distributed/partials/khan_dummy_channel_translation.html
kalite/topic_tools/__init__.py
kalite/topic_tools/tests/utils_tests.py

1. Match the KA channel description with that's in the po file (already fixed before, but someone edited it.)
2. i18nize the exercise title (don't mind the exercise text, this is a khan exercise).
3. i18nize the hint button.
Remaining issues:
Couldn't i18nize the "Remaining hints" text in the hint button:
Fixing this properly would require more extensive changes to the perseus codebase, related to integrating Django's and `jed.js`'s catalog file. I'm getting there, but I need more time, and I believe this shouldn't be a blocker for 0.13.

More i18n fixes

---

python-packages/securesync/devices/api_views.py
python-packages/securesync/devices/forms.py

Two small fixes in here:
- Send us a notification with diagnostic info if the "Client device did not verify" occurs again in production.
- Ensure public key submitted for registration uses "+" rather than " ", to avoid reg issue caused by parsing oddities in some sort of weird browser.

Registration tweaks (destined for central server submodule)

---

kalite/topic_tools/__init__.py

Fix notification of where to download missing content.
Fixes #3364 Inaccurate message: "This content was not found! You can download it by going to the Update page."
Branch: develop
Expected behavior: Display correct location
Steps to reproduce: Login as admin and try to access an undownloaded video.
Actual behavior: Displays old location, that does not exist anymore.
-Updated location in the message
Screenshot after update:
Thanks, Georgy

Fix notification of where to download missing content.

---

kalite/distributed/hbtemplates/content/content-wrapper.handlebars

Fix displaying empty h3 tag, when no dubs available. This causes accessibility issues.
Fixes #3337 Accessibility : Empty h3 tag over video title
Branch: develop
Expected behavior: Display h3 tag with content when dubs are available
Steps to reproduce: Play a video in Learn
Actual behavior: An empty h3 tag is displayed.
-Display the h3 tag, only when dubs are available
For screenshots, please refer to #3337
Thanks, Georgy

Fix displaying empty h3 tag, when no dubs available.

---

python-packages/securesync/devices/views.py
python-packages/securesync/tests/regression_tests.py

This avoids a "peer did not return certificate" error being thrown; urllib.urlopen is a bit flaky.

Replace urllib.urlopen with more robust requests.get method.

---

kalite/coachreports/static/css/coachreports/tabular_view.css
kalite/coachreports/templates/coachreports/tabular_view.html

Fixes #3225. No test included, it's purely display.

Modify coachreport legend to accomodate long compound words auf Deutsch

---

kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/templates/distributed/base.html
kalite/distributed/templates/distributed/base_manage.html

This pull request fixes the closed issue https://github.com/learningequality/ka-lite/issues/3168
The dropdown menu for smaller screens is now much more aesthetically pleasing. 
Also, the second search bar has been removed from distributed/base.html. @rtibbles please check to see that this hasn't adversely affected the autofill; seems to work on my end though. 
Following are screenshots of the new mobile navigation. Critiques and suggestions are very welcome!
Not logged in screen:
Unopened menu for admins/teachers:
Opened menu for admins/teachers:
Second level navigation for teachers:
Dropdown for students:

Fixes #3168: New responsive menu for mobile devices and small desktop screen views

---

kalite/distributed/management/commands/screenshots.py
kalitectl.py
sphinx-docs/README.md
sphinx-docs/conf.py
sphinx-docs/requirements.txt
sphinx-docs/screenshot.py

Cherry picking changes from #3480 onto central-develop. Will allow [#252](https://github.com/fle-internal/ka-lite-central/pull/252) on the central-server to be merged once the submodule there is updated. I am testing these changes right now, will post here when ok.

Pick docs intl

---

kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/search.css
kalite/distributed/static/css/distributed/sidebar.css
kalite/distributed/templates/distributed/search_page.html

I always thought the search page could do with a refresh, but I couldn't quite put a finger on what was wrong with it. I don't think anything was wrong with it, but I decided to make a few enhancements anyway.
1. It does not look as bland
2. Requires less scrolling (mobile optimization FTW!)
3. No more wasted whitespace
Here's what it looks like:
I'm not sure if there are any more categories than the ones pictured above, but this new layout should scale gracefully, stacking them underneath, since it uses a simple Bootstrap grid.
Suggestions for enhancements like splashes of color etc. are welcome.

3-column enhancement for search page

---

kalite/control_panel/features/steps/control_panel.py
kalite/testing/behave_helpers.py

After a behave test failed on python 2.6, I realized I was flirting with race conditions. The upshot is that if one clicks an element in selenium and causes a page load, selenium will not wait for the page to load. In general, the `WebElement.click` method will not wait for anything and so should be used with great caution. See [this blog post](http://www.obeythetestinggoat.com/how-to-get-selenium-to-wait-for-page-load-after-a-click.html) for some context.
**What's inside:**
* A helper method for the common case that you want to click an element and wait for a new page to load as a result.
* Fixed an existing test to explicitly wait for a page load.

Add method to wait for page load after a click

---

kalite/facility/models.py
python-packages/securesync/engine/models.py
python-packages/securesync/tests/crypto_tests.py

For now, this is just the regression test, as I want to see whether it fails on Travis.

Fixes #2470: "Cant register because Client device must be self-signed with a signature matching its own public key"

---

kalite/distributed/templates/distributed/homepage.html

Issue discovered in using the installers to update 0.12 to 0.13 this should resolve those issues as a temp fix however since the entire playlist is deprecated we should go back through this and remove other parts such as divs and tables for 0.14 that could right now affect release of 0.13.

Resolves depricated playlist in 0.13 release with more clean up needed

---

provision.sh

Hi @aronasorman - this fixes #3516 - Using vagrant throws some errors.
I've modified the `provision.sh` script so it automatically run `apt-get update --fix-missing` to retrieve new lists of packages.

Auto-update the lists of packages of the vagrant box when provisioning.

---

python-packages/securesync/engine/models.py
python-packages/securesync/tests/regression_tests.py

This started showing up on the central server tests, even though it was passing here (since we never do `full_clean(imported=True)` in the distributed server tests, only in the ecosystem tests on the central server). Adding the fix here, along with a test so that any regressions will be caught here directly.

Test and fix for regression error on SyncedModel.full_clean(imported=True)

---

kalite/basetests/tests.py

Hi @aronasorman - this fixes #3525 - Basetests are failing for `kalite`.
I've removed the check for `securesync` module version as discussed.
See attached screenshot for result of running `python kalite/basetests/tests.py`.

Remove the test for the `securesync` module.

---

Vagrantfile
provision.sh

Workaround for #3541. We increase the memory so we wouldn't hit the
silent MemoryError, and so people can still continue using Vagrant for development.

increase memory for vagrant virtualbox instances.

---

python-packages/securesync/devices/views.py

Session variable `"registered"` is only updated [here](https://github.com/learningequality/ka-lite/blob/0.13.x/python-packages/securesync/devices/middleware.py#L23) when it's not already defined in the session, so when it was used [here](https://github.com/learningequality/ka-lite/blob/0.13.x/kalite/distributed/views.py#L43) without logging out/in, it was using the session-cached value, and hence still showing the "Please register" message.
This PR clears the session variable whenever the reg page is viewed, which always happens post-reg, ensuring it will be cleared as needed. If another user is logged in in parallel, clicking on the "reg now" button will take them to the reg page, clear the var, and tell them it's already reg'ed.

Delete the reg state from session post-reg to reload on next pageload.

---

kalite/main/api_resources.py

Fixes #3561.
* Counterintuitively, removes 'subtitle_urls' from the list of explicit Content model fields, so that it gets parsed as an 'extra_field' and then properly transmitted to the client side.
@aronasorman This is the fix you've been looking for. It is a very minor change, that I think would be best to include in 0.13.0.
(Note: subtitles will not work with DEBUG=True as we are currently copying them directly into the static folder which is not served).

Allow subtitle_urls through the TastyPie firewall

---

kalite/updates/static/js/updates/update_languages.js

Without this, it's not possible to download updated language packs after a software version upgrade (like right now), as the `language_pack_version` is [reset after every version upgrade](https://github.com/fle-internal/ka-lite-central/blob/92d5cdafa5117679c5260dbdb1307757a2a19f2a/centralserver/i18n/management/commands/update_language_packs.py#L755).

Hotfix: Factor in software version when checking whether a langpack is new.

---

Vagrantfile

Supersedes https://github.com/learningequality/ka-lite/pull/3569. We pull in the box that the box name points to, from vagrantcloud itself.

pull in latest Vagrantfile from develop

---

kalite/distributed/hbtemplates/search/search-item.handlebars
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/static/js/distributed/exercises/views.js

* Reinstate colourisation of ticks and crosses for attempt display on exercises
* Reinstate sidebar icons on topic tree
* Properly fix search autocomplete dropdown icons to have a whitespace between them and the text
Can't take a screenshot of the autocomplete, it vanishes.

Attempt Display and Sidebar icons fixes

---

kalite/topic_tools/__init__.py

Fixes #3603. Can more be done? Reduces the number of calls to `os.path.exists` by an order of magnitude. Incoming with comparisons from line_profiler.

Server start bottleneck fix

---

kalite/playlist/static/js/playlist/view_playlist.js

We require a Playlist in which there are only a Quiz.
As Quiz are generated from the exercises of that playlist, so we need to hide those exercises.
We have an "is_essential" variable in every entity of a playlist.
{
"entity_id": "/v/place-value-3/",
"entity_kind": "Video",
"is_essential": true,
"sort_order": 2
},
So, if we make it false for the exercise of Quiz playlist, then only Quiz would be visible and exercises would be hidden.

Hiding Exercises in a playlist so that only quiz is visible

---

kalite/distributed/management/commands/points_reset.py

For new Nalanda year, all the students points have to be reset to zero.
Added points_reset management command to iterate through these logs and reset points to zero.

Added management command to reset points from exercise/video/attempt logs to zero

---

kalite/control_panel/views.py
kalite/distributed/settings.py
kalite/facility/custom_context_processors.py
kalite/version.py

Fixes #3562. So apparently upon installation, data files (things in
data/) and py files are placed in separate directories. So importing
version.yaml relative to version.py would break things upon install.
The solution is to turn VERSION_INFO into a function, and call
django.conf.settings when VERSION_INFO's value is needed. That would
avoid circular imports and allow us to use settings.CONTENT_DATA_PATH,
which is where the data files are defined.

turn VERSION_INFO into a function.

---

kalite/distributed/static/js/distributed/topics/views.js

Fixes #3221. Supercedes #3512. Adds callbacks to windows resize and scroll events to ensure the sidebar looks ok.

Sidebar render fix

---

.travis.yml
MANIFEST.in
kalite/distributed/management/commands/setup.py
kalite/settings/base.py
kalitectl.py
python-packages/fle_utils/chronograph/management/commands/cronserver.py
scripts/uninstall.sh
setup.py

This PR adds installer testing for Travis and removes the threaded execution of cronserver, being replaced by a subprocess.Popen, same on all platforms.
This in turn fixes #3616
@aronasorman do you known why the previous call for Windows contained `creationflags=CREATE_NEW_PROCESS_GROUP` ? I removed it because I couldn't find anything on Google explaining why it was needed (it doesn't work on other platforms, so I wanted something that could be similar on all).

Installer test

---

kalite/caching/__init__.py
kalite/updates/management/commands/videoscan.py
kalite/updates/tests/videoscan_tests.py

Fixes #3621. Removes duplicate definitions in `kalite.caching` and `kalite.updates`. Disconnects `pre_delete` callback for the duration of the offending section in `videoscan` command, where potentially a lot of deletions are made. Ensures that `caching.invalidate_all_caches` _is_ called once if a video is deleted. Plus a test!

Preload loop

---

kalite/distributed/static/js/distributed/exercises/views.js

Fix for https://github.com/learningequality/ka-lite/issues/3584
Adds an if conditional to prevent the ExerciseProgressView from initializing for admins.

Fixes issue #3584: hides exercise streak bar from super users

---

kalite/distributed/custom_context_processors.py
kalite/distributed/templates/distributed/help_admin.html
kalite/updates/templates/updates/update_videos.html

Fixes #3619  
Replaces the old url with new faq url. As not to hard write the url, central_server_domain is imported.

Redirect download videos help information to the new FAQ page

---

kalite/main/api_resources.py
kalite/main/management/commands/init_assessment_items.py
kalite/main/migrations/0037_auto__add_assessmentitem__add_index_attemptlog_user_exercise_id_contex.py
kalite/main/models.py
kalite/topic_tools/__init__.py

Load the assessment items into the backend instead of loading all of them into memory. Memory profiling to come.
What's inside:
* A new AssessmentItem model in `main` app (and a migration)
* Refactor tastypie resource and topic_tools functions to use the model.
* A management command (`init_assessment_items`) to bootstrap the AssessmentItem table.
How to test it out:
* Run migrations for the `main` app.
* Run the `init_assessment_items` management command. Pretty slow!
* Have fun using KA Lite.

Assessmemt item backend

---

kalite/distributed/static/css/distributed/khan-lite.css

Fixed the margins, toned back the has-error state and toned up the focus one as a bonus.
SR popover problems are another can of worms. Turns out NVDA isn't reading them properly, but JAWS is, so it's more of the AT provider issue than markup itself. Have an inkling that 'tooltip' instead of 'popover' might have a better acceptance, but will have to test further. 
Should fix the #3558 also.

Finishing what was started in #3459

---

kalite/coachreports/views.py
kalite/playlist/models.py

Fixed video slug to video id lookup so that video coach reports works.
Changed sorting order of students, first_name, last_name.
Improved exercise mastery coach reports to ignore duplicate and display all grade playlists.

Enabling coach reports for videos by fixing slug lookup

---

circle.yml
kalitectl.py
requirements_dev.txt
sphinx-docs/developer_docs/index.rst
sphinx-docs/developer_docs/profiling.rst

The goal of this patch is to introduce lightweight memory profiling that can be run in the build server/in the background. The data will be used to track how our memory usage grows over time as measured by the benchmarking suite. This isn't designed to help pinpoint where memory leaks happen, see `guppy-heapy` and `memory_profiler` for that.
Oh, and with this change I also introduce a more substantial CircleCI config file.

Buildserver-oriented memory profiling

---

kalite/distributed/static/js/distributed/topics/views.js

Ensures the sidebar's size is calculated correctly even if the user doesn't resize or scroll the window.

Sidebar initial size fix

---

.travis.yml
kalite/control_panel/static/js/control_panel/facility_management.js
kalite/distributed/management/commands/kaserve.py
kalite/distributed/static/js/distributed/distributed-server.js
kalite/distributed/static/js/distributed/search/views.js
kalite/distributed/static/js/distributed/session/models.js
kalite/distributed/templates/distributed/base.html
kalite/distributed/tests/javascript_unit_tests/session_model_tests.js
kalite/distributed/urls.py
kalite/settings/base.py
kalite/updates/static/js/updates/update_languages.js
kalite/updates/static/js/updates/update_videos.js
kalite/updates/templates/updates/update_languages.html
kalite/updates/templates/updates/update_videos.html
requirements.txt

Adds Django JS Reverse to expose a Urls object in client side code for access to Django URLs in the browser.
* Adds django_js_reverse app
* Ports as many Javascript referenced URLs as possible over to the Urls object.
Note: Tastypie messes it all up. Again.

Django js reverse

---

kalite/distributed/management/commands/initdconfig.py
scripts/runatboot.sh
sphinx-docs/installguide/install_linux.rst

Fixes #3654. In particular, `initdconfig` script template had what could be an error (the shebang was not the first character, but actually a newline character), `runatboot.sh` definitely had an error (could produce undesirable output, since it was using a deprecated command), and the documentation was amended to clarify the options.

Install guide fix

---

kalite/distributed/management/commands/compileymltojson.py
kalite/shared/utils.py
kalite/version.py

Fixes #3562. Summary of `open_json_or_yml` algorithm:
Attempt to load a json version of the file first, by changing the file extension to `json`. If it's not present, load the `yml` version by changing the extension to `yml`.
~~todo: a management command that "compiles" all the yaml files into json.~~
You can compile all relevant yml files into json by running `kalite manage compileymltojson`. For now it just compiles `version.yml`.

Load either the json or yml version file.

---

python-packages/fle_utils/settingshelper.py

It's not cool to have a function that looks at everything in INSTALLED_APPS and just imports `settings` from it.

stop trying to import settings from everything in INSTALLED_APPS

---

kalite/coachreports/templates/coachreports/base.html
kalite/coachreports/templates/coachreports/base_d3_visualization.html
kalite/coachreports/templates/coachreports/scatter_view.html
kalite/coachreports/templates/coachreports/student_view.html
kalite/control_panel/templates/control_panel/base.html
kalite/distributed/hbtemplates/user/login.handlebars
kalite/distributed/hbtemplates/user/navigation.handlebars
kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/static/js/distributed/distributed-server.js
kalite/distributed/static/js/distributed/exercises/views.js
kalite/distributed/static/js/distributed/navigation/views.js
kalite/distributed/static/js/distributed/user/views.js
kalite/distributed/templates/admin/base.html
kalite/distributed/templates/admin/login.html
kalite/distributed/templates/distributed/base.html
kalite/distributed/templates/distributed/base_teach.html
kalite/distributed/templates/distributed/homepage.html
kalite/distributed/templates/distributed/learn.html
kalite/facility/api_resources.py
kalite/facility/templates/facility/facility.html
kalite/facility/templates/facility/facility_selection.html
kalite/facility/templates/facility/facility_user.html
kalite/playlist/templates/playlist/assign_playlists.html
kalite/student_testing/templates/student_testing/current_unit.html
kalite/student_testing/templates/student_testing/test_list.html
kalite/updates/templates/updates/base.html
kalite/updates/templates/updates/update_languages.html
kalite/updates/templates/updates/update_software.html
kalite/updates/templates/updates/update_videos.html

Looks the same as the current one, so no screenshots necessary.
The view for the nav bar listens to the statusModel for they type of user (student, teacher, guest, etc.) and displays the appropriate tabs with appropriate activation according to which page the user is on. 
URL's are currently hardcoded.
Will be adding a few commits shortly for cleaning up the no-longer-needed django blocks on templates that used to activate the tabs, but just wanted the put this PR now since the code is functional.

Created backbone view for the navigation bar

---

kalite/distributed/templates/distributed/learn.html

Moves MathJax loading outside of DjangoCompressed block to prevent 404 errors when loading files that are not present and MathJax does not need

---

sphinx-docs/usermanual/userman_learner.rst

Fixes #3665, almost. What should be done about exercise screenshots in the docs? One would need to ensure the machine building the docs has the exercise referenced by the screenshot directive, otherwise it will fail to build the docs. @aronasorman ?

Correct explanation in learner docs

---

kalite/i18n/__init__.py
kalite/playlist/models.py
kalite/topic_tools/__init__.py
kalite/updates/api_views.py
python-packages/fle_utils/internet/webcache.py
python-packages/securesync/engine/models.py

This causes a circular import where a settings module imports this
module at the toplevel. Doing that import forces django to load the
LazySettings attributes, which causes an import of all settings modules,
which causes this module to get loaded, which forces django to load the
LazySettings attributes...
Loading settings at actual function call avoids this circular import.

don't load the settings during function eval.

---

kalite/distributed/features/login.feature
kalite/distributed/features/steps/login.py
kalite/distributed/settings.py
kalite/distributed/static/js/distributed/distributed-server.js
kalite/distributed/static/js/distributed/user/views.js
kalite/distributed/views.py
kalite/testing/testrunner.py

Fixes #3538
* Use next GET param to determine redirect location.
* If no next GET param, then use any supplied redirect from the API response
* Alter the 403 handler view to add login=true to the GET param to trigger the modal.

Fixes redirect for modal login.

---

kalite/contentload/management/commands/channels/base.py

Fixes #3320
* Adds .strip() to description if it exists on a node

Contentload now strips descriptions to prevent whitespace only descriptions

---

kalite/distributed/hbtemplates/search/search-item.handlebars
kalite/distributed/static/css/distributed/search_autocomplete.css
kalite/distributed/static/js/distributed/search/views.js

Fixes #3578. I couldn't figure out what happened to the `0.13.x` styling, so I just tried my own. Perhaps the only contentious thing here is that search result elements have a fixed height; overflow is hidden, instead of increasing the result item's height.
Also fixes #3349 and #3345.
Screenshot:

Searchbar fixes

---

kalite/distributed/static/js/distributed/user/views.js

Fixes https://github.com/learningequality/ka-lite/issues/3742
All of the tabs still toggle correctly and the learn tab no longer flickers on a video, but I'm not too sure if this is the best approach.

Fixes #3742: flickering learn tab

---

kalite/version.py
setup.cfg
setup.py

Apparently with the latest version of pip, instead of calling "setup.py install", it tries "setup.py bdist_wheel" first, which will create a broken .whl package. By raising an exception, pip falls back to "setup.py install".

Disable wheels (because of pip 7.0)

---

kalite/coachreports/models.py

Fixes #3743 - except it doesn't. But fixes the only possible places I can find in the code that might be associated with this.
* Fully deprecates Playlists in student progress reports.
* Eliminates reference to topic tree node children as anything but ids.
@MCGallaspy

Eliminates reference to topic tree node children as anything but ids

---

python-packages/fle_utils/django_utils/command.py

Workaround for #3704. Running videodownload on OS X results in a strange quitting behaviour by the python process if run as a thread. If run as a process, it should work fine, albeit it might take longer. Good enough for now.

Spawn processes by default for OS X whenever we call call_command_async

---

kalite/distributed/hbtemplates/user/navigation.handlebars

Fixes https://github.com/learningequality/ka-lite/issues/3840
My Progress now links to the student progress report page

Fix for 3840: adds url to my progress page

---

kalite/distributed/templates/distributed/search_page.html
kalite/distributed/views.py

Fixes #3244
* Use generator expressions to produce search results
* Paginate search results by 'page' GET parameter
* Add page indicator and 'previous' and 'next' navigation.
Note: This has room for improvement, but this is for a first pass to fix up for 0.14.

Paginate Search

---

kalite/distributed/management/commands/gitmigrate.py
kalite/distributed/management/commands/setup.py
sphinx-docs/installguide/release_notes.rst

This fixes the first part of #3335. Needs specific changes in the installers to leverage this new option on setup.
* Adds a management command to migrate from a previous installation somewhere else in the file system (presumably git)
* Copies database file from old install to new
* Copies content files from old install to new
* Adds option to setup management command to pass in a path to migrate from
* Calls gitmigrate command before setting up the database to avoid creating a database and then destroying it
@aronasorman Take a peek.

Git install migrate

---

kalite/coachreports/api_views.py
kalite/coachreports/features/coachreports.feature
kalite/coachreports/features/steps/coachreports.py
kalite/coachreports/hbtemplates/coach_nav/detailspanel.handlebars
kalite/coachreports/hbtemplates/coach_nav/detailspanelbody.handlebars
kalite/coachreports/hbtemplates/coach_nav/landing.handlebars
kalite/coachreports/management/commands/generaterealdata.py
kalite/coachreports/static/css/coachreports/base.css
kalite/coachreports/static/css/coachreports/events_view.css
kalite/coachreports/static/css/coachreports/tabular_view.css
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/distributed/static/css/distributed/bootstrap-overrides.css
kalite/distributed/static/css/distributed/khan-lite.css
kalite/distributed/templates/distributed/base_manage.html
python-packages/fle_utils/handlebars/static/js/handlebars/handlebars-helpers.js
sphinx-docs/developer_docs/index.rst
sphinx-docs/developer_docs/utility.rst

Fixes #3837, closes #3839, resolves #3845, fixes #3846, closes #3850, resolves #3853, fixes #3854, closes #3858, resolves #3880, and fixes #3882.
* Enhances latest activity timestamp logging in generaterealdata
* Stops two summary data API calls being made
* Fixes bug with summary data aggregation so that data is actually aggregated.
* Positions detail panel view under cell that was clicked.
* Prevents getattr calls without default values.
* Filters teachers out of coach reports.
* Pushes pagination outside of content in details panel.
* Properly implements pagination on the details panel view.
* Implements a first pass attempt at displaying Perseus answers in the details panel view.
* Hides the 'Show Tabular Report' button when no data is available.
* Shows progress …

Coach report bug fixes

---

kalite/facility/api_resources.py
kalite/facility/tests/__init__.py
kalite/facility/tests/api_resource_tests.py

Fixes #3857 and adds a test for it. Supersedes #3879, since I rewrote history. Warning: looking at that PR now may cause headaches.

Coach login redirects to coach reports

---

kalite/django_cherrypy_wsgiserver/cherrypyserver.py
sphinx-docs/developer_docs/index.rst
sphinx-docs/developer_docs/logging.rst

Here's some logging. It's opt-in, since it doesn't use any rotation. A simpler solution than #3800 for now. In general it's possible to use fancy logfiles with rotation using the `logging` module, but since we import that from settings I'm not touching it right now.

Some logging is better than none

---

kalite/distributed/static/js/distributed/exercises/models.js

Not sure how long this has been extant, but it's going to give us some awfully crappy data.
Fixes #3885

Fixes #3885. Don't reference object directly in Backbone Model defaults, as object will be shared across instances.

---

kalite/topic_tools/__init__.py
kalite/updates/__init__.py
kalite/updates/management/commands/videoscan.py

Fixes #2976, and attempts to resolve #3835, and perhaps closes #3743 permanently.
* Only assign topic tree to global variable after the flat topic tree has been generated.
* Removes signals that trigger cache invalidation after modification of VideoFile model.

Video download and topic tree fixes

---

data/khan/make_unique_slugs.py

Fixes #3807, but creates a TODO. Inside:
* a little script to fix up "topics.json", ensuring that siblings in the topic tree have unique slugs/paths
* topics.json thusly fixed-up

Quick fix to #3807 by ensuring uniqueness constraint

---

python-packages/fle_utils/django_utils/command.py

Hi @aronasorman this fixes #3704 
Downloading videos on osx isntaller worked properly after I commented `line 141` at `ka-lite/python-packages/fle_utils/django_utils/command.py`.
Refer to the screenshots below.  
I also observed that progress bar is not showing during downloading videos. I think this is another issue.

Cannot connect to server for downloading video files from current development installs

---

kalite/distributed/management/commands/test.py
kalite/testing/testrunner.py

@66eli77 @rtibbles 
Overrides the builtin `test` management command, just to add an extra option, `--bdd-only` that only runs behave tests. You can specify an app label to only run tests in that app, so 
```sh
bin/kalite manage test distributed --bdd-only
```
only runs the behave tests in the distributed app. Depends on the implementation details of `DjangoTestSuiteRunner`, and so may not be safe on different versions of Django unfortunately.

Add option to only run behave tests

---

kalitectl.py
sphinx-docs/developer_docs/logging.rst

Final amendment to #3601
@MCGallaspy I replaced NAIVE_LOGGING with a default log file that's just truncated every time you run `kalite start`. I think it matches the needs better on a production system.
I don't mind that it's there by default, because you'd have to have an incredible uptime and usage to make a significant impact on file size. Everything else will memory leak and die before this is an issue, and restarting kalite always truncates the log file.
In case there's a failure, normal users can refer to the log. I could add more interesting features that kept latest lines from a previous log, but on the other hand, I feel like we need to get a proper logging mechanism and not spend more time on this :)

Simplify logging and docs, and command line instructions

---

kalitectl.py

The regex isn't super perfect, but this is not mission critical.. I don't see it matching and failing with acceptable patterns.
#3939

Fail when illegal option pattern is used #3939

---

kalite/facility/api_resources.py
kalite/settings/base.py

I just discovered the following situation:
```sh
> kalite manage shell
>>> from kalite import settings
>>> settings._DOCS_EXIST
AttributeError: 'module' object has no attribute '_DOCS_EXIST'
```
This seems to resolve it. Necessary to make sure statically served docs have an entry in the navbar.

Ditch the underscore for module attribute

---

bin/windows/kalite.bat

In the future, in windows, we may wish to e.g. get the version number of a previous install with the command "kalite.bat --version 1> version.txt". Without `@echo off`, this will also print the contents of kalite.bat.

@echo off to make output redirection nicer

---

kalitectl.py

To ensure port is freed before it tries to grab it again, as described here: https://github.com/learningequality/ka-lite/pull/4014#issuecomment-118728304

Add a short delay between stopping and starting in restart command.

---

kalitectl.py

command line failure on --option=value pairs **without** = (e.g. "--long-option value") should understand --long-option containing a dash
#4026

No failure on "--long-option value" when dash in long option

---

kalite/distributed/management/commands/gitmigrate.py
kalite/distributed/management/commands/setup.py
kalitectl.py
sphinx-docs/installguide/release_notes.rst

The command was trying to put stuff in `KALITE_DIR` instead of `DEFAULT_DATABASE_PATH` and `CONTENT_ROOT`, which prevented it from working at all.
The improvements here also present more options to the user, allowing them to select an alternate location to load videos from, see how big the files there are, and choose whether to copy or move. More granular progress is then displayed during the transfer.

Updated gitmigrate command to a) work, b) be friendlier. Also, fixed docopt option parsing.

---

kalite/settings/base.py

This change makes learningequality/installers#73 work without issues. Otherwise changes will need to be made in that PR in order to migrate old database files (`data.sqlite`) to a new name (`default.sqlite`).

Use consistent database name

---

kalite/coachreports/api_views.py
kalite/coachreports/hbtemplates/tabular_reports/tabular-view-row.handlebars
kalite/coachreports/management/commands/generaterealdata.py
kalite/coachreports/static/css/coachreports/tabular_view.css
kalite/coachreports/static/js/coachreports/coach_reports/models.js
kalite/coachreports/static/js/coachreports/coach_reports/router.js
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/coachreports/templates/coachreports/coach.html
kalite/coachreports/views.py
kalite/distributed/static/js/distributed/content/views.js
kalite/distributed/static/js/distributed/contentrec/views.js
kalite/distributed/static/js/distributed/distributed-server.js
kalite/distributed/static/js/distributed/exercises/views.js
kalite/facility/api_resources.py

Fixes #3977, #3978, #3980, #3981, #3982, #3983, #3985, #3986, #3987, #3988, #3989, #4017, #4019.
* Make both client and server insensitive to timezones in datetime calculations.
* Adds loading indicator to tabular report button.
* Fixes display of student name cells in tabular report.
* Show currently clicked cell for detail view on tabular report as selected.
* Prevents detail panel contents from overflowing tab pane.
* Adds css hover to tabular report cells to indicate clickability.
* Automatically redirect coaches to their own facility.
* Don't display streak messages to admins and coaches.
* Adds UserLogs back into generaterealdata.
* Corrects total time logged to report hours, not seconds.
* Reinstate appropriate change functionality for facility and group …

Front end bug fixes

---

kalitectl.py

It is problematic that "kalite stop" exits with a non-zero code just because it was already stopped. That should be okay, otherwise other scripts that call "kalite stop" will think it failed to stop!

Return code 0 on "kalite stop" when already stopped

---

kalitectl.py

Also fail on broken -x 123, should be -x123 for now

---

kalite/topic_tools/__init__.py

This blew up the facility management page on the central server, since it tried to load the assessment item DB in order to stamp availability when retrieving the topic tree (not sure why the facility management page needs the topic tree, but I didn't dig too deep for now).

Do not attempt to load assessment items on the central server.

---

kalite/settings/base.py
python-packages/fle_utils/django_utils/command.py
python-packages/securesync/management/commands/register.py

This doesn't really affect anything on the distributed server (other than adding `fle_utils.testing` to `INSTALLED_APPS` to support the `runcode` command), but is needed to get the submodule stuff on ka-lite-central working.

Tweaks needed in order to work with central server

---

kalite/__init__.py
kalite/settings/base.py

On windows, since the windows installer does not use setup tools, we must make the setting `USER_DATA_ROOT` be configurable. Also, since the docs directory was renamed (sphinx-docs to docs) let that be reflected in the static docs serving code.

Windows root data path workaround

---

kalite/distributed/management/commands/setup.py

Fixes:
- Link to KA Lite website was out of date
- Python version was being display in non-human-readable form
- There was no way to skip assessment item stuff (e.g. database migrations) on central server

Update setup command with correct link and better version display, and add "--no-assessment-items" option

---

kalite/caching/__init__.py
kalite/updates/management/commands/videodownload.py
kalite/updates/views.py

To improve performance on the Raspberry Pi, don't invalidate the cache at download finish, just remove the disk based cache to force a refresh of the content cache at startup.

Don't invalidate caches except at boot when using disk based caches

---

bin/kalite
kalitectl.py
python-packages/fle_utils/chronograph/management/commands/cronserver_blocking.py

Instead of leaving an eternally blocking thread behind because cherrypy calls its join(), we use setDaemon and wait for it after asking it to shutdown

Fix --foreground process leak

---

MANIFEST.in.dist
setup.py

Add a new exclude rule to the auto-generated MANIFEST.in that is triggered AFTER the include rule.

Fixes #4131

---

.gitignore
kalite/topic_tools/__init__.py
python-packages/fle_utils/general.py

Write cache data in user space #4109

---

kalite/coachreports/api_resources.py
kalite/coachreports/api_views.py
kalite/coachreports/features/steps/coachreports.py
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/control_panel/api_resources.py
kalite/distributed/static/js/distributed/content/views.js
kalite/distributed/static/js/distributed/user/views.js
kalite/shared/api_auth/auth.py

This PR makes changes to the coach reports that leave their functionality unchanged on the distributed server, but make them compatible with the Central Server code.
* Do not create dummy Django models for Groups 'All' and 'Ungrouped', instead dynamically generate those options on the client side.
* Use CENTRAL_SERVER aware permissions (borrowing from existing CENTRAL_SERVER compatible permissions code) for student progress reports.

Central coach reports

---

docs/developer_docs/documentation.rst
docs/developer_docs/environment.rst
docs/developer_docs/index.rst
docs/faq.rst
docs/requirements.txt
docs/usermanual/userman_admin.rst

**Work in progress**
* Updates for #4106 and move CONTENT_ROOT note to correct location
* Removed outdated, mis-placed upgrade instructions, we're better off with release notes for people who pay attention to updates than instructing someone about how to upgrade in our offline docs.
* Development environment instructions no longer mis-placed
* Info about building the documentation updated

Docs tweaks

---

kalite/__init__.py
kalitectl.py

Example:
```
✗ bin/kalite diagnose
KA Lite diagnostics
Calculating diagnostics...
KA LITE VERSION:      0.14.0
PYTHON:               2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
PLATFORM:             Linux
hostname
3.16.0-38-generic
#52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015
x86_64
SERVER ADDRESS:       http://192.168.40.148:8008/
SERVER ADDRESS:       http://127.0.0.1:8008/
SERVER STATUS:        OK, running
INSTALLED IN:         code/ka-lite/kalite
CONTENT ROOT:         code/ka-lite/content
CONTENT SIZE:         3.0 MB
USER DATABASE:        code/ka-lite/kalite/database/data.sqlite
ASSESSMENT DATABASE:  code/ka-lite/content/assessmentitems.sqlite
DEVICE NAME:          hostname
DEVICE UUID:          60d28ba6c1d9593b8f9c6b61d1ae7935
DEVICE REGISTERED:    True
DEVICE SYNCED: …
```

New diagnose command diagnoses system (not so robust)

---

package.json

`4.12` dropped the support for **srt** files, in favor of implementing **vtt**. `4.11` version is the most recent (Jan. 2015) that supports **srt**.

Changed the VideoJS version number in the package.json to 4.11

---

kalite/distributed/static/js/distributed/bundle_modules/register_public_key_client.js
python-packages/securesync/templates/securesync/register_public_key_client.html

The js module has the same name. Lives in the `distributed` app. Fixes #4156.

Create js bundle for register_public_key_client.html

---

kalite/testing/management/commands/readmodel.py
python-packages/securesync/__init__.py

- Use kalite.version.VERSION for securesync; needed for minversion checks
- Properly handle dates when serializing models to JSON in readmodels

Securesync fixes

---

kalite/coachreports/templates/coachreports/student_view.html

Should fix #3927. 
It doesn't seem to break anything on my end, but I'll test some more (and do a rebase :P ) before merging.

Deleting "← Back to Facilities" link on student Progress report page

---

kalite/topic_tools/__init__.py

Makes sure that exercises are searched on the `localized_exercise_dirpath`.

Fix #4186: Make sure stamping uses the right dir.

---

kalite/coachreports/static/css/coachreports/base.css
kalite/control_panel/templates/control_panel/partials/_groups_table.html
python-packages/fle_utils/handlebars/static/js/handlebars/handlebars-helpers.js

@jamalex Fixes the outstanding issues for styling and URL generation.

Zone space coach reports

---

kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-container.handlebars
kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-details.handlebars
kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/student-progress-container.handlebars

This is technically finished, and I used `generaterealdata` function to test it with the learners from Wilson Elementary... :)
I can say I feel satisified, so, **review and merge away**! :)
This is technically finished, but I'd like to test it more thoroughly with more content (waiting for the #4135 & #4157 ). So, **don't merge yet**! :)
Still **WIP**, but it's a lot of fun though, like trying to fit puzzle pieces... :)

Optimizing Student Progress Report page for screen readers

---

kalite/main/migrations/0039_log_timestamps.py
kalite/main/migrations/0040_auto__chg_field_videolog_video_id__chg_field_attemptlog_exercise_id__c.py
kalite/main/models.py

* Data migration for latest_activity_timestamp to put in values where available
* Increases size of 'id' fields on log models to 200.

Log data migration

---

docs/README.md
docs/installguide/install_all.rst

Tried to build docs locally, but was getting `'sphinx-build' command was not found` errors with sphinx installed via pip (Ubuntu 15.04). Only after I checked the official docs and installed with `apt-get install python-sphinx` did I manage to build. Added the command to `README.md`, fixed a broken `:ref:` link and a couple of missing line breaks in the `install_all.rst` file.

Correct docs folder name, and fix for a broken link and couple of minor build errors

---

kalite/distributed/static/js/distributed/exercises/models.js
kalite/distributed/static/js/distributed/topics/views.js

Develop frontend code is currently slightly broken due to the removal of ExerciseModels import in the sidebar code.
This rectifies that by simply removing the code that uses it, as it serves no current purpose anyway.

Don't load unnecessary log models in sidebar when we are not using them.

---

kalite/distributed/static/js/distributed/base/baseview.js

Fixes #4244.
- Remove the top-level view itself (via Backbone.View.remove) to get it out of the DOM before removing subviews, to minimize reflow overhead.
- Make sure we never recurse infinitely in subview removal, in case there's weird circularity.

Fixes #4244: Safer BaseView.remove: remove el before reflow, no infinite recursion.

---

kalite/control_panel/templates/control_panel/facility_management.html
kalite/control_panel/templates/control_panel/zone_management.html

(with a .container inside a .container, these inner divs were overflowing their parents; not so apparent on the distributed server, though noticeable, but super bad in the context of the central server's styling, which motivated the fix)
Before:
After:

Fix container-inside-container overflow issue.

---

kalite/distributed/demo_middleware.py

Fixes #4251. The cause of the bug here is that messages are already rendered in the
template, but making an API call that's unfiltered (in this case
/securesync/api) causes another reload of the same messages from the
demo server, hence the duplicates.
The change here is simple: we just filter out /securesync/api/.

Fix #4251. filter securesync api calls in the demo middleware.

---

data/version.yml
kalite/version.py

@rtibbles or @jamalex could you build a 0.15 assessment.zip?
Anything else that needs doing?

Bumping version to 0.15 to distinguish current develop branch

---

kalite/i18n/__init__.py
python-packages/django/core/management/commands/makemessages.py

Fixes #4276.
1. Restore the use of the `djangojs` domain. i18n js files are now less than 10KB.
2. Parse a lot of KA's JS strings, thanks to xgettext's builtin `JavaScript` parser.

Much strings -- i18n performance fixes.

---

kalite/updates/tests/__init__.py
kalite/updates/tests/regression_tests.py
python-packages/securesync/devices/decorators.py

Fixes #4282. Replaces #4283. Implemented as a client test instead of a browser test (execution time of ~10s vs ~30s).

Registration redirect does nothing when offline

---

kalite/settings/base.py

Since sessions are now stored in cookies, our default cookie expiration date may have some unintended consequences for computers with multiple KA Lite users. Admins who expect to get logged out on reboot, actually don't get logged out. 
This simple change ensures that the session cookie is cleared *when the browser is closed* ([not tab closed, browser closed](http://stackoverflow.com/questions/3976498/why-doesnt-session-expire-at-browser-close-true-log-the-user-out-when-the-bro)).

Expire cookies whenever we close the browser.

---

kalite/distributed/management/commands/restorebackup.py

DB Backup currently has a functionality for restoring backup from a given file. This PR fixes the referencing issue in 'restorebackup' management command which occurs while restoring a backup from a given file. Also, prints an error message if the given filepath is invalid.

DB Backup: Fix backup_filepath referencing issue and error out invalid filepath

---

kalite/distributed/static/js/distributed/utils/messages.js

Fixes #4117, instead of #4119 that suffered a bad rebase.

Replace the 'close' <a> element with an accessible button in user alert messages

---

kalite/distributed/management/commands/create_content_db.py
kalite/distributed/tests/browser_tests/language_packs.py
kalite/topic_tools/__init__.py
kalite/topic_tools/settings.py
python-packages/fle_utils/general.py
requirements.txt

For memory constrained systems such as Android and the SanDisk, admins may have the option of running the `create_content_db` which will generate a `contents.sqlite` option. This has some substantial memory improvements as shown [in this gist](https://gist.github.com/aronasorman/bceac4036dfc8e152f35).
Behaviour wise it should be identical to the old json content dict. Implementation wise, we generate an SQLite file that whose interface is similar to a dictionary.

Use SQLiteDict for the content cache.

---

kalitectl.py

Example:
```
➜  ka-lite git:(kalite-command-proxy-status) bin/kalite status
OK, running (0)
KA Lite running on:
http://192.168.40.146:7007/
http://127.0.0.1:7007/
KA Lite configured behind another server, primary addresses are:
http://192.168.40.146:8008/
http://127.0.0.1:8008/
```

Add correct status message when running with a proxy setting (nginx)

---

requirements_dev.txt

These requirements are duplicated in `requirements_test.txt`, resulting in an error when you run `pip install -r requirements_dev.txt`.

Remove duplicate requirements

---

kalite/updates/static/js/updates/bundle_modules/update_languages.js

Expose language pack management functions to global scope for onclick attributes.

---

docs/developer_docs/javascript_testing.rst
docs/developer_docs/utility.rst
docs/usermanual/userman_admin.rst

Partially fixes #4326. Just change `bin/kalite` to `kalite` in our docs.
Next trick up my sleeve is to change the [Restarting Your Server: Mac](https://learningequality.org/docs/0.14/en/usermanual/userman_admin.html#restarting-your-server-mac) section to conform to the new OS X installer.

Change mentions of bin/kalite to kalite.

---

kalite/coachreports/management/commands/generaterealdata.py

I wanted to test out coach reports with a more specific scenario.
* Adds a new kwarg to `generate_fake_facility_users` to make coaches. Since coach-facility group associations are not possible within the app, but permissible at a model level, I'm careful not to set the facility group for coaches.
* Adds a new option to `generaterealdata` (`--scenario-1`) as described in the help text. Behavior is exactly the same if this option is not passed.

Add a scenario option to generaterealdata mgmt command

---

setup.py

Fix #4382 -- we are MIT licensed

---

kalite/contentload/management/commands/generate_assessment_zips.py

This removes 4706 unneeded assessment items. Will see how much space that saves, shortly.

Don't bother including assessment items for blacklisted exercises.

---

kalite/control_panel/api_resources.py
kalite/distributed/features/steps/content_rating.py

Fixes #4367. See commit message:
```
Exportable content ratings are now filtered to be non-empty, where
we take non-empty to mean that both the quantitative ratings are not 0.
If they _are_ both 0, it indicates the user has not interacted with the
rating widget at all.
Some irrelevant columns are also removed from the result.
```
Now the output looks like this:

Content rating - clean csv output

---

kalite/distributed/static/js/distributed/rating/views.js
kalite/distributed/static/js/distributed/topics/views.js

Fixes #4309, and also fixes two other bugs I discovered while working on that.
See the commit message, where I describe the changes:
```
Check if content is available, if it's not then don't show the rating.
It took me a while to figure out that the "model" being passed around
was actually the entry in the sidebar itself... :(
Improve clarity by trimming down `show_rating` function a bit
and adding comments.
First error: Define a close function for RatingView and call it
instead of BaseView.remove, which removes the container element from
the DOM, thus foiling subsequent renders.
Second error: initialize rating_view's model property with
blank "content_id", "content_kind" -- if that initalization
logic is run it will cause the subsequent display logic to not
execute, since it's …
```

Content rating -- only show on available content

---

circle.yml

See: https://docs.saucelabs.com/reference/sauce-connect/
The `--readyfile` will `touch` the file when the connections is established, so we can wait for it.

Update circle.yml to wait for sauce connection

---

kalite/distributed/static/css/distributed/homepage.css
kalite/distributed/templates/distributed/homepage.html

Fixes #4432. Here's how it looks in various viewport sizes:
__Normal__
__Smaller__
__Smallest__ (when the hamburger shows up)

Style splash image responsively

---

kalite/contentload/management/commands/channels/import_channel.py
kalite/contentload/management/commands/contentload.py

On this branch, I ran this command:
`python bin\kalite manage contentload --import=D:\ka-lite\import_test\`
Got this output:
```
WARNING:kalite:No metadata for file
WARNING:kalite:No metadata for file
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:No metadata for file
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:Title missing from file , using file name instead
WARNING:kalite:Removing childless topic: _1
WARNING:kalite:Removing childless topic: _2
INFO:kalite:Downloaded topic_tree data for
0 exercises
0 content files
0 assessment items
```
After staring the server (and changed the settings to use new channel) it's apparently empty.
Archive of `D:\ka-lite\import_test\`: …

Import channel test

---

kalite/contentload/tests/generate_assessment_zips.py

TestUrlConversion is defined twice... one was clearly inadvertantly left in, since
the other has the same tests, but updated.
Let's see if our test overlords agree.

Remove duplicate TestCase subclass

---

kalite/distributed/static/js/distributed/rating/views.js
kalite/distributed/static/js/distributed/topics/views.js

Fixes #4407. @rtibbles I wasn't able to replicate the exact circumstances you reported, but I did pare down the # of requests as much as possible. See commit messages for details. Also addresses another issue I noticed.
There is an extra PUT request after POST requests to create a new rating model. It seems to be done automatically -- can we live with that?

Reduce number of ajax requests in content rating

---

kalite/distributed/static/js/distributed/bundle_modules/base.js
python-packages/fle_utils/django_utils/command.py

Add it to the global scope, so that it can be accessed by inline JS
in central server templates.
@rtibbles is this what you were thinking?

Add get_cookie to base module & global scope

---

kalite/distributed/static/js/distributed/user/views.js
kalite/distributed/static/js/distributed/utils/api.js

Fixes #4449 
Currently, if you are logged out and an API request returns a 403 forbidden, then our modal login does not get triggered (it will produce a Javascript error instead).
To test this, go to developer console, resources, and delete the sessionId cookie while on the video download page.

Properly triggers login on API 403.

---

python-packages/fle_utils/django_utils/command.py

On windows we need to specify the python interpreter for invoking bin/kalite.
This allows me to run tests on the central server on Windows.

Massage the Popen arguments into windows form

---

kalite/distributed/static/js/distributed/search/views.js

Don't autofocus on first element to make access to search page easier for keyboard users.

---

kalite/settings/_utils.py
kalite/settings/base.py

Fixes #4213. We already have said vulnerability wherein the SECRETT_KEY is both public and the same for each installation. With the introduction of sessions-in-cookies it's a double whammy.
So now the solution is to create a secret key file for each installation if it's not detected, and load that as the value of SECRET_KEY.
Assigning @jamalex, but @benjaoming please take a look too.

Generate a secret key file, and load SECRET_KEY from said file.

---

kalite/caching/__init__.py
kalite/updates/views.py

Sorry @rtibbles - I merged your PR #4510 earlier, made a comment, then clicked on the `Close and Comment` button, not sure why that was available but it closed your PR and did not merge it.  
So I'm re-creating this PR and merging this instead.
This fixes #4483 - fixed earlier by #4510.

Don't invalidate caches on the Mac, and warn users that they need to restart after video download - redo.

---

kalite/testing/base_environment.py

TransactionManagementErrors appear to be appearing again.
This is an attempt to catch them where they arise - during teardown of the database in the behave tests.

Try to catch TransactionManagementErrors during database teardown.

---

kalite/updates/management/commands/languagepackdownload.py
kalite/updates/videos.py

Ignore video_file_sizes.json - system location is unwritable

---

kalite/facility/api_resources.py

Renaming override_urls to prepend_urls in kalit/facility/api_resources.py removes warning from issue #3822.

deprecated function name change

---

MANIFEST.in.dist

#4555 
@aronasorman I found no django.po files in the application -- everything has been moved to languagepacks I presume?

Remove redundant lines generating warnings #4555

---

docs/installguide/install_all.rst

Hi @aron / @MCGallaspy - this updates the docs on "greyed-out assessment items on OSX during upgrade" and the uninstallation process on OSX.
This hopefully fixes https://github.com/learningequality/installers/issues/201

Update the OSX documentation.

---

kalite/distributed/static/css/distributed/video-js-override.less
package.json

Fix icons for old video-js version.
Fixes #4578

Strictly enforce video-js version for srt compatability. 

---

kalite/settings/base.py
kalite/topic_tools/settings.py

@aronasorman @benjaoming let me know if this seems tenable. Will test it out on the deb by pulling source and setting `IS_SOURCE=False`, assuming this essentially replicates installing using deb.

Put cache database in user-writable location

---

kalite/updates/static/js/updates/update_languages.js

Language packs not shown as available, due to version comparison on distributed server. See my commit message/code.
See @aronasorman's note for context: https://github.com/fle-internal/ka-lite-central/commit/7a48ceca9eff#diff-b4c6913ca485fa33b3dfb6040efc3dddR680
We should cherry-pick this to `0.15.x` and `develop` as well.
Commit message:
```text
Change version comparison logic
The central server sends a short version (e.g. 0.14), which the distributed server
then compares to its long version (e.g. 0.14.1). The problem is that 0.14 compares
as less than 0.14.1, so language packs are shown as unavailable. Instead,
when comparing two mismatched-length versions, only consider the shortest version
available -- thus 0.14 and 0.14.1 would compare equal. Then the languagepack versions
will be …
```

Fix language pack availability issue in 0.14.1

---

data/version.yml
docs/installguide/install_all.rst
kalite/main/api_resources.py

Supersedes https://github.com/learningequality/ka-lite/pull/4593. Most of the commits were already applied to 0.15.x.

0.15.x cherry-picks from 0.14.x

---

kalite/distributed/static/js/distributed/exercises/perseus-helpers.js

Fixes Javascript error in #4182.

Reinstate Khan i18n helpers, overwrite $._ to ensure translation.

---

.gitignore
Makefile
requirements_dev.txt

I would like this included in 0.15, because then the sdist will come with a man page that the debian dist can include.
It's automatically generated from the docutils output using cli2man.
This does not affect the 0.15 code base at all.

automatically generate a manpage and put it in docs/

---

kalite/settings/base.py
kalite/updates/management/commands/languagepackdownload.py

My suggestions for resolving merge conflicts.

Master into 0.15.x

---

kalite/coachreports/management/commands/generaterealdata.py

Fixes #4631
Apart from import error. There was another deprecated variable named video_cache which was also removed.

Fix the generaterealdata command by giving proper imports 

---

MANIFEST.in.dist
Makefile
kalite/__init__.py
kalite/distributed/management/commands/setup.py
kalite/settings/base.py
setup.py

Not touching content/assessment items right now. Fixes part of #4653. New behavior:
* Create empty db in `assets` make target, and include in sdist.
* If the user has no database at `settings.DEFAULT_DATABASE_PATH` and `settings.DB_TEMPLATE_FILE` is truthy, then the latter file will be copied to the former by the setup mgmt command.
The reason this works -- when the sdist is built `IS_SOURCE` is `True` (or it should be), so we create a db at `kalite/database/data.sqlite` (which is the `DEFAULT_DATABASE_PATH`). We simply preserve this file in the sdist, then when IS_SOURCE is `False` (and `DEFAULT_DATABASE_PATH` has a different value) we set `DB_TEMPLATE_FILE` to point to that file in the source tree.

Add empty db to sdist

---

kalite/coachreports/models.py
kalite/distributed/features/steps/content_recommendation.py
kalite/testing/behave_helpers.py
kalite/topic_tools/content_recommendation.py

commit message:
```text
Handles three errors.
1. In get_exercise_prereqs, if an unknown exercise id is passed in, it
now contributes nothing to the prereqs instead of raising an error.
2. Avoid a divide-by-zero error in coachreports.models.
3. Finally, in get_explore_recommendations, use of `next` built-in could
result in an unhandled StopIteration exception. Refactor to use for..in block.
```
@rtibbles inspite of the fact that no errors are now raised, the content_recommender api endpoint takes a really long time to return (one run took me 3.7 minutes). I think we can do two things (perhaps for 0.16), let me know if you agree:
1. Add a placeholder when awaiting the response.
2. Separate the content recommendation endpoint into three separate endpoints.

Content recommendation bugs

---

kalite/coachreports/api_resources.py
kalite/coachreports/api_views.py
kalite/coachreports/models.py
kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-container.handlebars
kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-details.handlebars
kalite/coachreports/static/js/coachreports/tabular_reports/hbtemplates/detailspanelbody.handlebars
kalite/distributed/static/js/distributed/exercises/views.js
kalite/topic_tools/__init__.py

Fixes #4650. Partially at least. CC @jinchuika
I still couldn't get the exercise text translated, despite propagating the language in `get_exercise_cache` too. Any ideas @rtibbles?

propagate the request language in user progress.

---

kalite/distributed/management/commands/setup.py

Seems like an earlier call to the DB unexpectedly causes this branch to be executed no matter what (even if a db didn't exist prior to running the "start" command).
So let's just consolidate the conditional -- shouldn't matter, since syncdb is idempotent.

Call syncdb regardless of database existence

---

Makefile

Building the Windows installer requires a zipfile here. @benjaoming

Create zipfile with `make dist` command

---

docs/installguide/install_all.rst

Because of an upstream problem in Ubuntu, Software Center will not display our debconf dialogues unless libgtk2-perl is installed. Actually, it will lock up. This has been recently accepted as one of their "One Hundred Papercuts", so it seems likely, it will be backported for Trusty.
Anyways, here's a fix. Should be backported for 0.15.x as it doesn't need a new release to make it to RTD.
learningequality/installers#146
@EdDixon @radinamatic

doc fix for learningequality/installers#146

---

docs/installguide/install_all.rst

Cherry-picked docs change from develop affecting all previous .deb releases
learningequality/installers#146

backported doc fix for learningequality/installers#146

---

data/version.yml
kalite/version.py

Publish to 'latest' on RTD (which tracks the master branch)
http://ka-lite.readthedocs.org/en/latest/

0.15.x docs changes

---

requirements_dev.txt

Hi @aronasorman - this removes the re-declared `django-extensions` pip requirement so we can build the OSX 0.16.x installer on Bamboo.

Remove doubly-declared requirement.

---

kalite/updates/management/commands/languagepackdownload.py

This function would likely be broken because of the unresolved import for REMOTE_VIDEO_SIZE_FILEPATH

fix unresolved import in languagepackdownload

---

kalite/distributed/management/commands/retrievecontentpack.py
kalite/topic_tools/content_models.py

Done:
- Fixes test failure relating to unreferenced variable 'values'
- `retrievecontentpack` now supports installing from a local content pack.
- Annotate the right content database.
- Generate the language specific JS file.
- ~~non-english content packs are not getting translated. Figure out why.~~ (fix is in the content-pack-maker repo)
- Integrated `retrievecontentpack` with the updates framework.
WIP. I'll try to get as many changes as I can before EOD.
Todo:
- Write docs on how to use `retrievecontentpack`.
- Port the language pack download interface to use `retrievecontentpack`.
Link to the first PR: https://github.com/learningequality/ka-lite/pull/4757

Content pack download v2

---

setup.py

Replaces #4762. Makes `setup.py` safe to run on OSX (in particular our build server).

Modified setup.py for OSX, avoid error on build server

---

scripts/add_systemstart_task.bat
scripts/remove_systemstart_task.bat

See https://github.com/learningequality/installers/pull/322

Finally remove batch scripts; moved to installers repo

---

kalite/distributed/static/css/distributed/content-rating.less
kalite/distributed/static/js/distributed/rating/hbtemplates/rating.handlebars
kalite/distributed/static/js/distributed/rating/hbtemplates/star.handlebars
kalite/testing/base_environment.py

Fixes #4308, fixes #4544.
See screenshots. Commit msg:
```text
Played around with different layouts within bootstrap,
not totally satisfying for resolutions > ~400px and < 768 px,
but good enough without changing the hb template or view logic.
At smallest res, all rating buttons and labels stack,
and no hover-label is shown.
As the resolution increases (to bootstrap's col-sm- size),
the labels and buttons flatten out, and a hover label is
shown. The size of the buttons also progressively increases.
```
**Smallest**
**Larger**
**Largest**

Rating display issues

---

kalite/distributed/management/commands/retrievecontentpack.py

Previously we generated our own dummy metadata. Now, extract the one
that comes with the content pack. 
Also, there's a fix in the content pack generation side. We now properly include interface translations. See https://github.com/fle-internal/content-pack-maker/commit/f1041d22ab2525e84f6630c2ddeda3f9aefe7970

Extract metadata from content pack.

---

kalite/basetests/tests.py

The "scripts path" it was testing was removed from the KA Lite repo in #4771.

Remove irrelevant test

---

kalite/distributed/management/commands/setup.py
kalite/settings/__init__.py
kalite/settings/base.py
kalite/shared/exceptions.py
kalite/shared/warnings.py

Fixes #4496. Decided it would be safest to raise an exception, rather than both trying to remove the warnings *and* refactor old code to remove cruft -- will open separate issue for that.

Replace deprecation warning by raising exception

---

kalite/topic_tools/content_models.py
kalite/topic_tools/tests/__init__.py
kalite/topic_tools/tests/content_models_tests.py

get_content_parents() should return an empty list when passed and empty list of ids.
Fixes https://github.com/learningequality/ka-lite/issues/4662

Fixerror in topic_tools/content_models.py get_content_parents() method

---

kalite/topic_tools/content_models.py

Add in the pk field to AssessmentItem. This is so assessment items can be saved in the content-pack-maker side.

Add a pk to AssessmentItem

---

docs/kalite-theme/breadcrumbs.html
docs/kalite-theme/theme.conf

Targeting #4831 for 0.16.x instead, fixes #4348

Remove docs GitHub link for offline users

---

kalite/distributed/static/js/distributed/exercises/models.js

The model's urlRoot has two trailing slashes, which was misinterpreted by the API endpoint and resulted in not content being returned. This seems to have *been* working, but for some reason I started experiencing errors from it. Could it be that I need to update my JS sources, or that updating them broke this somehow? Or perhaps my browser *used* to handle it gracefully but now it doesn't?
Testable with Selenium, but probably overkill? We need to revive the js testing framework!

Remove trailing slash from API url

---

kalite/distributed/management/commands/retrievecontentpack.py

Rather than looping over them in python code then extracting them one by one.
Before: https://github.com/learningequality/ka-lite/issues/4863#issuecomment-185875070
After: https://github.com/learningequality/ka-lite/issues/4863#issuecomment-185889160
15 seconds vs. 26 seconds.
Might also solve the corrupt filenames getting served, as seen by @MCGallaspy.

Extract all assessment resources at once.

---

kalite/coachreports/static/js/coachreports/student_progress/views.js

Fixes https://github.com/learningequality/ka-lite/issues/4840

fixes error show_message is not defined

---

Makefile
circle.yml
kalite/distributed/features/steps/ui_regression.py
kalite/distributed/features/ui_regression.feature
kalite/distributed/static/js/distributed/user/hbtemplates/navigation.handlebars
kalite/testing/behave_helpers.py

Fixes #4375 by adding a top-level item to the menu for docs if they are detected. Appears regardless of whether the user is logged in or not. Now also links directly to the user manual section, and I changed the display name accordingly. @radinamatic your opinion on this?
Screenshot:

Create top-level nav item for docs

---

kalite/__init__.py
kalite/distributed/management/commands/setup.py

This function was already considered really odd. In addition to that, having utility functions in `kalite/__init__.py` is bad practice.
None
Not expecting this to be a challenge to merge. Searched through the codebase, and this was the only occurrence.

remove is_installed, replace with explicit check for database file

---

kalite/distributed/static/js/distributed/bundle_modules/homepage.js
kalite/distributed/static/js/distributed/user/views.js

fix issue #4879
The current behavior will be, right after the superuser is created, the login modal will pop up.
#4879

enable login right after superuser is created

---

kalite/distributed/cherrypyserver.py
kalite/distributed/management/commands/retrievecontentpack.py

Fix assessment serving

---

kalite/distributed/management/commands/retrievecontentpack.py
kalite/updates/management/commands/classes.py
kalite/updates/management/commands/videodownload.py
kalite/updates/management/commands/videoscan.py

Removes the seemingly superfluous foreground flag on UpdatesCommands - as it is set during init, can't be modified post hoc after handle (as suggested in the comment that implemented it).
This is a reversion of a previous change that caused this bug.
Fixes #4817.
@benjaoming please comment as to why the foreground flag is necessary if I am removing it in this way (and just letting the process_log be None), and I will try to update this to account for that use case, but for now, it just seemed to block the intended use of these UpdatesCommands.

Let commands actually set their progress log.

---

Makefile

Save time and space. The .zip files are not necessary for pip to work.
Please comment if you **do** find them necessary on PyPi.

Do not create a .zip archive for sdist, tar.gz is enough

---

kalite/distributed/static/js/distributed/video/hbtemplates/video-player.handlebars
kalite/distributed/static/js/distributed/video/views.js

Adds the playback speed button back to our video player. Removed inline video.js configuration options in favor of explicit configuration in our view. @jamalex you're identified as my bug-buddy for videos, but if you don't have the opportunity to review this then please indicate that's the case.
Fixes #4639.

Add playback speed button to video player

---

kalite/distributed/static/css/distributed/khan-lite.less

Color that was initially set for the inline skip button text was #7a7a7a that was basically **gray**, now the button text color is changed to **black**.
Fixes #4905

'Done' and 'Skip' button now appear enabled

---

kalite/facility/api_resources.py
kalite/facility/forms.py
kalite/facility/middleware.py
kalite/facility/templates/facility/facility_group.html
kalite/facility/views.py

Don't load facilities into session object.
Don't even bother caching a list of facilities on the central server.
No regression test, as the main offense of this issue was on the central server, not distributed.
Fixes #4720

Don't load facilities into session object.

---

kalite/updates/download_track.py

Catch occasional error reported by @radinamatic in #4817 
Catch error from popping from empty list that appears to happen sometimes during video download.

Catch pops from an empty list.

---

kalite/distributed/static/js/distributed/utils/api.js

Maybe there is a "real" `case 0` that warrants the previous message, but in 3 months of testing I haven't seen it. Every time this message appears, it's about waiting for the server response at logging in and out, and not really needing to "try again later". 
I can't even grab a screenshot, it resolves too fast on my dev setup, which kind of proves a point... :)
Let me know what you think @rtibbles @aronasorman

Change message for the user while they wait for server response

---

kalite/distributed/static/css/distributed/bootstrap-overrides.less
kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-explore-topic.handlebars

Width value change to 100% so as to avoid overlapping of text.
Fixes #3863

Removed overlapping text of content recommendation explore

---

kalite/distributed/static/js/distributed/topics/views.js
kalite/topic_tools/content_recommendation.py
kalite/topic_tools/tests/resume_tests.py

*Short description*
Main oddity is that one of the files had tab indents, so that has been rectified.
Fixes #4910

Add catches for missing data or None returns in content data.

---

kalite/i18n/management/commands/makemessages.py

Add more ignore patterns for our `makemessages`, so it doesn't try to process random stuff like `node_modules` and `dist-packages-temp`, which will make it error out due to some files' non-ASCII nature.
Dead simple PR.

Add more ignore patterns when making messages

---

kalite/topic_tools/content_models.py
kalite/updates/api_views.py
kalite/updates/static/js/updates/bundle_modules/update_videos.js
kalite/updates/tests/api_tests.py

Properly sets the language codes on the client side, and then properly parses them on the server side in order to ensure that video download, video deletion, and video scanning all actually do this for multiple languages, rather than just English.
Fixes #4937, fixes #4933, fixes a behaviour noted in #4929 by @radinamatic.

Video download fixes

---

kalite/main/api_views.py
kalite/topic_tools/content_models.py

For 0.15 we made a hack that manually maps `pt-BR` to `pt`. This hack is not needed anymore, in fact it actively hinders `pt-BR` from working properly by causing annotation to happen on a nonexistent DB.

Remove that custom pt-BR -> pt mapping.

---

kalite/coachreports/api_views.py
kalite/coachreports/static/js/coachreports/coach_reports/models.js
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/coachreports/static/js/coachreports/tabular_reports/views.js
kalite/coachreports/tests/coachreport_tests.py
kalite/testing/mixins/student_progress_mixins.py
kalite/topic_tools/content_models.py

Ensures that when the topic selector is used in the coach reports, this also restricts the data used in the tabular report to just those topics.
I have not written any tests, because we need Javascript unit tests to properly check this. Sorry, the integration tests are just too flakey and difficult to implement at this juncture.
To test this, generate some data using `generaterealdata`, go to the coach reports, look at the tabular report.
Select a topic from the topic drop down. The report view will refresh. Show the tabular report again. Now only content items in the topic drop down will display.
Fixes #4869.
Also puts in the KA Lite side fix for #4728 - sort_order is being set incorrectly by content packs though, so this change is not yet visible.

Propagates topic selection to tabular coach report.

---

.github/PULL_REQUEST_TEMPLATE.md
kalitectl.py

Fixes #4935:
```text
Allow positional arguments with dashes inside
It choked on valid commands like:
`kalite manage retrievecontentpack local es-ES foo.zip`
Because of the dash in the middle of a positional argument.
So only match if there is preceding whitespace.
Also remove redundant non-capturing group -- negative lookaheads
don't capture anyway.
```
Remove reference to nonexistent CHANGELOG.rst in our PR template, too.

Allow positional arguments with dashes inside

---

kalite/distributed/static/css/distributed/content_recommendation.less
kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-nextsteps-lesson.handlebars
kalite/distributed/static/js/distributed/contentrec/hbtemplates/content-resume.handlebars

Fixes display issues for icomoon icons on the content recommendation templates.
No tests - we don't have a testing framework for css rendering.
Fixes #4911

Fixes display issues for icomoon icons used in content recommendation.

---

kalite/updates/static/js/updates/bundle_modules/update_videos.js

Prevents Javascript TypeErrors from being thrown.
UI is unaffected, this just ensures against unnecessary and misleading JS errors in the console.
@MCGallaspy this was reported by @radinamatic as part of her follow up on #4937 - that issue is solved, but these residual errors could be misleading in debug reports.

Prevent TypeErrors getting thrown on partial downloads.

---

kalite/coachreports/tests/coachreport_tests.py
kalite/distributed/static/js/distributed/topics/views.js
kalite/topic_tools/tests/explore_tests.py

Fixes a sidebar rendering bug, and also extant test failures on 0.16.x
Fixes #4948 (follow steps for replication there to verify fix).
Fixes #4956 (passing test suite will verify this fix).
Sidebar works as intended:

Sidebar bug fix and test fix up

---

Makefile

Cleans up the `release` command and uses twine instead of `setup.py upload` because the latter is considered unsafe.
It's already tested because the 0.16b1 was released with it...

use twine for PyPi uploads

---

kalite/coachreports/static/js/coachreports/student_progress/hbtemplates/playlist-progress-container.handlebars

Some text that contained % symbols did not use %% to escape them. This made sprintf get mad.
Fixes #4951

Escapes %s to stop sprintf throwing an error.

---

kalite/distributed/features/learn_content.feature
kalite/distributed/features/steps/learn_content.py
kalite/distributed/static/css/distributed/video-js-override.less
kalite/distributed/static/js/distributed/bundle_modules/base.js
kalite/distributed/static/js/distributed/video/views.js
kalite/testing/base_environment.py
kalite/testing/behave_helpers.py
kalite/topic_tools/annotate.py
kalite/topic_tools/content_models.py
package.json

Migrate to VTT subtitle format. They're included in the content packs, so we just have to serve them (and tweak a few things). Upgrade to the latest video.js as well.
Native text track support seems to be sparse or broken. Look at the commit messages for a description of the issue.
I would like guidance on writing a test for this. One thing that might not be too brittle, assuming we stick to video.js, would be to load a video page and assert that the "CC" button appears. Alternatively, we could use the video.js api to assert that the expected [textTracks](http://docs.videojs.com/docs/api/player.html#MethodstextTracks) are present.
Both would involve installing a content pack on the test server and downloading at …

Migrate to VTT subtitle format

---

kalite/coachreports/static/js/coachreports/coach_reports/hbtemplates/landing.handlebars
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/control_panel/templates/control_panel/base.html
kalite/distributed/management/commands/retrievecontentpack.py
kalite/distributed/management/commands/setup.py
kalite/distributed/views.py
kalite/i18n/base.py
kalite/i18n/management/commands/makemessages.py
kalite/settings/base.py

Some i18n fixes to get ready for the 0.16 po file release.
Review by commit. Changes will make more sense.

I18n fixes

---

kalite/distributed/static/js/distributed/exercises/views.js

Fixes error in points display. For exercise log sync events, only update the points display if there is a discrepancy between the points reported by the server and the points known to the client.
Here's my really good reason. Testing this using selenium would take the following steps:
1. Create new student account and set the points to some appropriate initial value.
2. Navigate to an exercise.
3. Interact with the exercise to gain points.
4. Make assertion about observed points in user menu.
This is challenging because we don't provide a testing api for interacting with content nor a reliable way to determine the "state" of the page in order to avoid race conditions (e.g. polling the `#points` element too soon or …

Update points if there is server-client discrepancy

---

data/narratives.yml
kalite/distributed/templates/distributed/base.html
kalite/inline/api_views.py
kalite/inline/static/js/inline/bundle_modules/bootstrap.js
kalite/inline/static/js/inline/views.js

Fixes #4986. Clicking on the inline help on that page now disables the button and creates a warning bubble. See screenshots.
Also fixes up the existing inline help which was broken due to UI changes.
Not clear how to test this... Maybe in the future, when the UI changes the changer must be responsible for double checking the inline help feature on that page?
Fixes #4986.

Inline help fixes

---

kalite/updates/static/css/updates/update_languages.css
kalite/updates/static/js/updates/bundle_modules/update_languages.js
kalite/updates/templates/updates/update_languages.html

Fixes #4955. But while looking in to this I went down a dead end with the updates management command base classes: https://github.com/learningequality/ka-lite/blob/0.16.x/kalite/updates/management/commands/classes.py#L41
As far as I can tell, it's not possible to pass kwargs to a command's constructor using the `call_command` function (or possibly at all). For instance, it doesn't seem possible to set the `process_name`, which was the first thing I attempted. Instead changes to the back-end (like in this case changing the management command that's being called) require changes to the front-end. Is this worth a refactor?
Test incoming.
Fixes #4955.

Languagepack progress bar fix

---

kalite/distributed/static/js/distributed/user/hbtemplates/navigation.handlebars

Fixes #4977. 
Tab link now has both a title & target attribute with the appropriate icon and accessible info for the screenreader users. I renamed it to `DOCS` since `USER MANUAL` seemed too big for me visually, although I have considered `HELP`too...
@MCGallaspy

Open docs link in a separate window (accessible)

---

kalite/distributed/features/steps/superuser_create.py

Seems to have been added by a revert-revert, however
it seems to be the wrong assertion to make in this case.
Causes flakiness if the modal is dismissed *first*.

Remove unnecessary assertion in test

---

Makefile

Simple: Do one-pass finds in Makefile. Otherwise it takes multiple passes, which can be much slower.

Do one-pass finds in Makefile

---

Makefile

Reverts learningequality/ka-lite#4978
Seems to have been the cause of some error: https://github.com/learningequality/ka-lite/commit/f4ac347a001f4d2f275e564fe80f627e5ce74287#commitcomment-16816534
Goodbye concise `find`s...

Revert "Do one-pass finds in Makefile"

---

kalite/updates/static/js/updates/bundle_modules/update_videos.js

Speculative attempt to prevent uncompleted topics from being shown as complete.
Stronger checking on files_complete attribute.
Tries to fix #4959

Attempts to ensure against inappropriately flagging topics as complete.

---

kalite/distributed/static/js/distributed/exercises/views.js

Due to some refactoring, we were no longer setting `exercise_id` when saving an `AttemptLog`. This means there was no way of know what exercise it was for, which was messing up coach reports, syncing (it was a required field, and hence caused failed validation), and exercises (refreshing the page would make attempts disappear).
Minimal changes here, but they fix all of these issues.
Fixes #5017 and #4989.

Ensure attempt logs are given exercise_id, and inserted in right order.

---

kalite/distributed/views.py
kalite/i18n/base.py
kalite/testing/mixins/browser_mixins.py

Fixes #5005. We now show this alert on the homepage if there are language packs that need to be upgraded:
Note: is shown for everyone, even if you're not logged in. Since this can potentially prevent the said languages from functioning properly, having everyone see it will hopefully convince the admin to upgrade sooner than later.

Languagepack upgrade alert

---

kalite/distributed/management/commands/retrievecontentpack.py
kalite/i18n/base.py

Review by commit. Changes:
- we modify `get_localized_exercise_dirpath` to just use the lang code we get from the content pack.
- extract the html exercises bundled in content packs into the right directory.
To test this, use the content pack linked in the dev room.

Extract html exercises

---

kalite/main/tests/base.py
kalite/testing/base_environment.py
kalite/topic_tools/annotate.py
kalite/topic_tools/content_models.py
kalite/updates/api_views.py
kalite/updates/management/commands/videodownload.py

Properly stamps availability flags, files_complete etc. on different languages, and ensures that the subtitle fallback annotation works properly.
Also filters retrieval of youtube_ids for downloading and deletion by whether there are any files to download/delete.
Finally, prevents overwriting/download of videos that already exist in the content dir.
Fixes #4994, fixes #4990, and supersedes #5016.

Availability

---

kalite/distributed/management/commands/setup.py

In some upgrade scenarios (like on the RPi) the system's
built js files might have a timestamp *earlier* than the
static files appearing in the user's static files location.
The effect is that `collectstatic` called during an upgrade
will not replace the old static files with the new ones, since
the timestamp is reverse.
So force them to be cleared. But preserve the "extra" files we
add in, e.g. for subtitles (vtt, srt) and exercise templates (html).
Those must not be removed, since they're downloadable content!

Force clear out collectstatic on setup

---

kalitectl.py

Quick fix to get the `kalite diagnose` command working again. This command is useful for getting more details in bug reports from users.
#4974

Fixes #4974: Remove broken assessment DB display from diagnose command.

---

kalite/settings/base.py

As seen in #5030, `logging.StreamHandler` is causing problems on Windows, and isn't logging correctly. As this causes problems for other parts of the application, this PR disables the logging output, specifically on Windows.
Fixes #5030.

Fixes #5030: Disable logging on Windows, to avoid errors.

---

kalite/coachreports/features/coachreports.feature
kalite/contentload/management/commands/unpack_assessment_zip.py
kalite/distributed/management/commands/setup.py

@aronasorman knows what's what, and I gotta run. Can add more notes later as needed.

Fixes to logic in setup management command for loading content packs.

---

data/version.yml
kalite/distributed/management/commands/setup.py

Fixes #5069. Instead of blanket preserving all HTML files, we now specifically preserve the files found under `perseus/ke/exercises`, as these are the only HTML files that can't be `collectstatic`'ed (they come from content packs).
I ran manually tested the sdist made from this branch using the following procedures on an RPi 3:
1. A fresh install
```
1. create a new virtualenv and ensure there's no .kalite dir
2. pip install ka-lite-static-0.16.1.tar.gz
3. kalite manage setup (downloading the content pack in the process)
4. load the kalite server and check for docs, and do some khan exercises
```
outcomes: docs link loads to 0.16, khan exercises load correctly.
2. An upgrade from 0.15.1 to 0.16.1
```
1. pip install ka-lite-static-0.15.1.tar.gz with a current time of 04/03/2016
2. kalite …
```

Preserve content pack assets from collectstatic(clear=True).

---

kalite/distributed/static/js/distributed/exercises/views.js

Critical bug fix for 0.16.2, as discussed with @aronasorman and @rtibbles.
Problem: `data_model.get("exercise_id")` was `undefined`, and hence when we made a request for attempt logs, it didn't filter by exercise, and returned the last 10 of *any* attempt logs from the user.
@radinamatic, I will send you an sdist momentarily, for testing.

Fix critical bug in filtering attempt log collection request properly

---

docs/installguide/install_all.rst

Link in CLI snippet out-dated, adding a link to redirect in text part, too.

Update broken links for Raspberry Pi in docs

---

data/version.yml
kalite/contentload/management/commands/unpack_assessment_zip.py
kalite/contentload/tests/unpack_assessment_zip.py
kalite/distributed/management/commands/setup.py
kalite/topic_tools/base.py
kalite/version.py

Final changes before 0.16.4
As noted in #5105 :
> Error was that the original assessment_zip used to contain a file channel.name and the legacy version doesn't. Fixing it in the codebase.

Fix channel name

---

MANIFEST.in.dist

As mentioned by @rifatbd in #5099, we are missing woff2 files. They need to be in our MANIFEST in order to end up in the sdist.

Add woff2 files to MANIFEST and sdist

---

kalite/distributed/static/js/distributed/video/views.js

Addresses the error message issue in #4875.
Tested with admin and no user: now, no error message.
With logged-in learner, still saves the log at the end of the video.

Do not save unconditionally when video ends; only if learner logged in.

---

kalitectl.py

As reported by  @harishbalachandran, trying to connect to a server defined in kalite.pid may cause a socket.error
Here, we catch it and thus assume that a `socket.error` indicates a running instance that's dead somehow or another network error that we don't need to worry about.
#5132

Treat socket.error as if no server is running

---

kalite/__init__.py

Make ROOT_DATA_PATH consider the KALITE_DIR environment variable
Otherwise, kalite start will fail to find the static media files that it will try to copy on the first run, causing assets to be unresolvable when loading the web UI.
* I'm unsure how to write a test for this, but I checked it manually. Any advice?
* Not needed: it's all about using KALITE_DIR in a missing place, which is already documented
* Not needed
https://github.com/learningequality/ka-lite/issues/5143

Make ROOT_DATA_PATH consider the KALITE_DIR environment variable

---

kalite/control_panel/templates/control_panel/device_management.html

Quick fix for #2003 - since we're clearly not displaying an IP address but a host name, let's write that so it isn't confused with the local device IP
We apparently have issues that can be fixed in 2 seconds :)
#2003

Since we're clearly not displaying an IP address for the local device..

---

kalite/distributed/middleware.py

We hardcode-specify which pages are allowed during lockdown :/
Tested that this enables both first-run admin creation and subsequent logins, after which the user can view content etc.
This is critical to fix because reporter has said so, and I believe @Aypak :)
#5117

Allow logins during LOCKDOWN #5117

---

docs/installguide/release_notes.rst

Seems "not okay" that users should be forced to guess which languages are currently broken.

Detail affected languages in release notes

---

kalite/settings/base.py

allow for CONTENT_ROOT to be set with an environment variable
*If the PR has documentation, link the file here (either .rst in your repo or if built on Read The Docs)*
*They're nice. :)*
We use this at endlessm.com to allow sharing content whilst keeping the databases separate (we merge them on launch).
Signed-off-by: Niv Sardi <xaiki@evilgiggle.com>

allow for CONTENT_ROOT to be set with an environment variable,

---

kalite/topic_tools/content_models.py

This is to ameliorate the slowness identified in https://github.com/learningequality/ka-lite/issues/5200. 
On my laptop, with the full set of videos:
- Old code: 1 hour 8 min
- New code: 6 mins 24 seconds
So, the speedup looks to be around 10x.
The main sources of the speedup:
- `.annotate` was super slow in peewee; now we use list comprehensions
- we recalculated shared ancestors numerous times (non-deduped recursion); now, we queue up and then recurse level-by-level, only ever updating each node at most once

Optimizations to annotate_content_models for a 10x speedup

---

kalite/distributed/middleware.py

The Lockdown feature was still not working as expected. Students were still not able to login when lockdown activated. @benjaoming made a fix that got rid of page redirect error that was previously present when lockdown was activated
#5150 
Students were not able to login when lockdown was activated because /securesync/api/user/login was not whitelisted. Tested and working after this change.

Allow logins during lockdown

---

kalite/contentload/management/commands/unpack_assessment_zip.py
kalite/contentload/tests/unpack_assessment_zip.py
kalite/distributed/management/commands/setup.py
kalite/i18n/base.py

This error has caused downloading of assessment items to fail, but no one has noticed, so likely no one uses this functionality. It's gonna be deleted in 0.17.
#5209

String formatting error failing in legacy download of assessment items

---

kalite/contentload/management/commands/unpack_assessment_zip.py
kalite/contentload/tests/unpack_assessment_zip.py

It seems that annotating the content db while running BDD tests concurrently will fail. This is okay, tests run locally.
None
#5216

Disable unpack assessment zip command tests

---

kalite/distributed/cherrypyserver.py

According to cherrypy docs, we can add a dictionary of content types:
https://cherrypy.readthedocs.io/en/3.2.6/refman/lib/static.html#cherrypy.lib.static.staticdir
I hope this *supplements* the already well-known mimetypes and doesn't mean that we won't get content type headers for all the other files.
@harishgangwar
Let's ensure that already known MIME types are still supported :)
#5140

Try to add well-known content types because of Windows XP

---

kalite/distributed/features/steps/content_rating.py

BDD tests are failing again, and failure doesn't occur locally as usual.
None
Related #5215 - however, this is a new error
https://saucelabs.com/jobs/fa013f75e77b407b8e18cd34109f9701
When complaining about not being able to click feedback element, this is the screen shot shown:

Try adding a wait for element to be visible before clicking it

---

kalite/distributed/management/commands/setup.py

Seems like an old bug and some kind of untested code that's been introduced a long time ago.
If you're a Mac expert the please feel free to jump in.
Otherwise please feel convinced by this:
```
➜  ka-lite git:(fix-uid-check) sudo python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getuid()
0
```
#5032

test getuid() == 0 instead of arbitrary 502

---

kalite/version.py

There was a missing return statement such that the `user-agent` header on various calls to our central hub was being set to `None`.
@arceduardvincent - it would be nice if you could test if this could be the cause of your mysterious pyrun crashes.
N/A
Possibly #5211

Fix missing return statement in user_agent helper function

---

kalite/settings/base.py
kalite/topic_tools/content_models.py
requirements.txt

Adds SQLite pragma support for content databases.
- Upgrades our peewee version to add pragma support for `SQLiteDatabase` calls.
- Adds a new setting in `base.py`, called `CONTENT_DB_SQLITE_PRAGMAS`, which should be a list of two-tuples. By default it's an empty list, but you can override it like so:
```python
CONTENT_DB_SQLITE_PRAGMAS = [("journal_mode", "MEMORY"),
("temp_store", "2")]
```
depending on your situation. See [this link](https://www.sqlite.org/pragma.html) for a list of pragmas you can put here.

Pragma support

---

kalite/distributed/features/steps/superuser_create.py
kalite/testing/behave_helpers.py

Enough facepalming. Make a couple of very slow tests faster and more reliable (they still failed randomly).
Cuts off 1:50 from test time on my local system.
Before:
```
1 feature passed, 0 failed, 0 skipped
7 scenarios passed, 0 failed, 0 skipped
42 steps passed, 0 failed, 0 skipped, 0 undefined
Took 2m22.849s
```
Now:
```
1 feature passed, 0 failed, 0 skipped
7 scenarios passed, 0 failed, 0 skipped
42 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m31.488s
```
-
-

Make wait times a lot shorter for silly BDD tests

---

kalite/testing/base_environment.py

As I merged #5245, the tests on Circle failed again. This time because Sauce was down. So let's just ignore that.
https://circleci.com/gh/learningequality/ka-lite/2499
Nah I guess we can all do without if Sauce is down.. there'll be a message in the log, and one can just build again if Sauce output is wanted.
None

Ignore SSL timeouts when SauceConnect is down

---

docs/installguide/release_notes.rst
kalite/project/settings/base.py
python-packages/securesync/templates/securesync/register_public_key_client.html

~~I was unable to install requirements, not sure what the difference is, maybe Travis has been running another version of Pip and this.~~
~~Furthermore, fixed an issue since South fails to find migrations and thus if we try to migrate a fresh database, stuff would break.~~
Finally, that button I was trying to add :)
#4622

Device registration completed

---

kalite/distributed/static/js/distributed/exercises/views.js

Fixes #4875.
This ensures that users see a notification of how much they need to answer to achieve mastery, get a message when they achieve mastery, and don't overflow the progress box with check marks every time they submit an answer after mastery.

Fixes exercise messaging and attempt overflow errors.

---

docs/installguide/release_notes.rst

This is important to know: If someone upgrades from 0.15 to 0.16, they *will* experience problems with video downloads. The rest is stated in the commit...
None really, just a little addition to the docs before releasing!
#5263

Add a known issue for Windows upgrades from 0.15 due to #5263

---

README.rst
circle.yml
requirements_test.txt

Byebye coveralls.io, hello Codecov

---

MANIFEST.in
docs/installguide/release_notes.rst

favicon.ico missing in distributed set of files, little KA green leaf now appears in browser window decorations and shortcuts

favicon.ico missing

---

docs/installguide/release_notes.rst
kalite/cli.py

As the release notes will read, we have `bin/kalite manage runserver --settings=kalite.project.settings.dev` which does the job.
But furthermore, we should not expose developer options to users.

Remove watchify code from cli, it belongs in runserver (which works!)

---

docs/installguide/release_notes.rst
kalite/distributed/static/js/distributed/user/views.js

Forces a javascript redirect if the word "signup" appears in the URL. The page itself is already protected server-side and users can't actually signup after logging in.

Special little hotfix for signup page redirect - fixes #3926

---

docs/installguide/release_notes.rst

Small changes, to ensure that stuff that users should read is at the top, and everything for developers is below the folds.

Move some developer-oriented release notes to code cleanup

---

kalite/distributed/management/commands/setup.py

Add possibility to use patterns of own choice to content packs to allow installers to version them
E.g. the debian installer will use `/usr/share/kalite/preseed/contentpack-0.17.en.zip` for the English content pack, thus avoiding installing 0.17 content packs when upgrading to 0.18 in some distant future.

More filename patterns for contentpack preseeding

---

kalite/distributed/static/js/distributed/perseus/ke/.gitmodules

I'm very sure this file isn't in use, removing it because it breaks our RTD builds because RTD automatically checks out submodules... and this particular submodule doesn't even exist :)
This change will be ported into all branches.
@rtibbles - just letting you know :)

Remove .gitmodules file causing RTD to break

---

docs/installguide/release_notes.rst

Release notes - Windows needs to be running Python 2.7.11+
https://github.com/learningequality/installers/pull/427

Release note concerning the .whl windows update 

---

kalite/i18n/api_views.py

(resubmitting against develop branch per [request](https://github.com/learningequality/ka-lite/pull/5340#issuecomment-262745332))
In multi-lingual environments, it is not user friendly for each user to change the default language manually with the drop-down box on the bottom of the page. This patch allows setting the language through a link, which then redirects the user to the requested content. We use this patch in RACHEL for our multi-lingual installations. You can see it in action here, where we link to English, French, and Spanish versions on the same server:
http://rachelfriends.org/previews/rachelplus-en/
http://rachelfriends.org/previews/rachelplus-es/
http://rachelfriends.org/previews/rachelplus-fr/
It would be nice if this functionality were included in the official release.
- …

ability to change language via url redirect, added docstring

---

docs/installguide/release_notes.rst
requirements.txt

CherryPy doesn't document all changes, but this upgrade immediately meant I could see cache invalidation go back to normal, fixing #5317
Since it's an upstream bug, we don't write tests, we expect dependencies to work :)
Tested:
1. Changes in files => HTTP 200
1. Unchanged files => HTTP 304
#5317

Cautiously upgrade CherryPy to 3.3.0 - fixes #5317

---

docs/installguide/release_notes.rst
kalite/distributed/custom_context_processors.py
kalite/distributed/static/js/distributed/base/baseview.js
kalite/distributed/static/js/distributed/bundle_modules/base.js
kalite/distributed/templates/distributed/base.html
kalite/settings/base.py
kalite/testing/behave_helpers.py

We have received comments that our user-facing JS error handling may result in some bad learning experiences @j-schwartz
The original screenshot documents a default error message stemming from tasty-pie. It seems to land inside a message display that doesn't concern itself with failures - so this one is hard to fix, yet we can replace the default Tastypie error message as is done in this PR. I didn't manage to recreate the actual issue though.
Other than that, the below error message will now be shown in all cases of Backbone errors and errors in Ajax requests. I'm not familiar with any expected failures in our current codebase.
Is this too aggressive?
#5123

Experiment with universal user-oriented js error handling

---

requirements_dev.txt
requirements_sphinx.txt

Running `make dist` in KA Lite `develop branch` will have this error:
> Exception occurred:
File "/Users/user/.virtualenvs/kalite-b1/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 1
Hi @benjaoming I downgraded the `docutils` package as  a quick fix on [sphinx issue](https://github.com/sphinx-doc/sphinx/issues/3212).

Downgrade docutils package to fix sphinx issue.

---

kalite/distributed/static/js/distributed/bundle_modules/base.js

Apparrently `ajaxError` is called with a status code `0`. Not sure why, but this fix will conservatively stick to displaying error messages when codes match `500`. Let's expand it once we discover which codes are appropriate.
#5365

Only display error messages when status code matches 500

---

requirements_dev.txt
requirements_sphinx.txt

Reverts learningequality/ka-lite#5362
Not able to accommodate because RTD complained:
https://readthedocs.org/projects/ka-lite/builds/4796414/

Revert "Downgrade docutils package to fix sphinx issue."

---

kalite/cli.py

Failed to insert linebreaks:
Before:
To access KA Lite from another connected computer, try the following address(es):	http://192.168.1.1:8008/	http://192.168.1.2:8008/To access KA Lite from this machine, try the following address:	http://127.0.0.1:8008/
Now:
```
To access KA Lite from another connected computer, try the following address(es):
http://192.168.1.1:8008/
http://192.168.1.2:8008/
To access KA Lite from this machine, try the following address:
http://127.0.0.1:8008/
```

Add missing linebreaks in stout

---

docs/installguide/release_notes.rst
requirements.txt

Now releasing the 0.12 django-tastypie-legacy package in order to service our legacy South needs.
Fixes #5319

Remove dependency link and depend on django-tastypie-legacy

---

docs/installguide/release_notes.rst
kalite/distributed/custom_context_processors.py
kalite/distributed/settings.py
kalite/distributed/tests/browser_tests/distributed.py
kalite/facility/settings.py
kalite/legacy/i18n_settings.py
kalite/legacy/updates_settings.py
kalite/main/settings.py
kalite/packages/bundled/fle_utils/chronograph/settings.py
kalite/packages/bundled/securesync/settings.py
kalite/project/settings/demo.py
kalite/project/settings/nalanda.py
kalite/settings/__init__.py
kalite/settings/base.py

These settings raised exceptions in 0.16 and should be harmless to remove
#4830

Rm CONFIG_PACKAGE and local_settings

---

docs/installguide/release_notes.rst
kalite/distributed/management/commands/contentpackchecker.py
kalite/distributed/management/commands/retrievecontentpack.py
kalite/distributed/management/commands/setup.py
kalite/i18n/base.py
kalite/settings/base.py
kalite/topic_tools/annotate.py

* Reduces HTTP logging on dev server to something readable
* Fixes `kalite manage contentpackchecker all --update` so it only updates installed content packs
* Unpacks subtitle files `*.vtt` to `CONTENT_ROOT/srt`: Annotates with updated url and no longer needs to ignore any file or folder patterns during `collectstatic`
Let me know if you find anything unacceptable here. New static files handing will be described in release notes.
#5073

Static files from content packs served from CONTENT_ROOT

---

Makefile
docs/installguide/release_notes.rst
setup.py

Dependency links are not support in Pip 9, which is already released. But we haven't needed them since #5319 was solved.
- Removing this should ensure that `ka-lite-static` builds on Pip 9.
- Also added a make target `sdist` for installers.

Remove artifacts from dependency links

---

docs/installguide/release_notes.rst

Finalizing release notes, should be the last step before 0.17.x is ready for release :)

Finalize release notes for 0.17 - still needs proofreading

---

Makefile
kalite/distributed/features/steps/superuser_create.py
kalite/distributed/features/superuser_create.feature
kalite/distributed/middleware.py
kalite/distributed/static/js/distributed/utils/api.js
kalite/distributed/templates/distributed/base.html
kalite/packages/bundled/fle_utils/django_utils/middleware.py
kalite/packages/bundled/fle_utils/internet/classes.py
kalite/project/settings/dev.py
kalite/updates/static/js/updates/bundle_modules/update_languages.js

Since the actual issue was due to upstream HTTP headers and `OPTIONS` returning 405, there was nothing to fix.
Instead, I leave us with some:
1) Removes some homebrewed `JsonAsHTML` debug middleware that was really breaking stuff in debug mode.
1) Additional JS console output in case of failure
1) Fixing broken debug-toolbar due to fetching online resources
1) A CSP middleware that's only enabled with DEBUG=True and blocks online sources so we won't make mistakes in the future
1) Disables `tota11y` by default, but enables it with `USE_TOTA11Y=True` in settings @radinamatic 
#5348

Add additional logging during AJAX request failures + CSP middleware for debugging

---

docs/installguide/release_notes.rst
kalite/packages/bundled/fle_utils/internet/functions.py
kalite/packages/bundled/securesync/devices/api_views.py
kalite/packages/bundled/securesync/devices/decorators.py
kalite/settings/base.py
kalite/updates/tests/regression_tests.py

It's fine that kalite.learningequality.org redirects. However, with the mess that `am_i_online` was, it wasn't actually doing the test right.
So I simplified it to a function that doesn't accept arguments.
Also, it doesn't check the root URL since this one redirects, but looks for a well-known API endpoint... which hopefully, we won't remove :)
* Outputs logging from `fle_utils`
* Increases reliability of `am_i_online`
* Add release note
Not expecting anyone to jump in on this, but feel free, @jamalex and @aronasorman - since this is a last-minute release blocker that will ship shortly.
#5401

Simplify am_i_online which broke because of a 301 on kalite.learninequality.org

---

docs/installguide/release_notes.rst
kalite/distributed/templates/distributed/500.html
kalite/distributed/views.py
kalite/packages/bundled/securesync/devices/views.py
kalite/updates/tests/regression_tests.py

Due to various issues reported, I'm trying to affirm that device registration works through a bit of fumbling.
* Add an additional test case to clear that *online* presence is correctly detected.
#5401 
#5123

Additional fixes for device registration

---

docs/installguide/install_all.rst

Users who are not navigating to the latest docs should at least be aware of what version the installation instructions are linking to.
Will be cherry-picked to other release branches.
#5165

Make version visible in docs for installation guide

---

docs/installguide/release_notes.rst
kalite/packages/bundled/fle_utils/videos.py

`os.path.getsize` returns bytes, should be safe since file object is closed after returning from `download_file`
This is a potential problem for small devices downloading huge videos.
I've checked this by fetching a video.
#2909

Do not load video into memory to check its size, just use disk stats

---

circle.yml
docs/installguide/release_notes.rst
kalite/cli.py
kalite/distributed/management/commands/initialize_kalite.py
kalite/distributed/management/commands/setup.py
kalite/distributed/tests/__init__.py
kalite/distributed/tests/cli_tests.py
kalite/packages/bundled/README.django.md
kalite/settings/base.py

Taking over from #5438
This also (once again) prints the server address at command line ( a regression from #5364 )
Let me know if there are problems in this approach. I don't see much of a difference, except I forced ALL of the loggers in `kalite.distributed.management.commands` to user a logger WITHOUT formatting, expecting their outputs to be generally targeted for command line displaying.
However, they are also subject to be printed in the server log.
#5408

 Add logging to setup and initialize_kalite (2)

---

docs/installguide/release_notes.rst
kalite/cli.py
kalite/distributed/static/css/distributed/bootstrap-overrides.less

Simple fix. Hopefully it doesn't break other aspects of our buttons, but manual tests of the next prerelease will have to verify this @radinamatic 
Otherwise, this is easy to revert.
None, will be thoroughly tested in the prerelease
#5004

Add line breaks in buttons so text isn't cut

---

docs/developer_docs/logging.rst
docs/faq.rst
docs/installguide/release_notes.rst
kalite/cli.py
kalite/settings/base.py

This is a new feature, but I'm going for 0.17.1 because it's super important to have logs for stuff.. especially tech support.
We might wanna make extra sure that this works on Windows, but I don't think there's a lot to review here.. I've manually tried it out, and it works :) But all the tests will end up logging things, too!
#4890

Log rotation

---

docs/installguide/advanced.rst
docs/installguide/install_all.rst
docs/installguide/install_main.rst

I found a bunch of things that were hard to read or badly structured, so did a bit of clean up.
Ultimately, I think we should get rid of `install_all` because it's way too long and cluttered.
Maybe look for typos :)
#5459

Docs TOC level and installation instruction improvements

---

README.rst

We have stopped using the list because we prefer the community forums: http://community.learningequality.org/

Remove Google Groups link (it's now an announce list)

---

circle.yml

Move a bunch of dependency setup that affects all containers to the dependency build so the build fails when any of these steps fail
Before, our builds would continue even though JS asset building had failed. Which created a lot of confusing errors in Selenium tests.

Re-arrange CI test build steps

---

kalite/coachreports/api_views.py

When trying to select a `Theme` inside `Teach` tab and submits it, the `Show Tabular Reports` displays resource titles in English.
Just a quick fix.
#5494 
pinging @radinamatic @benjaoming for this

Quick fix for resource titles

---

kalite/coachreports/static/js/coachreports/coach_reports/hbtemplates/landing.handlebars
kalite/coachreports/static/js/coachreports/coach_reports/views.js
kalite/coachreports/static/js/coachreports/tabular_reports/hbtemplates/tabular-view.handlebars

@radinamatic suggested to unify the `Color Legends` together with the `Keys`
#5510 
#5494

Remove color legends

---

docs/installguide/release_notes.rst
kalite/facility/api_resources.py

Reference: https://stackoverflow.com/a/18477897
FYI @benjaoming @Aypak 
It seems that tastypie automatically limits the API request to `1000` and I have no idea why do they do that.
I was not able to replicate the issue when there are 1,000 users registered in a facility. But I think this fixes the issue since it is already returning the number of expected users
`{"meta": {"limit": 0, "offset": 0, "total_count": 1011}`
#5523

Set max_limit to 0 in order to fetch all users.

---

docs/developer_docs/behave_testing.rst
docs/developer_docs/environment.rst
docs/developer_docs/index.rst
docs/installguide/release_notes.rst
docs/usermanual/userman_admin.rst
kalite/packages/bundled/fle_utils/internet/download.py
kalite/packages/bundled/fle_utils/videos.py
kalite/testing/base.py
kalite/topic_tools/content_models.py
kalite/updates/download_track.py
kalite/updates/management/commands/videodownload.py
kalite/updates/settings.py
kalite/updates/tests/__init__.py
kalite/updates/tests/base.py
kalite/updates/tests/download_tests.py
kalite/updates/videos.py

Debugging #5528, I found that the issue seems to be the lack of retries when connections are broken or temporarily unresolved.
Any error in downloading a video or thumbnail results in an item being skipped in the queue. This could also explain why the resized videos torrent set has consistently been missing a couple of items.. downloading 30+k files would usually result in a couple of errors. From my own connection, I had 197 errors out of 15k thumbnail downloads. FYI: @jamalex 
Assuming no external use of `download_file` and other refactored components. Central server will not be upgraded immediately.
#5528

Make video/thumbnail download more robust

---

docs/installguide/release_notes.rst

Had anticipated to fix missing videos in torrent sets, but there weren't any (I think it must have been pre- the July content pack that I observed it)
@jamalex This! Sorry about having expressed otherwise -- I'm still confident that I've downloaded torrent sets before that didn't have all videos... but now it's tested and with the latest content pack, the videos from the torrent match 100%.

Remove inaccurate release note

---

docs/installguide/release_notes.rst

This addresses #5561 so that people are finally informed that this is a flaw of 0.17.
We will prioritize getting 0.18 out ASAP, just for the sake of this content pack update!
This is a docs upgrade so it mainly just needs to be merged to master and `0.17.x` to get exposure on RTD.
Additional note: I'm removing the 0.17.5 milestone.
n/a
#5561

Add known issue about content packs in 0.17 series

---

docs/installguide/release_notes.rst
kalite/distributed/management/commands/retrievecontentpack.py
kalite/updates/api_views.py
kalite/updates/management/utils.py

Before, we called `update_stage`, which would write progress to the DB. A pretty bad idea.
On RPi, it basically meant it was impossible to run `retrievecontentpack` in some cases.
Thanks @holta for reporting this!
I know this isn't necessarily nicely done or follows through with any kind of consequence for other commands, but this fixes the immediate issue for RPi.
#5575
#4892

RPi fix: Make running retrievecontentpack download NOT update the DB

---

.buildkite/build_and_upload_artifact.sh
.buildkite/setup_and_upload_artifacts.sh
Dockerfile
Makefile
kalite/testing/testrunner.py
setup.py

Remove usage of retrievecontentpack --foreground

---

docs/installguide/release_notes.rst
kalite/updates/tests/download_tests.py

Apologies @mrpau-richard - of course when changing CLI, there should be a release note about it.

Add a note that the --foreground flag is gone.

---

kalite/distributed/management/commands/setup.py

The current setup command wrongly claims that a database file exists and will be backed up on a clean release:
```
$ rm -rf ~/.kalite
$ kalite start --foreground
Running 'kalite start' in foreground...
Generating a new secret key file ~/.kalite/secretkey.txt...
Setting up KA Lite; this may take a few minutes; please wait!
_   __  ___    _     _ _          
| | / / / _ \  | |   (_) |         
| |/ / / /_\ \ | |    _| |_ ___    
|    \ |  _  | | |   | | __/ _ \   
| |\  \| | | | | |___| | ||  __/   
\_| \_/\_| |_/ \_____/_|\__\___|   
https://learningequality.org/ka-lite/
version 0.17.2
(Re)moving database file to temp location, starting clean install. Recovery location: /tmp/tmpkPYEPM
```

Fix database move message
